import { createHmac, createHash } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { generateEntityId } from "@/lib/core/identifiers";

const roles=["Dealer Principal / Owner","General Manager","Sales Manager","BDC","Finance","Inventory","Service","Other"] as const;
const rooftops=["1","2–5","6–15","16+"] as const;
const interests=["Connected customer workflow","Sales and BDC","Management visibility","Inventory","DealerFlow AI","Multi-rooftop operations"] as const;
const contacts=["Email","Phone"] as const;
export interface DemoRequestInput{firstName:string;lastName:string;email:string;phone?:string;dealership:string;role:string;rooftops:string;crm?:string;interest:string;contact:string;notes?:string;website?:string}
export interface DemoRequestResult{id:string;created:boolean}
export class DemoRequestValidationError extends Error{constructor(readonly issues:readonly string[]){super("Demo request is invalid.");this.name="DemoRequestValidationError"}}
export class DemoRequestRateLimitError extends Error{constructor(){super("Too many demo requests were received. Please try again later.");this.name="DemoRequestRateLimitError"}}
export class DemoRequestConflictError extends Error {
  constructor() {
    super("The idempotency key was already used for a different demo request.");
    this.name = "DemoRequestConflictError";
  }
}

export class DemoRequestIntake{
  constructor(private readonly pool:Pool,private readonly secret:string,private readonly ownerEmail:string){}
  async submit(input:DemoRequestInput,networkIdentity:string,idempotencyKey:string):Promise<DemoRequestResult>{
    const value=validate(input);const networkFingerprint=hmac(this.secret,networkIdentity||"unknown");const requestFingerprint=hash(JSON.stringify(value));const day=new Date().toISOString().slice(0,10);const deduplicationKey=hash(`${value.email}|${value.dealership.toLowerCase()}|${day}`);
    const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`demo:${networkFingerprint}`]);const existing=await client.query<{id:string;idempotency_key:string;request_fingerprint:string}>("SELECT id,idempotency_key,request_fingerprint FROM commercial_demo_requests WHERE idempotency_key=$1 OR deduplication_key=$2 ORDER BY (idempotency_key=$1) DESC LIMIT 1",[idempotencyKey,deduplicationKey]);if(existing.rows[0]){if(existing.rows[0].idempotency_key===idempotencyKey&&existing.rows[0].request_fingerprint!==requestFingerprint)throw new DemoRequestConflictError();await client.query("COMMIT");return{id:existing.rows[0].id,created:false};}
      const limits=await client.query<{network_count:number;email_count:number}>("SELECT count(*) FILTER(WHERE network_fingerprint=$1 AND created_at>now()-interval '1 hour')::int network_count,count(*) FILTER(WHERE work_email=$2 AND created_at>now()-interval '1 day')::int email_count FROM commercial_demo_requests",[networkFingerprint,value.email]);if((limits.rows[0]?.network_count??0)>=5||(limits.rows[0]?.email_count??0)>=3)throw new DemoRequestRateLimitError();
      const id=generateEntityId("cdr");await client.query(`INSERT INTO commercial_demo_requests(id,first_name,last_name,work_email,phone,dealership_name,role,rooftop_range,current_crm,primary_interest,preferred_contact_method,notes,idempotency_key,deduplication_key,request_fingerprint,network_fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[id,value.firstName,value.lastName,value.email,value.phone??null,value.dealership,value.role,value.rooftops,value.crm??null,value.interest,value.contact,value.notes??null,idempotencyKey,deduplicationKey,requestFingerprint,networkFingerprint]);
      await event(client,id,"received",{preferredContactMethod:value.contact,rooftopRange:value.rooftops});await client.query(`INSERT INTO transactional_email_messages(id,kind,recipient_email,subject,text_body,html_body,idempotency_key) VALUES($1,'commercial-demo-request',lower($2),$3,$4,$5,$6)`,[generateEntityId("tem"),this.ownerEmail,`DealerFlow demo request: ${value.dealership}`,textBody(value,id),htmlBody(value,id),`commercial-demo-request:${id}`]);await event(client,id,"notification-queued",{channel:"transactional-email"});await client.query("UPDATE commercial_demo_requests SET status='notification-queued',updated_at=now() WHERE id=$1",[id]);await client.query("COMMIT");return{id,created:true};
    }catch(error){await client.query("ROLLBACK").catch(()=>undefined);throw error;}finally{client.release();}
  }
}
function validate(input:DemoRequestInput){const issues:string[]=[];const clean=(value:string|undefined,max:number)=>value?.trim().slice(0,max)||undefined;const firstName=clean(input.firstName,100);const lastName=clean(input.lastName,100);const email=clean(input.email,320)?.toLowerCase();const dealership=clean(input.dealership,200);if(!firstName)issues.push("First name is required.");if(!lastName)issues.push("Last name is required.");if(!email||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))issues.push("A valid work email is required.");if(!dealership)issues.push("Dealership or group is required.");if(!roles.includes(input.role as typeof roles[number]))issues.push("Role is invalid.");if(!rooftops.includes(input.rooftops as typeof rooftops[number]))issues.push("Rooftop range is invalid.");if(!interests.includes(input.interest as typeof interests[number]))issues.push("Primary interest is invalid.");if(!contacts.includes(input.contact as typeof contacts[number]))issues.push("Preferred contact method is invalid.");if(input.website?.trim())issues.push("Request could not be accepted.");if(issues.length)throw new DemoRequestValidationError(issues);return{firstName:firstName!,lastName:lastName!,email:email!,dealership:dealership!,role:input.role,rooftops:input.rooftops,interest:input.interest,contact:input.contact,...(clean(input.phone,40)?{phone:clean(input.phone,40)}:{}),...(clean(input.crm,200)?{crm:clean(input.crm,200)}:{}),...(clean(input.notes,1000)?{notes:clean(input.notes,1000)}:{})};}
function hmac(secret:string,value:string){return createHmac("sha256",secret).update(value).digest("hex");}function hash(value:string){return createHash("sha256").update(value).digest("hex");}
async function event(client:PoolClient,requestId:string,eventType:string,evidence:Record<string,unknown>){await client.query("INSERT INTO commercial_demo_request_events(id,request_id,event_type,evidence) VALUES($1,$2,$3,$4)",[generateEntityId("cde"),requestId,eventType,evidence]);}
function textBody(v:ReturnType<typeof validate>,id:string){return [`Demo request ${id}`,`Name: ${v.firstName} ${v.lastName}`,`Work email: ${v.email}`,`Dealership: ${v.dealership}`,`Role: ${v.role}`,`Rooftops: ${v.rooftops}`,`Interest: ${v.interest}`,`Preferred contact: ${v.contact}`,v.phone?`Phone: ${v.phone}`:"",v.crm?`Current CRM: ${v.crm}`:"",v.notes?`Notes: ${v.notes}`:""].filter(Boolean).join("\n");}
function htmlBody(v:ReturnType<typeof validate>,id:string){return `<h1>DealerFlow demo request</h1><p>Reference: ${escape(id)}</p><p>${escape(v.firstName)} ${escape(v.lastName)} from ${escape(v.dealership)}</p><p>Work email: ${escape(v.email)}<br>Role: ${escape(v.role)}<br>Rooftops: ${escape(v.rooftops)}<br>Interest: ${escape(v.interest)}<br>Preferred contact: ${escape(v.contact)}</p>`;}function escape(value:string){return value.replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);}
