import type { AuthorizationActor } from "@/lib/platform/auth";
import { assertAuthorized,assertFeatureEnabled } from "@/lib/platform/auth";

export const customerRecommendationPromptVersion="customer-next-action-v1";
export type RecommendationUrgency="low"|"medium"|"high"|"immediate";
export interface RecommendationEvidence { id:string; category:"engagement"|"appointment"|"vehicle"|"deal"|"communication"|"task"; observation:string; observedAt:string }
export interface CustomerRecommendation { primaryAction:string; rationale:string; evidenceIds:readonly string[]; confidence:number; urgency:RecommendationUrgency; timeHorizon:string; risks:readonly string[]; opportunities:readonly string[]; supportingActions:readonly string[] }
export interface RecommendationGeneration { providerResponseId:string; model:string; recommendation?:CustomerRecommendation; refusal?:string; inputTokens?:number; outputTokens?:number; latencyMs:number }
export interface CustomerRecommendationGateway { generate(input:{evidence:readonly RecommendationEvidence[];idempotencyKey:string;promptVersion:string}):Promise<RecommendationGeneration> }
export interface RecommendationRunProvider {
  begin(input:{organizationId:string;customerId:string;leadId?:string;actorId:string;evidence:readonly RecommendationEvidence[];promptVersion:string;idempotencyKey:string}):Promise<{runId:string;created:boolean;generation?:RecommendationGeneration}>;
  complete(input:{organizationId:string;actorId:string;runId:string;generation:RecommendationGeneration}):Promise<void>;
  fail(input:{organizationId:string;actorId:string;runId:string;code:string}):Promise<void>;
  review(input:{organizationId:string;actorId:string;runId:string;decision:"accepted"|"dismissed";note?:string}):Promise<boolean>;
}
export class RecommendationValidationError extends Error { constructor(readonly issues:readonly string[]){super("Recommendation request is invalid.");this.name="RecommendationValidationError";} }
export class CustomerRecommendationService {
  constructor(private readonly provider:RecommendationRunProvider,private readonly gateway:CustomerRecommendationGateway){}
  async generate(input:{actor:AuthorizationActor;organizationId:string;customerId:string;leadId?:string;evidence:readonly RecommendationEvidence[];idempotencyKey:string}){
    assertAuthorized(input.actor,{organizationId:input.organizationId,capability:"customer.read"});assertFeatureEnabled(input.actor,input.organizationId,"ai");validateInput(input);
    const run=await this.provider.begin({organizationId:input.organizationId,customerId:input.customerId,...(input.leadId?{leadId:input.leadId}:{}),actorId:input.actor.userId,evidence:input.evidence,promptVersion:customerRecommendationPromptVersion,idempotencyKey:input.idempotencyKey});
    if(!run.created){if(run.generation)validateGeneration(run.generation,input.evidence);return{runId:run.runId,created:false,...(run.generation?{generation:run.generation}:{})};}
    try{const generation=await this.gateway.generate({evidence:input.evidence,idempotencyKey:run.runId,promptVersion:customerRecommendationPromptVersion});validateGeneration(generation,input.evidence);await this.provider.complete({organizationId:input.organizationId,actorId:input.actor.userId,runId:run.runId,generation});return{runId:run.runId,created:true,generation};}
    catch(error){await this.provider.fail({organizationId:input.organizationId,actorId:input.actor.userId,runId:run.runId,code:error instanceof RecommendationValidationError?"invalid-provider-output":"provider-failed"});throw error;}
  }
  async review(input:{actor:AuthorizationActor;organizationId:string;runId:string;decision:"accepted"|"dismissed";note?:string}){assertAuthorized(input.actor,{organizationId:input.organizationId,capability:"customer.update"});assertFeatureEnabled(input.actor,input.organizationId,"ai");if(!/^air_[a-z0-9_-]{6,64}$/.test(input.runId))throw new RecommendationValidationError(["runId is invalid."]);if(input.note&&input.note.length>500)throw new RecommendationValidationError(["note must not exceed 500 characters."]);if(!await this.provider.review({organizationId:input.organizationId,actorId:input.actor.userId,runId:input.runId,decision:input.decision,...(input.note?{note:input.note.trim()}: {})}))throw new RecommendationValidationError(["Only completed, unreviewed recommendations may be reviewed."]);}
}
function validateInput(input:{customerId:string;leadId?:string;evidence:readonly RecommendationEvidence[];idempotencyKey:string}){const issues:string[]=[];if(!/^cus_[a-z0-9_-]{6,64}$/.test(input.customerId))issues.push("customerId is invalid.");if(input.leadId&&!/^led_[a-z0-9_-]{6,64}$/.test(input.leadId))issues.push("leadId is invalid.");if(input.evidence.length<1||input.evidence.length>30)issues.push("Between 1 and 30 evidence items are required.");if(!/^[A-Za-z0-9:_-]{8,200}$/.test(input.idempotencyKey))issues.push("idempotencyKey is invalid.");const ids=new Set<string>();for(const item of input.evidence){if(!/^[A-Za-z0-9:_-]{3,100}$/.test(item.id)||ids.has(item.id))issues.push("Evidence IDs must be unique and valid.");ids.add(item.id);if(!item.observation.trim()||item.observation.length>500)issues.push("Evidence observations must contain 1 to 500 characters.");if(Number.isNaN(Date.parse(item.observedAt)))issues.push("Evidence timestamps must be ISO dates.");}if(issues.length)throw new RecommendationValidationError(issues);}
export function validateGeneration(generation:RecommendationGeneration,evidence:readonly RecommendationEvidence[]){if(Boolean(generation.recommendation)===Boolean(generation.refusal))throw new RecommendationValidationError(["Provider must return one recommendation or refusal."]);const recommendation=generation.recommendation;if(!recommendation)return;const allowed=new Set(evidence.map((item)=>item.id));const valid=recommendation.primaryAction.trim()&&recommendation.primaryAction.length<=200&&recommendation.rationale.trim()&&recommendation.rationale.length<=600&&recommendation.confidence>=0&&recommendation.confidence<=100&&recommendation.evidenceIds.length>0&&recommendation.evidenceIds.every((id)=>allowed.has(id))&&recommendation.risks.length<=5&&recommendation.opportunities.length<=5&&recommendation.supportingActions.length<=5;if(!valid)throw new RecommendationValidationError(["Provider recommendation failed validation."]);}
