import { describe,expect,it,vi } from "vitest";
import type { AuthorizationActor } from "@/lib/platform/auth";
import { CustomerRecommendationService,RecommendationValidationError,type CustomerRecommendationGateway,type RecommendationEvidence,type RecommendationRunProvider } from "./customer-recommendation";
const actor:AuthorizationActor={userId:"usr_salesperson",memberships:[{organizationId:"org_dealerflow",locationIds:["loc_main"],capabilities:["customer.read","customer.update"]}]};
const evidence:RecommendationEvidence[]=[{id:"appointment:apt_123456",category:"appointment",observation:"Test drive is confirmed for tomorrow.",observedAt:"2026-08-25T14:00:00.000Z"},{id:"vehicle:vhi_123456",category:"vehicle",observation:"Primary vehicle is available.",observedAt:"2026-08-24T12:00:00.000Z"}];
const generation={providerResponseId:"resp_123",model:"gpt-5.6",latencyMs:1200,inputTokens:200,outputTokens:100,recommendation:{primaryAction:"Confirm the test drive details.",rationale:"The appointment is tomorrow and the vehicle is available.",evidenceIds:[evidence[0]!.id,evidence[1]!.id],confidence:92,urgency:"high" as const,timeHorizon:"Before close of business",risks:[],opportunities:["Reinforce vehicle availability."],supportingActions:["Prepare the vehicle."]}};
function providers(created=true){const run:RecommendationRunProvider={begin:vi.fn().mockResolvedValue({runId:"air_recommend1",created}),complete:vi.fn(),fail:vi.fn(),review:vi.fn().mockResolvedValue(true)};const gateway:CustomerRecommendationGateway={generate:vi.fn().mockResolvedValue(generation)};return{run,gateway};}
describe("CustomerRecommendationService",()=>{
  it("persists the run before generation and completes validated evidence-cited guidance",async()=>{const{run,gateway}=providers();const result=await new CustomerRecommendationService(run,gateway).generate({actor,organizationId:"org_dealerflow",customerId:"cus_customer1",leadId:"led_buycycle1",evidence,idempotencyKey:"ai:request-123"});expect(result.generation?.recommendation?.confidence).toBe(92);expect(run.begin).toHaveBeenCalledBefore(gateway.generate as ReturnType<typeof vi.fn>);expect(run.complete).toHaveBeenCalledOnce();});
  it("rejects unsupported evidence citations and records a safe failure code",async()=>{const{run,gateway}=providers();vi.mocked(gateway.generate).mockResolvedValue({...generation,recommendation:{...generation.recommendation,evidenceIds:["fabricated"]}});await expect(new CustomerRecommendationService(run,gateway).generate({actor,organizationId:"org_dealerflow",customerId:"cus_customer1",evidence,idempotencyKey:"ai:request-123"})).rejects.toBeInstanceOf(RecommendationValidationError);expect(run.fail).toHaveBeenCalledWith(expect.objectContaining({code:"invalid-provider-output"}));});
  it("requires human-review permission and prevents a second review",async()=>{const{run,gateway}=providers();await new CustomerRecommendationService(run,gateway).review({actor,organizationId:"org_dealerflow",runId:"air_recommend1",decision:"accepted"});expect(run.review).toHaveBeenCalledOnce();vi.mocked(run.review).mockResolvedValue(false);await expect(new CustomerRecommendationService(run,gateway).review({actor,organizationId:"org_dealerflow",runId:"air_recommend1",decision:"dismissed"})).rejects.toBeInstanceOf(RecommendationValidationError);});
  it("fails closed when the tenant AI module is disabled",async()=>{const{run,gateway}=providers();const disabled:AuthorizationActor={...actor,memberships:[{...actor.memberships[0]!,features:{ai:false}}]};await expect(new CustomerRecommendationService(run,gateway).generate({actor:disabled,organizationId:"org_dealerflow",customerId:"cus_customer1",evidence,idempotencyKey:"ai:request-123"})).rejects.toThrow("permission");expect(run.begin).not.toHaveBeenCalled();expect(gateway.generate).not.toHaveBeenCalled();});
});
