import { NextResponse } from "next/server";
import { CustomerRecommendationService,RecommendationValidationError } from "@/lib/application/ai";
import { OpenAIRecommendationGateway,AIProviderError } from "@/lib/integrations/ai";
import { AuthorizationError,type Capability } from "@/lib/platform/auth";
import { AuthenticationError,MembershipError,PostgresMembershipReader,authenticateOrganizationRequest } from "@/lib/server/auth";
import { buildCustomerRecommendationEvidence,PostgresRecommendationRunProvider } from "@/lib/server/ai";
import { parseServerEnvironment } from "@/lib/server/config";
import { CustomerWorkspaceReader } from "@/lib/server/customers";
import { getDatabasePool } from "@/lib/server/database";
import { OperationalReporter,resolveCorrelationId } from "@/lib/server/observability";

export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=30;
interface Context{params:Promise<{organizationId:string;customerId:string}>}
export async function POST(request:Request,context:Context){const correlationId=resolveCorrelationId(request);try{const{organizationId,customerId}=await context.params;const idempotencyKey=request.headers.get("idempotency-key")?.trim();if(!idempotencyKey)return problem(400,"invalid_request","Idempotency-Key is required.",correlationId);const pool=getDatabasePool();const actor=await authenticateOrganizationRequest(request,organizationId,new PostgresMembershipReader(pool));const membership=actor.memberships[0]!;const has=(capability:Capability)=>membership.capabilities.includes(capability);const record=await new CustomerWorkspaceReader(pool).read(actor.userId,organizationId,customerId,{locationIds:membership.locationIds,communications:has("communication.read"),appointments:has("appointment.read"),tasks:has("task.read"),inventory:has("inventory.read"),deals:has("deal.read")});if(!record)return problem(404,"not_found","Customer was not found.",correlationId);const evidence=buildCustomerRecommendationEvidence(record);if(!evidence.length)return problem(409,"insufficient_evidence","No authoritative evidence is available for a recommendation.",correlationId);const environment=parseServerEnvironment(process.env,{ai:true});const service=new CustomerRecommendationService(new PostgresRecommendationRunProvider(pool),new OpenAIRecommendationGateway({apiKey:environment.openaiApiKey!,model:environment.aiModel!}));const result=await service.generate({actor,organizationId,customerId,...(record.lead?{leadId:record.lead.id}:{}),evidence,idempotencyKey});if(result.created&&result.generation)await new OperationalReporter(environment).report({code:"ai.recommendation.completed",severity:"info",correlationId,organizationId,attributes:{runId:result.runId,model:result.generation.model,latencyMs:result.generation.latencyMs,inputTokens:result.generation.inputTokens??0,outputTokens:result.generation.outputTokens??0,refused:Boolean(result.generation.refusal)}});return NextResponse.json(result,{status:result.created?201:200,headers:{"cache-control":"private, no-store","x-correlation-id":correlationId}});}catch(error){if(error instanceof AuthenticationError)return problem(401,"unauthorized",error.message,correlationId);if(error instanceof MembershipError||error instanceof AuthorizationError)return problem(403,"forbidden","AI recommendations are not permitted.",correlationId);if(error instanceof RecommendationValidationError)return NextResponse.json({error:"invalid_request",message:error.message,issues:error.issues,correlationId},{status:400,headers:{"cache-control":"no-store","x-correlation-id":correlationId}});if(error instanceof AIProviderError)return problem(503,"ai_unavailable","AI guidance is temporarily unavailable.",correlationId);return problem(500,"internal_error","Recommendation generation failed.",correlationId);}}
function problem(status:number,error:string,message:string,correlationId:string){return NextResponse.json({error,message,correlationId},{status,headers:{"cache-control":"no-store","x-correlation-id":correlationId}});}
