import { withTenantDatabaseContext, type DatabasePool } from "@/lib/server/database";
export interface DealDirectoryItem { id: string; dealNumber: string; locationId: string; customerId: string; customerName: string; leadId: string; status: string; purchaseType?: string; agreedPriceCents?: number; vehicleLabel: string; stockNumber?: string; updatedAt: string; }
export class DealDirectoryError extends Error { constructor(message: string) { super(message); this.name = "DealDirectoryError"; } }
export class DealDirectoryReader { constructor(private readonly pool: DatabasePool) {} list(context: { userId: string; organizationId: string; locationIds: readonly string[] | "all" }, query: { status?: string; search?: string; limit?: number }): Promise<{ records: DealDirectoryItem[] }> { const limit = query.limit ?? 50; if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new DealDirectoryError("limit must be between 1 and 100."); const statuses = ["draft", "working", "pending-approval", "approved", "contracted", "delivered", "cancelled"]; if (query.status && !statuses.includes(query.status)) throw new DealDirectoryError("status is invalid."); const search = query.search?.trim().slice(0, 100) ?? ""; return withTenantDatabaseContext(this.pool, context, async (client) => { const all = context.locationIds === "all"; const locations = all ? [] : [...context.locationIds]; const result = (await client.query(`SELECT d.id, d.deal_number, d.location_id, d.customer_id, c.display_name AS customer_name,
      d.lead_id, d.status, d.purchase_type, d.agreed_price_cents, d.updated_at,
      v.year::text || ' ' || v.make || ' ' || v.model || CASE WHEN v.trim IS NULL THEN '' ELSE ' ' || v.trim END AS vehicle_label,
      i.stock_number FROM deals d JOIN customers c ON c.organization_id = d.organization_id AND c.id = d.customer_id
      JOIN vehicles v ON v.organization_id = d.organization_id AND v.id = d.primary_vehicle_id
      LEFT JOIN inventory_units i ON i.organization_id = d.organization_id AND i.id = d.inventory_unit_id
      WHERE d.organization_id = $1 AND ($2::boolean OR d.location_id = ANY($3::text[]))
        AND ($4::text IS NULL OR d.status::text = $4)
        AND ($5 = '' OR d.deal_number ILIKE '%' || $5 || '%' OR c.display_name ILIKE '%' || $5 || '%' OR v.vin ILIKE '%' || $5 || '%')
      ORDER BY CASE WHEN d.status IN ('delivered','cancelled') THEN 1 ELSE 0 END, d.updated_at DESC, d.id DESC LIMIT $6`, [context.organizationId, all, locations, query.status ?? null, search, limit])) as { rows: Array<{ id: string; deal_number: string; location_id: string; customer_id: string; customer_name: string; lead_id: string; status: string; purchase_type: string | null; agreed_price_cents: number | null; vehicle_label: string; stock_number: string | null; updated_at: Date }> }; return { records: result.rows.map((row) => ({ id: row.id, dealNumber: row.deal_number, locationId: row.location_id, customerId: row.customer_id, customerName: row.customer_name, leadId: row.lead_id, status: row.status, ...(row.purchase_type ? { purchaseType: row.purchase_type } : {}), ...(row.agreed_price_cents !== null ? { agreedPriceCents: row.agreed_price_cents } : {}), vehicleLabel: row.vehicle_label, ...(row.stock_number ? { stockNumber: row.stock_number } : {}), updatedAt: row.updated_at.toISOString() })) }; }); } }
