import type { Pool } from "pg";
import { HandoffIntegrityError, type DealDelivery, type DeliveryEvent, type DeliveryProvider, type DeliverySession, type TradeAppraisal, type TradeEvent, type TradeProvider, type TradeSession } from "@/lib/application/deals";
import { generateEntityId } from "@/lib/core/identifiers";
import type { OrganizationScope, RequestContext } from "@/lib/platform/data";
import type { SqlExecutor } from "@/lib/server/data";
import { withTenantDatabaseContext } from "@/lib/server/database";

export class PostgresTradeProvider implements TradeProvider { constructor(private readonly pool: Pool, private readonly context: { userId: string; organizationId: string }) {} transaction<Result>(operation: (session: TradeSession) => Promise<Result>) { return withTenantDatabaseContext(this.pool, this.context, (client) => operation(new TradeDb(client as unknown as SqlExecutor))); } }
export class PostgresDeliveryProvider implements DeliveryProvider { constructor(private readonly pool: Pool, private readonly context: { userId: string; organizationId: string }) {} transaction<Result>(operation: (session: DeliverySession) => Promise<Result>) { return withTenantDatabaseContext(this.pool, this.context, (client) => operation(new DeliveryDb(client as unknown as SqlExecutor))); } }
type TradeRow = { id: string; organization_id: string; location_id?: string; deal_id: string; vehicle_id: string; version: number; status: TradeAppraisal["status"]; allowance_cents: number; payoff_cents: number; equity_cents: number; odometer_miles: number | null; condition_notes: string | null; lienholder: string | null; expires_at: Date | null; acquired_inventory_unit_id: string | null; idempotency_key: string };
type TradeEventRow = { id: string; organization_id: string; appraisal_id: string; from_status: TradeEvent["fromStatus"] | null; to_status: TradeEvent["toStatus"]; reason: string | null; occurred_at: Date; idempotency_key: string };
const tradeColumns = "a.id, a.organization_id, a.deal_id, a.vehicle_id, a.version, a.status, a.allowance_cents, a.payoff_cents, a.equity_cents, a.odometer_miles, a.condition_notes, a.lienholder, a.expires_at, a.acquired_inventory_unit_id, a.idempotency_key";
class TradeDb implements TradeSession {
  constructor(private readonly db: SqlExecutor) {}
  async acquireLock(scope: OrganizationScope, key: string) { await lock(this.db, scope, key); }
  async findByIdempotency(scope: OrganizationScope, key: string) { const result = await this.db.query<TradeRow & { location_id: string }>(`SELECT ${tradeColumns}, d.location_id FROM trade_appraisals a JOIN deals d ON d.organization_id = a.organization_id AND d.id = a.deal_id WHERE a.organization_id = $1 AND a.idempotency_key = $2 LIMIT 1`, [scope.organizationId, key]); return result.rows[0] ? trade(result.rows[0]) : null; }
  async getContext(scope: OrganizationScope, dealId: string, vehicleId: string) { const result = await this.db.query<{ status: import("@/lib/application/deals").DealStatus; location_id: string }>(`SELECT d.status, d.location_id FROM deals d JOIN lead_vehicle_interests vi ON vi.organization_id = d.organization_id AND vi.lead_id = d.lead_id AND vi.customer_id = d.customer_id AND vi.vehicle_id = $3 AND vi.role = 'trade' AND vi.status = 'active' WHERE d.organization_id = $1 AND d.id = $2 LIMIT 1`, [scope.organizationId, dealId, vehicleId]); const row = result.rows[0]; return row ? { dealStatus: row.status, locationId: row.location_id } : null; }
  async nextVersion(scope: OrganizationScope, dealId: string, vehicleId: string) { const result = await this.db.query<{ version: number }>("SELECT COALESCE(max(version),0)::int + 1 AS version FROM trade_appraisals WHERE organization_id = $1 AND deal_id = $2 AND vehicle_id = $3", [scope.organizationId, dealId, vehicleId]); return result.rows[0]?.version ?? 1; }
  async create(context: RequestContext, item: TradeAppraisal, event: TradeEvent) { await this.db.query(`INSERT INTO trade_appraisals (id, organization_id, deal_id, vehicle_id, version, status, allowance_cents, payoff_cents, equity_cents, odometer_miles, condition_notes, lienholder, expires_at, idempotency_key, created_by, updated_by) VALUES ($1,$2,$3,$4,$5,'draft',$6,$7,$8,$9,$10,$11,$12,$13,$14,$14)`, [item.id, item.organizationId, item.dealId, item.vehicleId, item.version, item.allowanceCents, item.payoffCents, item.equityCents, item.odometerMiles ?? null, item.conditionNotes ?? null, item.lienholder ?? null, item.expiresAt ?? null, item.idempotencyKey, context.actorId]); await insertTradeEvent(this.db, context, event); await audit(this.db, context, "trade_appraisal.created", "trade_appraisal", item.id); return item; }
  async findTransition(scope: OrganizationScope, key: string) { const result = await this.db.query<TradeRow & { location_id: string; event_id: string; from_status: TradeEventRow["from_status"]; to_status: TradeEventRow["to_status"]; reason: string | null; occurred_at: Date; event_key: string }>(`SELECT ${tradeColumns}, d.location_id, e.id AS event_id, e.from_status, e.to_status, e.reason, e.occurred_at, e.idempotency_key AS event_key FROM trade_appraisal_status_events e JOIN trade_appraisals a ON a.organization_id=e.organization_id AND a.id=e.appraisal_id JOIN deals d ON d.organization_id=a.organization_id AND d.id=a.deal_id WHERE e.organization_id=$1 AND e.idempotency_key=$2 LIMIT 1`, [scope.organizationId, key]); const row = result.rows[0]; return row ? { appraisal: trade(row), event: tradeEvent({ id: row.event_id, organization_id: row.organization_id, appraisal_id: row.id, from_status: row.from_status, to_status: row.to_status, reason: row.reason, occurred_at: row.occurred_at, idempotency_key: row.event_key }) } : null; }
  async getForUpdate(scope: OrganizationScope, id: string) { const result = await this.db.query<TradeRow & { location_id: string; deal_status: import("@/lib/application/deals").DealStatus }>(`SELECT ${tradeColumns}, d.location_id, d.status AS deal_status FROM trade_appraisals a JOIN deals d ON d.organization_id=a.organization_id AND d.id=a.deal_id WHERE a.organization_id=$1 AND a.id=$2 FOR UPDATE OF a`, [scope.organizationId, id]); const row = result.rows[0]; return row ? { appraisal: trade(row), dealStatus: row.deal_status, locationId: row.location_id } : null; }
  async hasAccepted(scope: OrganizationScope, dealId: string, vehicleId: string, exceptId: string) { const result = await this.db.query<{ exists: boolean }>("SELECT EXISTS (SELECT 1 FROM trade_appraisals WHERE organization_id=$1 AND deal_id=$2 AND vehicle_id=$3 AND id<>$4 AND status IN ('accepted','acquired')) AS exists", [scope.organizationId, dealId, vehicleId, exceptId]); return result.rows[0]?.exists === true; }
  async transition(context: RequestContext, item: TradeAppraisal, event: TradeEvent, acquisition?: { inventoryUnitId: string; stockNumber: string; listPriceCents?: number }) { if (acquisition) { await this.db.query(`INSERT INTO inventory_units (id, organization_id, location_id, vehicle_id, stock_number, idempotency_key, status, list_price_cents, acquired_at, created_by, updated_by) VALUES ($1,$2,$3,$4,$5,$6,'available',$7,now(),$8,$8)`, [acquisition.inventoryUnitId, item.organizationId, item.locationId, item.vehicleId, acquisition.stockNumber, `trade-acquisition:${item.id}`, acquisition.listPriceCents ?? null, context.actorId]); await this.db.query(`UPDATE lead_vehicle_interests vi SET status='traded',updated_by=$4,updated_at=now() FROM deals d WHERE d.organization_id=vi.organization_id AND d.id=$2 AND vi.organization_id=$1 AND vi.lead_id=d.lead_id AND vi.customer_id=d.customer_id AND vi.vehicle_id=$3 AND vi.role='trade' AND vi.status='active'`, [item.organizationId,item.dealId,item.vehicleId,context.actorId]); } const update = await this.db.query<{ id: string }>("UPDATE trade_appraisals SET status=$3, acquired_inventory_unit_id=$4, updated_by=$5, updated_at=now() WHERE organization_id=$1 AND id=$2 AND status=$6 RETURNING id", [item.organizationId, item.id, item.status, item.acquiredInventoryUnitId ?? null, context.actorId, event.fromStatus]); if (!update.rows[0]) throw new HandoffIntegrityError("Concurrent trade transition was rejected."); await insertTradeEvent(this.db, context, event); await audit(this.db, context, "trade_appraisal.status_changed", "trade_appraisal", item.id); return item; }
}

type DeliveryRow = { id: string; organization_id: string; location_id: string; deal_id: string; status: DealDelivery["status"]; starts_at: Date; ends_at: Date; timezone: string; notes: string | null; completed_at: Date | null; idempotency_key: string };
type DeliveryEventRow = { id: string; organization_id: string; delivery_id: string; from_status: DeliveryEvent["fromStatus"] | null; to_status: DeliveryEvent["toStatus"]; reason: string | null; occurred_at: Date; idempotency_key: string };
class DeliveryDb implements DeliverySession {
  constructor(private readonly db: SqlExecutor) {}
  async acquireLock(scope: OrganizationScope, key: string) { await lock(this.db, scope, key); }
  async findByIdempotency(scope: OrganizationScope, key: string) { const result = await this.db.query<DeliveryRow>("SELECT * FROM deal_deliveries WHERE organization_id=$1 AND idempotency_key=$2 LIMIT 1", [scope.organizationId, key]); return result.rows[0] ? delivery(result.rows[0]) : null; }
  async getDealContext(scope: OrganizationScope, dealId: string) { const result = await this.db.query<{ status: import("@/lib/application/deals").DealStatus; location_id: string }>("SELECT status, location_id FROM deals WHERE organization_id=$1 AND id=$2 FOR UPDATE", [scope.organizationId, dealId]); const row=result.rows[0]; return row ? { dealStatus: row.status, locationId: row.location_id } : null; }
  async create(context: RequestContext, item: DealDelivery, event: DeliveryEvent) { await this.db.query(`INSERT INTO deal_deliveries (id, organization_id, location_id, deal_id, status, starts_at, ends_at, timezone, notes, idempotency_key, created_by, updated_by) VALUES ($1,$2,$3,$4,'scheduled',$5,$6,$7,$8,$9,$10,$10)`, [item.id,item.organizationId,item.locationId,item.dealId,item.startsAt,item.endsAt,item.timezone,item.notes??null,item.idempotencyKey,context.actorId]); await insertDeliveryEvent(this.db,context,event); await audit(this.db,context,"delivery.scheduled","deal_delivery",item.id); return item; }
  async findTransition(scope: OrganizationScope,key:string){const result=await this.db.query<DeliveryRow & {event_id:string;from_status:DeliveryEventRow["from_status"];to_status:DeliveryEventRow["to_status"];reason:string|null;occurred_at:Date;event_key:string}>(`SELECT d.*,e.id AS event_id,e.from_status,e.to_status,e.reason,e.occurred_at,e.idempotency_key AS event_key FROM deal_delivery_status_events e JOIN deal_deliveries d ON d.organization_id=e.organization_id AND d.id=e.delivery_id WHERE e.organization_id=$1 AND e.idempotency_key=$2 LIMIT 1`,[scope.organizationId,key]);const row=result.rows[0];return row?{delivery:delivery(row),event:deliveryEvent({id:row.event_id,organization_id:row.organization_id,delivery_id:row.id,from_status:row.from_status,to_status:row.to_status,reason:row.reason,occurred_at:row.occurred_at,idempotency_key:row.event_key})}:null;}
  async getForUpdate(scope:OrganizationScope,id:string){const result=await this.db.query<DeliveryRow & {deal_status:import("@/lib/application/deals").DealStatus}>(`SELECT d.*,deal.status AS deal_status FROM deal_deliveries d JOIN deals deal ON deal.organization_id=d.organization_id AND deal.id=d.deal_id WHERE d.organization_id=$1 AND d.id=$2 FOR UPDATE OF d`,[scope.organizationId,id]);const row=result.rows[0];return row?{delivery:delivery(row),dealStatus:row.deal_status,locationId:row.location_id}:null;}
  async transition(context:RequestContext,item:DealDelivery,event:DeliveryEvent){const update=await this.db.query<{id:string}>("UPDATE deal_deliveries SET status=$3,completed_at=$4,updated_by=$5,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status=$6 RETURNING id",[item.organizationId,item.id,item.status,item.completedAt??null,context.actorId,event.fromStatus]);if(!update.rows[0])throw new HandoffIntegrityError("Concurrent delivery transition was rejected.");await insertDeliveryEvent(this.db,context,event);await audit(this.db,context,"delivery.status_changed","deal_delivery",item.id);return item;}
}
function trade(r:TradeRow):TradeAppraisal{return{id:r.id,organizationId:r.organization_id,...(r.location_id?{locationId:r.location_id}:{}),dealId:r.deal_id,vehicleId:r.vehicle_id,version:r.version,status:r.status,allowanceCents:r.allowance_cents,payoffCents:r.payoff_cents,equityCents:r.equity_cents,...(r.odometer_miles!==null?{odometerMiles:r.odometer_miles}:{}),...(r.condition_notes?{conditionNotes:r.condition_notes}:{}),...(r.lienholder?{lienholder:r.lienholder}:{}),...(r.expires_at?{expiresAt:r.expires_at.toISOString()}:{}),...(r.acquired_inventory_unit_id?{acquiredInventoryUnitId:r.acquired_inventory_unit_id}:{}),idempotencyKey:r.idempotency_key};}
function tradeEvent(r:TradeEventRow):TradeEvent{return{id:r.id,organizationId:r.organization_id,appraisalId:r.appraisal_id,...(r.from_status?{fromStatus:r.from_status}:{}),toStatus:r.to_status,...(r.reason?{reason:r.reason}:{}),occurredAt:r.occurred_at.toISOString(),idempotencyKey:r.idempotency_key};}
function delivery(r:DeliveryRow):DealDelivery{return{id:r.id,organizationId:r.organization_id,locationId:r.location_id,dealId:r.deal_id,status:r.status,startsAt:r.starts_at.toISOString(),endsAt:r.ends_at.toISOString(),timezone:r.timezone,...(r.notes?{notes:r.notes}:{}),...(r.completed_at?{completedAt:r.completed_at.toISOString()}:{}),idempotencyKey:r.idempotency_key};}
function deliveryEvent(r:DeliveryEventRow):DeliveryEvent{return{id:r.id,organizationId:r.organization_id,deliveryId:r.delivery_id,...(r.from_status?{fromStatus:r.from_status}:{}),toStatus:r.to_status,...(r.reason?{reason:r.reason}:{}),occurredAt:r.occurred_at.toISOString(),idempotencyKey:r.idempotency_key};}
async function lock(db:SqlExecutor,scope:OrganizationScope,key:string){await db.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`${scope.organizationId}:${key}`]);}
async function insertTradeEvent(db:SqlExecutor,c:RequestContext,e:TradeEvent){await db.query("INSERT INTO trade_appraisal_status_events (id,organization_id,appraisal_id,from_status,to_status,reason,occurred_at,idempotency_key,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)",[e.id,e.organizationId,e.appraisalId,e.fromStatus??null,e.toStatus,e.reason??null,e.occurredAt,e.idempotencyKey,c.actorId]);}
async function insertDeliveryEvent(db:SqlExecutor,c:RequestContext,e:DeliveryEvent){await db.query("INSERT INTO deal_delivery_status_events (id,organization_id,delivery_id,from_status,to_status,reason,occurred_at,idempotency_key,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)",[e.id,e.organizationId,e.deliveryId,e.fromStatus??null,e.toStatus,e.reason??null,e.occurredAt,e.idempotencyKey,c.actorId]);}
async function audit(db:SqlExecutor,c:RequestContext,action:string,type:string,id:string){await db.query("INSERT INTO audit_logs (id,organization_id,actor_id,action,entity_type,entity_id,source,correlation_id) VALUES ($1,$2,$3,$4,$5,$6,'application',$7)",[generateEntityId("aud"),c.organizationId,c.actorId,action,type,id,c.correlationId]);}
