import { NextResponse } from "next/server";
import { AuthorizationError } from "@/lib/platform/auth";
import { AuthenticationError,MembershipError,PostgresMembershipReader,authenticateOrganizationRequest } from "@/lib/server/auth";
import { EnvironmentConfigurationError } from "@/lib/server/config";
import { getDatabasePool } from "@/lib/server/database";
import { createInventoryMediaManager } from "@/lib/server/vehicles/media-manager-factory";
import { InventoryMediaIntegrityError,InventoryMediaStorageError,InventoryMediaValidationError } from "@/lib/server/vehicles";
export const runtime="nodejs";export const dynamic="force-dynamic";interface Context{params:Promise<{organizationId:string;inventoryUnitId:string}>}
export async function POST(request:Request,context:Context){try{const{organizationId,inventoryUnitId}=await context.params;const body=object(await request.json());const key=request.headers.get("idempotency-key")?.trim();if(!key)return problem(400,"invalid_request","Idempotency-Key is required.");const pool=getDatabasePool();const actor=await authenticateOrganizationRequest(request,organizationId,new PostgresMembershipReader(pool));const result=await createInventoryMediaManager().initiate({actor,organizationId,inventoryUnitId,filename:string(body.filename),contentType:string(body.contentType),byteSize:number(body.byteSize),altText:string(body.altText),idempotencyKey:key});return NextResponse.json(result,{status:201,headers:{"cache-control":"no-store"}});}catch(error){return failure(error);}}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new InventoryMediaValidationError(["Request data must be an object."]);return value as Record<string,unknown>;}function string(value:unknown){return typeof value==="string"?value:"";}function number(value:unknown){return typeof value==="number"?value:Number.NaN;}
function failure(error:unknown){if(error instanceof SyntaxError)return problem(400,"invalid_json","Request body must be valid JSON.");if(error instanceof AuthenticationError)return problem(401,"unauthorized",error.message);if(error instanceof MembershipError||error instanceof AuthorizationError)return problem(403,"forbidden","Inventory media access is not permitted.");if(error instanceof InventoryMediaValidationError)return NextResponse.json({error:"invalid_request",message:error.message,issues:error.issues},{status:400,headers:{"cache-control":"no-store"}});if(error instanceof InventoryMediaIntegrityError)return problem(409,"data_conflict",error.message);if(error instanceof EnvironmentConfigurationError)return problem(503,"storage_unavailable","Inventory media storage is not configured.");if(error instanceof InventoryMediaStorageError)return problem(502,"storage_error",error.message);return problem(500,"internal_error","The upload could not be initiated.");}function problem(status:number,error:string,message:string){return NextResponse.json({error,message},{status,headers:{"cache-control":"no-store"}});}
