import { randomUUID } from "node:crypto";

import type { TenantConfigurationProvider } from "@/lib/application/organizations";
import { generateEntityId } from "@/lib/core/identifiers";
import { resolveTenantConfiguration, type TenantVertical } from "@/lib/platform/tenant";
import { withTenantDatabaseContext, type DatabasePool } from "@/lib/server/database";

export class PostgresTenantConfigurationProvider implements TenantConfigurationProvider {
  constructor(private readonly pool: DatabasePool) {}

  async read(input: { actorId: string; organizationId: string }) {
    return withTenantDatabaseContext(this.pool, { userId: input.actorId, organizationId: input.organizationId }, async (client) => {
      const result = await client.query(`SELECT o.id,o.slug,o.name,o.vertical::text,c.product_name,c.custom_domain,c.brand,c.features,c.terminology,c.version FROM organizations o LEFT JOIN organization_configurations c ON c.organization_id=o.id WHERE o.id=$1 AND o.active=true`, [input.organizationId]) as { rows: Array<{id:string;slug:string;name:string;vertical:TenantVertical;product_name:string|null;custom_domain:string|null;brand:Record<string,unknown>|null;features:Record<string,boolean>|null;terminology:Record<string,string>|null;version:string|null}> };
      const row=result.rows[0];if(!row)throw new Error("Organization was not found.");
      const brand=row.brand??{};
      return { version: row.version??"none", configuration: resolveTenantConfiguration({id:row.id,slug:row.slug,vertical:row.vertical,...(row.custom_domain?{customDomain:row.custom_domain}:{}),brand:{organizationName:row.name,productName:row.product_name??"DealerFlow",...(typeof brand.logoUrl==="string"?{logoUrl:brand.logoUrl}:{}),...(typeof brand.logoDarkUrl==="string"?{logoDarkUrl:brand.logoDarkUrl}:{}),...(typeof brand.faviconUrl==="string"?{faviconUrl:brand.faviconUrl}:{}),...(typeof brand.supportEmail==="string"?{supportEmail:brand.supportEmail}:{}),...(typeof brand.supportPhone==="string"?{supportPhone:brand.supportPhone}:{}),...(typeof brand.colors==="object"&&brand.colors?{colors:brand.colors as Record<string,string>}:{})},features:row.features??{},terminology:row.terminology??{}}) };
    });
  }

  async save(input: Parameters<TenantConfigurationProvider["save"]>[0]) {
    return withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async(client)=>{
      const nextVersion=randomUUID();const configuration=input.configuration;const brand={...configuration.brand};
      const result=input.expectedVersion==="none"
        ? await client.query(`INSERT INTO organization_configurations(organization_id,product_name,custom_domain,brand,features,terminology,version) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7) ON CONFLICT(organization_id) DO NOTHING RETURNING organization_id`,[input.organizationId,configuration.brand.productName,configuration.customDomain??null,JSON.stringify(brand),JSON.stringify(configuration.features),JSON.stringify(configuration.terminology),nextVersion]) as {rows:Array<{organization_id:string}>}
        : await client.query(`UPDATE organization_configurations SET product_name=$3,brand=$4::jsonb,features=$5::jsonb,terminology=$6::jsonb,version=$7,updated_at=now() WHERE organization_id=$1 AND version=$2 RETURNING organization_id`,[input.organizationId,input.expectedVersion,configuration.brand.productName,JSON.stringify(brand),JSON.stringify(configuration.features),JSON.stringify(configuration.terminology),nextVersion]) as {rows:Array<{organization_id:string}>};
      if(!result.rows[0])return false;
      const snapshotId=generateEntityId("ocv");await client.query(`INSERT INTO organization_configuration_versions(id,organization_id,configuration,change_kind,created_by) VALUES($1,$2,$3::jsonb,'update',$4)`,[snapshotId,input.organizationId,JSON.stringify(configuration),input.actorId]);
      await client.query(`INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,source,correlation_id,new_values) VALUES($1,$2,$3,'organization.configuration.updated','organization_configuration',$2,'application',$4,$5::jsonb)`,[generateEntityId("aud"),input.organizationId,input.actorId,`configuration:${nextVersion}`,JSON.stringify({version:nextVersion,productName:configuration.brand.productName,features:configuration.features,terminology:configuration.terminology})]);return true;
    });
  }
  async history(input:{actorId:string;organizationId:string}){return withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async(client)=>{const result=await client.query(`SELECT id,change_kind,configuration->'brand'->>'productName' product_name,created_at FROM organization_configuration_versions WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 20`,[input.organizationId]) as {rows:Array<{id:string;change_kind:"update"|"rollback";product_name:string;created_at:Date}>};return result.rows.map((row)=>({id:row.id,changeKind:row.change_kind,productName:row.product_name,createdAt:row.created_at.toISOString()}));});}
  async restore(input:{actorId:string;organizationId:string;expectedVersion:string;versionId:string}){return withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async(client)=>{const snapshot=await client.query(`SELECT configuration FROM organization_configuration_versions WHERE organization_id=$1 AND id=$2`,[input.organizationId,input.versionId]) as {rows:Array<{configuration:import("@/lib/platform/tenant").TenantConfiguration}>};const configuration=snapshot.rows[0]?.configuration;if(!configuration)return false;const nextVersion=randomUUID();const result=await client.query(`UPDATE organization_configurations SET product_name=$4,custom_domain=$5,brand=$6::jsonb,features=$7::jsonb,terminology=$8::jsonb,version=$3,updated_at=now() WHERE organization_id=$1 AND version=$2 RETURNING organization_id`,[input.organizationId,input.expectedVersion,nextVersion,configuration.brand.productName,configuration.customDomain??null,JSON.stringify(configuration.brand),JSON.stringify(configuration.features),JSON.stringify(configuration.terminology)]) as {rows:Array<{organization_id:string}>};if(!result.rows[0])return false;const restoredId=generateEntityId("ocv");await client.query(`INSERT INTO organization_configuration_versions(id,organization_id,configuration,change_kind,restored_from_id,created_by) VALUES($1,$2,$3::jsonb,'rollback',$4,$5)`,[restoredId,input.organizationId,JSON.stringify(configuration),input.versionId,input.actorId]);await client.query(`INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,source,correlation_id,new_values) VALUES($1,$2,$3,'organization.configuration.restored','organization_configuration',$2,'application',$4,$5::jsonb)`,[generateEntityId("aud"),input.organizationId,input.actorId,`configuration:${nextVersion}`,JSON.stringify({version:nextVersion,restoredFromId:input.versionId})]);return true;});}
}
