import{randomUUID}from"node:crypto";import type{DatabasePool}from"@/lib/server/database";import{withTenantDatabaseContext}from"@/lib/server/database";import type{LocationAdministrationProvider,LocationMutationResult,ManagedLocation}from"@/lib/application/organizations";import{generateEntityId}from"@/lib/core/identifiers";
export class PostgresLocationAdministration implements LocationAdministrationProvider{constructor(private readonly pool:DatabasePool){}create(input:{actorId:string;organizationId:string;location:ManagedLocation}){return withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async client=>{const authority=await client.query("SELECT EXISTS(SELECT 1 FROM organization_memberships WHERE organization_id=$1 AND user_id=$2 AND status='active' AND all_locations=true) allowed",[input.organizationId,input.actorId])as{rows:Array<{allowed:boolean}>};if(!authority.rows[0]?.allowed)return"forbidden"as const;await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`${input.organizationId}:location:${input.location.slug}`]);const result=await client.query("INSERT INTO locations(id,organization_id,slug,name,timezone,active) VALUES($1,$2,$3,$4,$5,true) ON CONFLICT(organization_id,slug) DO NOTHING RETURNING id",[input.location.id,input.organizationId,input.location.slug,input.location.name,input.location.timezone])as{rows:Array<{id:string}>};if(!result.rows[0])return"conflict"as const;await audit(client,input.actorId,input.organizationId,"organization.location.created",input.location.id,{slug:input.location.slug,name:input.location.name,timezone:input.location.timezone,active:true});return"created"as const;});}update(input:{actorId:string;organizationId:string;locationId:string;expectedUpdatedAt:string;name:string;timezone:string;active:boolean}){return withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async client=>{const current=await client.query("SELECT location.name,location.timezone,location.active,location.updated_at,membership.all_locations FROM locations location JOIN organization_memberships membership ON membership.organization_id=location.organization_id AND membership.user_id=$3 AND membership.status='active' AND (membership.all_locations OR EXISTS(SELECT 1 FROM membership_locations grant_record WHERE grant_record.organization_id=membership.organization_id AND grant_record.membership_id=membership.id AND grant_record.location_id=location.id)) WHERE location.organization_id=$1 AND location.id=$2 FOR UPDATE OF location",[input.organizationId,input.locationId,input.actorId])as{rows:Array<{name:string;timezone:string;active:boolean;updated_at:Date;all_locations:boolean}>};const row=current.rows[0];if(!row)return"not_found";if(row.updated_at.toISOString()!==input.expectedUpdatedAt)return"conflict";if(row.active!==input.active&&!row.all_locations)return"forbidden";if(row.active&&!input.active){const active=await client.query("SELECT count(*)::int count FROM locations WHERE organization_id=$1 AND active=true",[input.organizationId])as{rows:Array<{count:number}>};if((active.rows[0]?.count??0)<=1)return"last_active";const work=await client.query(`SELECT EXISTS(
          SELECT 1 FROM leads WHERE organization_id=$1 AND location_id=$2 AND status IN('open','working','qualified') UNION ALL
          SELECT 1 FROM tasks WHERE organization_id=$1 AND location_id=$2 AND status IN('open','in-progress') UNION ALL
          SELECT 1 FROM appointments WHERE organization_id=$1 AND location_id=$2 AND status IN('scheduled','confirmed','arrived') UNION ALL
          SELECT 1 FROM showroom_visits WHERE organization_id=$1 AND location_id=$2 AND status IN('checked-in','active') UNION ALL
          SELECT 1 FROM deals WHERE organization_id=$1 AND location_id=$2 AND status NOT IN('delivered','cancelled') UNION ALL
          SELECT 1 FROM inventory_units WHERE organization_id=$1 AND location_id=$2 AND status IN('available','hold')) busy`,[input.organizationId,input.locationId])as{rows:Array<{busy:boolean}>};if(work.rows[0]?.busy)return"in_use";}
      const updated=await client.query("UPDATE locations SET name=$3,timezone=$4,active=$5,updated_at=now() WHERE organization_id=$1 AND id=$2 AND updated_at=$6 RETURNING updated_at",[input.organizationId,input.locationId,input.name,input.timezone,input.active,input.expectedUpdatedAt])as{rows:Array<{updated_at:Date}>};if(!updated.rows[0])return"conflict";await audit(client,input.actorId,input.organizationId,"organization.location.updated",input.locationId,{name:input.name,timezone:input.timezone,active:input.active});return"updated"as LocationMutationResult;});}}
async function audit(client:{query(query:string,values?:readonly unknown[]):Promise<unknown>},actorId:string,organizationId:string,action:string,locationId:string,values:unknown){await client.query("INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,source,correlation_id,new_values) VALUES($1,$2,$3,$4,'location',$5,'application',$6,$7::jsonb)",[generateEntityId("aud"),organizationId,actorId,action,locationId,`location:${randomUUID()}`,JSON.stringify(values)]);}
