import { describe, expect, it, vi } from "vitest";
import type { DatabaseClient, DatabasePool } from "@/lib/server/database";
import { RoleWorkspaceReader } from "./role-workspace-reader";
import { resolveWorkspaceProfiles } from "./role-workspace";

function pool(row:Record<string,unknown>){const query=vi.fn<DatabaseClient["query"]>().mockResolvedValueOnce({}).mockResolvedValueOnce({}).mockResolvedValueOnce({rows:[row]}).mockResolvedValueOnce({});const client:DatabaseClient={query,release:vi.fn()};return{pool:{connect:vi.fn().mockResolvedValue(client)}as DatabasePool,query};}
const empty={active_leads:"0",overdue_tasks:"0",appointments_today:"0",pending_deals:"0",available_inventory:"0",inventory_missing_photos:"0",lead_queue:[],task_queue:[],appointment_queue:[],deal_queue:[],inventory_queue:[]};

describe("RoleWorkspaceReader",()=>{
  it("passes tenant, location, self scope, capabilities, and actor to one aggregate query",async()=>{const fixture=pool({...empty,active_leads:"2"});const membership={organizationId:"org_dealer01",locationIds:["loc_allowed01"],roleKeys:["salesperson"],capabilities:["lead.read","task.read","appointment.read"]}as const;const profile=resolveWorkspaceProfiles(membership).active!;const model=await new RoleWorkspaceReader(fixture.pool).read({userId:"usr_sales001",organizationId:"org_dealer01",membership,profile});expect(model.metrics[0]).toMatchObject({label:"Active Leads",value:2});expect(fixture.query).toHaveBeenCalledTimes(4);expect(fixture.query.mock.calls[2]?.[1]).toEqual(["org_dealer01",false,["loc_allowed01"],true,true,"usr_sales001",true,true,false,false,false]);expect(fixture.query.mock.calls[2]?.[0]).toContain("assigned_user_id=$6");});
  it("keeps manager queues within explicitly authorized locations",async()=>{const fixture=pool({...empty,lead_queue:[{id:"led_unassigned01",label:"Jordan Lee",detail:"Lead · new · Unassigned"}]});const membership={organizationId:"org_dealer01",locationIds:["loc_rooftop01"],roleKeys:["sales-manager"],capabilities:["lead.read","lead.assign"]}as const;const profile=resolveWorkspaceProfiles(membership).active!;const model=await new RoleWorkspaceReader(fixture.pool).read({userId:"usr_manager01",organizationId:"org_dealer01",membership,profile});expect(model.priorities[0]?.href).toBe("/organizations/org_dealer01/leads");expect(fixture.query.mock.calls[2]?.[1]?.[2]).toEqual(["loc_rooftop01"]);expect(fixture.query.mock.calls[2]?.[1]?.[10]).toBe(true);});
  it("does not request finance or inventory data without those capabilities",async()=>{const fixture=pool(empty);const membership={organizationId:"org_dealer01",locationIds:"all",roleKeys:["bdc"],capabilities:["lead.read","appointment.read"]}as const;const profile=resolveWorkspaceProfiles(membership).active!;await new RoleWorkspaceReader(fixture.pool).read({userId:"usr_bdc001",organizationId:"org_dealer01",membership,profile});expect(fixture.query.mock.calls[2]?.[1]?.slice(8,10)).toEqual([false,false]);expect(fixture.query.mock.calls[2]?.[0]).toContain("appointment.starts_at AT TIME ZONE COALESCE(location.timezone,'UTC')");});
});
