import type { Capability, OrganizationMembership } from "@/lib/platform/auth";
import { withTenantDatabaseContext, type DatabasePool } from "@/lib/server/database";
import type { WorkspaceProfile } from "./role-workspace";

export interface WorkspaceQueueItem { id:string; label:string; detail:string; href:string; tone:"default"|"warning"|"danger" }
export interface WorkspaceMetric { label:string; value:number; definition:string; href:string }
export interface RoleWorkspaceModel { priorities:WorkspaceQueueItem[]; today:WorkspaceQueueItem[]; exceptions:WorkspaceQueueItem[]; metrics:WorkspaceMetric[]; generatedAt:string }

export class RoleWorkspaceReader {
  constructor(private readonly pool:DatabasePool){}
  read(input:{userId:string;organizationId:string;membership:OrganizationMembership;profile:WorkspaceProfile}):Promise<RoleWorkspaceModel>{
    return withTenantDatabaseContext(this.pool,{userId:input.userId,organizationId:input.organizationId},async(client)=>{
      const all=input.membership.locationIds==="all",locations=all?[]:input.membership.locationIds,capabilities=new Set<Capability>(input.membership.capabilities),self=input.profile.audience==="individual"||input.profile.audience==="service";
      const rows=await client.query(`SELECT
        CASE WHEN $5 THEN (SELECT count(*) FROM leads WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status IN ('open','working','qualified') AND (NOT $4 OR assigned_user_id=$6)) ELSE 0 END::text active_leads,
        CASE WHEN $7 THEN (SELECT count(*) FROM tasks WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status IN ('open','in-progress') AND due_at<now() AND (NOT $4 OR assigned_user_id=$6)) ELSE 0 END::text overdue_tasks,
        CASE WHEN $8 THEN (SELECT count(*) FROM appointments a LEFT JOIN locations l ON l.organization_id=a.organization_id AND l.id=a.location_id WHERE a.organization_id=$1 AND ($2 OR a.location_id=ANY($3::text[])) AND a.status IN ('scheduled','confirmed','arrived') AND (a.starts_at AT TIME ZONE COALESCE(l.timezone,'UTC'))::date=(now() AT TIME ZONE COALESCE(l.timezone,'UTC'))::date AND (NOT $4 OR a.assigned_user_id=$6)) ELSE 0 END::text appointments_today,
        CASE WHEN $9 THEN (SELECT count(*) FROM deals WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status='pending-approval' AND (NOT $4 OR owner_user_id=$6)) ELSE 0 END::text pending_deals,
        CASE WHEN $10 THEN (SELECT count(*) FROM inventory_units WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status='available') ELSE 0 END::text available_inventory,
        CASE WHEN $10 THEN (SELECT count(*) FROM inventory_units unit WHERE unit.organization_id=$1 AND ($2 OR unit.location_id=ANY($3::text[])) AND unit.status='available' AND NOT EXISTS(SELECT 1 FROM inventory_unit_media media WHERE media.organization_id=unit.organization_id AND media.inventory_unit_id=unit.id AND media.status='active' AND media.source_type='actual')) ELSE 0 END::text inventory_missing_photos,
        CASE WHEN $5 THEN COALESCE((SELECT jsonb_agg(item) FROM (SELECT lead.id,customer.display_name label,concat('Lead · ',lead.stage,' · ',coalesce(owner.display_name,'Unassigned')) detail,lead.updated_at FROM leads lead JOIN customers customer ON customer.organization_id=lead.organization_id AND customer.id=lead.customer_id LEFT JOIN users owner ON owner.id=lead.assigned_user_id WHERE lead.organization_id=$1 AND ($2 OR lead.location_id=ANY($3::text[])) AND lead.status IN ('open','working','qualified') AND (CASE WHEN $11 THEN lead.assigned_user_id IS NULL WHEN $4 THEN lead.assigned_user_id=$6 ELSE true END) ORDER BY CASE WHEN lead.assigned_user_id IS NULL THEN 0 ELSE 1 END,lead.updated_at LIMIT 6)item),'[]'::jsonb) ELSE '[]'::jsonb END lead_queue,
        CASE WHEN $7 THEN COALESCE((SELECT jsonb_agg(item) FROM (SELECT task.id,task.title label,concat(customer.display_name,' · Due ',coalesce(to_char(task.due_at,'Mon DD HH24:MI'),'not scheduled')) detail,task.due_at FROM tasks task JOIN customers customer ON customer.organization_id=task.organization_id AND customer.id=task.customer_id WHERE task.organization_id=$1 AND ($2 OR task.location_id=ANY($3::text[])) AND task.status IN ('open','in-progress') AND (NOT $4 OR task.assigned_user_id=$6) ORDER BY task.due_at NULLS LAST LIMIT 6)item),'[]'::jsonb) ELSE '[]'::jsonb END task_queue,
        CASE WHEN $8 THEN COALESCE((SELECT jsonb_agg(item) FROM (SELECT appointment.id,customer.display_name label,concat(appointment.type,' · ',to_char(appointment.starts_at,'Mon DD HH24:MI'),' · ',appointment.status) detail,appointment.starts_at FROM appointments appointment JOIN customers customer ON customer.organization_id=appointment.organization_id AND customer.id=appointment.customer_id WHERE appointment.organization_id=$1 AND ($2 OR appointment.location_id=ANY($3::text[])) AND appointment.status IN ('scheduled','confirmed','arrived') AND appointment.starts_at>=date_trunc('day',now()) AND appointment.starts_at<date_trunc('day',now())+interval '1 day' AND (NOT $4 OR appointment.assigned_user_id=$6) ORDER BY appointment.starts_at LIMIT 6)item),'[]'::jsonb) ELSE '[]'::jsonb END appointment_queue,
        CASE WHEN $9 THEN COALESCE((SELECT jsonb_agg(item) FROM (SELECT deal.id,customer.display_name label,concat(deal.deal_number,' · ',deal.status) detail,deal.updated_at FROM deals deal JOIN customers customer ON customer.organization_id=deal.organization_id AND customer.id=deal.customer_id WHERE deal.organization_id=$1 AND ($2 OR deal.location_id=ANY($3::text[])) AND deal.status IN ('pending-approval','approved','contracted') AND (NOT $4 OR deal.owner_user_id=$6) ORDER BY CASE deal.status WHEN 'pending-approval' THEN 0 ELSE 1 END,deal.updated_at LIMIT 6)item),'[]'::jsonb) ELSE '[]'::jsonb END deal_queue,
        CASE WHEN $10 THEN COALESCE((SELECT jsonb_agg(item) FROM (SELECT unit.id,concat(vehicle.year,' ',vehicle.make,' ',vehicle.model) label,concat('Stock ',unit.stock_number,' · Missing actual photos') detail,unit.updated_at FROM inventory_units unit JOIN vehicles vehicle ON vehicle.organization_id=unit.organization_id AND vehicle.id=unit.vehicle_id WHERE unit.organization_id=$1 AND ($2 OR unit.location_id=ANY($3::text[])) AND unit.status='available' AND NOT EXISTS(SELECT 1 FROM inventory_unit_media media WHERE media.organization_id=unit.organization_id AND media.inventory_unit_id=unit.id AND media.status='active' AND media.source_type='actual') ORDER BY unit.updated_at LIMIT 6)item),'[]'::jsonb) ELSE '[]'::jsonb END inventory_queue`,[input.organizationId,all,locations,self,capabilities.has("lead.read"),input.userId,capabilities.has("task.read"),capabilities.has("appointment.read"),capabilities.has("deal.read"),capabilities.has("inventory.read"),input.profile.key==="team-management"||input.profile.key==="bdc"]) as {rows:WorkspaceRow[]};
      return model(rows.rows[0]!,input.organizationId,input.profile,capabilities);
    });
  }
}

interface RawItem{id:string;label:string;detail:string}
interface WorkspaceRow{active_leads:string;overdue_tasks:string;appointments_today:string;pending_deals:string;available_inventory:string;inventory_missing_photos:string;lead_queue:RawItem[];task_queue:RawItem[];appointment_queue:RawItem[];deal_queue:RawItem[];inventory_queue:RawItem[]}
function model(row:WorkspaceRow,organizationId:string,profile:WorkspaceProfile,capabilities:Set<Capability>):RoleWorkspaceModel{const base=`/organizations/${organizationId}`;const map=(items:RawItem[],kind:"lead"|"task"|"appointment"|"deal"|"inventory",tone:WorkspaceQueueItem["tone"]="default")=>items.map(item=>({id:`${kind}:${item.id}`,label:item.label,detail:item.detail,href:kind==="inventory"?`${base}/inventory/${item.id}`:kind==="deal"?`${base}/deals`:kind==="lead"?`${base}/leads`:`${base}/customers`,tone}));const priorities=profile.audience==="inventory"?map(row.inventory_queue,"inventory","warning"):profile.audience==="finance"?map(row.deal_queue,"deal","warning"):[...map(row.task_queue,"task","danger"),...map(row.lead_queue,"lead","warning")].slice(0,8);const today=map(row.appointment_queue,"appointment");const exceptions=profile.audience==="inventory"?[]:profile.audience==="executive"||profile.audience==="team"?map(row.deal_queue,"deal","warning"):[];const metrics:WorkspaceMetric[]=[];if(capabilities.has("lead.read"))metrics.push({label:"Active Leads",value:Number(row.active_leads),definition:profile.audience==="individual"?"Active Leads assigned to you.":"Active Leads in authorized locations.",href:`${base}/leads`});if(capabilities.has("task.read"))metrics.push({label:"Overdue Follow-Up",value:Number(row.overdue_tasks),definition:profile.audience==="individual"?"Your overdue open tasks.":"Overdue open tasks in scope.",href:`${base}/leads`});if(capabilities.has("appointment.read"))metrics.push({label:"Appointments Today",value:Number(row.appointments_today),definition:"Scheduled, confirmed, or arrived today.",href:`${base}/leads`});if(capabilities.has("deal.read"))metrics.push({label:"Deals Awaiting Approval",value:Number(row.pending_deals),definition:"Authoritative pending-approval Deals.",href:`${base}/deals`});if(capabilities.has("inventory.read"))metrics.push({label:profile.audience==="inventory"?"Inventory Missing Photos":"Available Inventory",value:profile.audience==="inventory"?Number(row.inventory_missing_photos):Number(row.available_inventory),definition:profile.audience==="inventory"?"Available units without actual inventory photos.":"Available units in authorized locations.",href:`${base}/inventory`});return{priorities,today,exceptions,metrics,generatedAt:new Date().toISOString()};}
