"use server";

import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { PackPolicyService } from "@/lib/application/deals";
import { InventoryCostService, inventoryCostSourceTypes } from "@/lib/application/inventory";
import { PostgresPackPolicyProvider } from "@/lib/server/deals";
import { PostgresInventoryCostProvider } from "@/lib/server/vehicles";
import { loadDirectoryContext } from "../../../_lib/load-directory-context";

const path=(organizationId:string)=>`/organizations/${organizationId}/settings/configuration/profitability`;
export async function recordInventoryCostAction(organizationId:string,formData:FormData){try{const context=await loadDirectoryContext(organizationId,"inventory.cost.manage");const sourceType=String(formData.get("sourceType")??"");if(!inventoryCostSourceTypes.includes(sourceType as (typeof inventoryCostSourceTypes)[number]))throw new Error("Choose a valid cost source.");await new InventoryCostService(new PostgresInventoryCostProvider(context.pool,{userId:context.session.user.id,organizationId})).record({actor:context.actor,organizationId,locationId:required(formData,"locationId"),inventoryUnitId:required(formData,"inventoryUnitId"),correlationId:`inventory-cost:${randomUUID()}`,costCents:money(formData,"cost"),sourceType:sourceType as (typeof inventoryCostSourceTypes)[number],sourceLabel:required(formData,"sourceLabel"),...(optional(formData,"sourceReference")?{sourceReference:optional(formData,"sourceReference")}:{}) ,effectiveAt:new Date(required(formData,"effectiveAt")).toISOString()});revalidatePath(path(organizationId));redirect(`${path(organizationId)}?notice=${encodeURIComponent("Authoritative inventory cost revision recorded.")}`)}catch(error){if(redirecting(error))throw error;redirect(`${path(organizationId)}?error=${encodeURIComponent(error instanceof Error?error.message:"Cost could not be recorded.")}`)}}
export async function savePackPolicyAction(organizationId:string,locationId:string|null,formData:FormData){try{const context=await loadDirectoryContext(organizationId,"quote.pack.configure");const enabled=formData.get("enabled")==="on";const expected=optional(formData,"expectedVersion");await new PackPolicyService(new PostgresPackPolicyProvider(context.pool,{userId:context.session.user.id,organizationId})).save({actor:context.actor,organizationId,...(locationId?{locationId}:{}),correlationId:`pack-policy:${randomUUID()}`,enabled,...(enabled?{packAmountCents:money(formData,"packAmount")}:{}) ,...(expected?{expectedVersion:Number(expected)}:{})});revalidatePath(path(organizationId));redirect(`${path(organizationId)}?notice=${encodeURIComponent("Pack policy saved.")}`)}catch(error){if(redirecting(error))throw error;redirect(`${path(organizationId)}?error=${encodeURIComponent(error instanceof Error?error.message:"Pack policy could not be saved.")}`)}}
function required(data:FormData,key:string){const value=String(data.get(key)??"").trim();if(!value)throw new Error(`${key} is required.`);return value}function optional(data:FormData,key:string){return String(data.get(key)??"").trim()||undefined}function money(data:FormData,key:string){const value=required(data,key).replace(/[$,\s]/g,"");if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error(`${key} must be a nonnegative amount.`);return Math.round(Number(value)*100)}function redirecting(error:unknown){return error instanceof Error&&error.message==="NEXT_REDIRECT"}
