import { describe, expect, it } from "vitest";
import type { AuthorizationActor } from "@/lib/platform/auth";
import type { RequestContext } from "@/lib/platform/data";
import { DeliveryService, HandoffIntegrityError, HandoffTransitionError, HandoffValidationError, TradeAppraisalService,
  type DealDelivery, type DeliveryEvent, type DeliveryProvider, type DeliverySession, type ScheduleDeliveryRequest,
  type TradeAppraisal, type TradeEvent, type TradeProvider, type TradeSession, type TransitionDeliveryRequest, type TransitionTradeRequest } from "./manage-handoff";
const actor: AuthorizationActor = { userId: "usr_finance", memberships: [{ organizationId: "org_dealerflow", locationIds: ["loc_main"], capabilities: ["deal.read", "deal.update", "inventory.read"] }] };
class Trades implements TradeProvider, TradeSession { items: TradeAppraisal[]=[]; events:TradeEvent[]=[]; dealStatus="working" as import("./manage-deal").DealStatus; async transaction<R>(op:(s:TradeSession)=>Promise<R>){return op(this);} async acquireLock(){} async findByIdempotency(s:{organizationId:string},k:string){return this.items.find(i=>i.organizationId===s.organizationId&&i.idempotencyKey===k)??null;} async getContext(){return{dealStatus:this.dealStatus,locationId:"loc_main"};} async nextVersion(_s:{organizationId:string},dealId:string,vehicleId:string){return this.items.filter(i=>i.dealId===dealId&&i.vehicleId===vehicleId).length+1;} async create(_c:RequestContext,i:TradeAppraisal,e:TradeEvent){this.items.push(i);this.events.push(e);return i;} async findTransition(s:{organizationId:string},k:string){const e=this.events.find(i=>i.organizationId===s.organizationId&&i.idempotencyKey===k);const appraisal=e?this.items.find(i=>i.id===e.appraisalId):undefined;return e&&appraisal?{appraisal,event:e}:null;} async getForUpdate(_s:{organizationId:string},id:string){const appraisal=this.items.find(i=>i.id===id);return appraisal?{appraisal,dealStatus:this.dealStatus,locationId:"loc_main"}:null;} async hasAccepted(_s:{organizationId:string},dealId:string,vehicleId:string,except:string){return this.items.some(i=>i.dealId===dealId&&i.vehicleId===vehicleId&&i.id!==except&&["accepted","acquired"].includes(i.status));} async transition(_c:RequestContext,i:TradeAppraisal,e:TradeEvent){this.items[this.items.findIndex(x=>x.id===i.id)]=i;this.events.push(e);return i;} }
class Deliveries implements DeliveryProvider, DeliverySession { items:DealDelivery[]=[];events:DeliveryEvent[]=[];dealStatus="contracted" as import("./manage-deal").DealStatus;async transaction<R>(op:(s:DeliverySession)=>Promise<R>){return op(this);}async acquireLock(){}async findByIdempotency(s:{organizationId:string},k:string){return this.items.find(i=>i.organizationId===s.organizationId&&i.idempotencyKey===k)??null;}async getDealContext(){return{dealStatus:this.dealStatus,locationId:"loc_main"};}async create(_c:RequestContext,i:DealDelivery,e:DeliveryEvent){this.items.push(i);this.events.push(e);return i;}async findTransition(s:{organizationId:string},k:string){const e=this.events.find(i=>i.organizationId===s.organizationId&&i.idempotencyKey===k);const delivery=e?this.items.find(i=>i.id===e.deliveryId):undefined;return e&&delivery?{delivery,event:e}:null;}async getForUpdate(_s:{organizationId:string},id:string){const delivery=this.items.find(i=>i.id===id);return delivery?{delivery,dealStatus:this.dealStatus,locationId:"loc_main"}:null;}async transition(_c:RequestContext,i:DealDelivery,e:DeliveryEvent){this.items[this.items.findIndex(x=>x.id===i.id)]=i;this.events.push(e);return i;}}
const tradeRequest=()=>({actor,organizationId:"org_dealerflow",correlationId:"req_trade",idempotencyKey:"trade:v1",dealId:"dea_12345678",vehicleId:"veh_tradecar",allowanceCents:1800000,payoffCents:1250000,odometerMiles:42000,expiresAt:"2026-09-01T12:00:00.000Z"});
const tradeTransition=(id:string,toStatus:TransitionTradeRequest["toStatus"],overrides:Partial<TransitionTradeRequest>={}):TransitionTradeRequest=>({actor,organizationId:"org_dealerflow",correlationId:"req_trade_status",idempotencyKey:`trade:${toStatus}`,appraisalId:id,toStatus,...overrides});
const deliveryRequest=():ScheduleDeliveryRequest=>({actor,organizationId:"org_dealerflow",correlationId:"req_delivery",idempotencyKey:"delivery:deal-1",dealId:"dea_12345678",startsAt:"2026-08-30T14:00:00.000Z",endsAt:"2026-08-30T15:00:00.000Z",timezone:"America/New_York"});
const deliveryTransition=(id:string,toStatus:TransitionDeliveryRequest["toStatus"],overrides:Partial<TransitionDeliveryRequest>={}):TransitionDeliveryRequest=>({actor,organizationId:"org_dealerflow",correlationId:"req_delivery_status",idempotencyKey:`delivery:${toStatus}`,deliveryId:id,toStatus,...overrides});
describe("TradeAppraisalService",()=>{it("creates immutable versions with calculated equity",async()=>{const p=new Trades();const s=new TradeAppraisalService(p,()=>new Date("2026-08-23T12:00:00.000Z"));const first=await s.create(tradeRequest());const retry=await s.create(tradeRequest());expect(first.appraisal).toMatchObject({version:1,equityCents:550000,status:"draft"});expect(retry.created).toBe(false);});it("controls presentation, acceptance, and contracted acquisition",async()=>{const p=new Trades();const s=new TradeAppraisalService(p,()=>new Date("2026-08-23T12:00:00.000Z"));const {appraisal}=await s.create(tradeRequest());await s.transition(tradeTransition(appraisal.id,"presented"));await s.transition(tradeTransition(appraisal.id,"accepted"));await expect(s.transition(tradeTransition(appraisal.id,"acquired"))).rejects.toBeInstanceOf(HandoffIntegrityError);p.dealStatus="contracted";const acquired=await s.transition(tradeTransition(appraisal.id,"acquired",{idempotencyKey:"trade:acquire:2",acquisition:{stockNumber:"U42000",listPriceCents:2200000}}));expect(acquired.appraisal.status).toBe("acquired");expect(acquired.appraisal.acquiredInventoryUnitId).toMatch(/^inv_/);});it("rejects unsafe appraisal amounts and skipped states",async()=>{const p=new Trades();const s=new TradeAppraisalService(p);await expect(s.create({...tradeRequest(),allowanceCents:-1})).rejects.toBeInstanceOf(HandoffValidationError);const {appraisal}=await s.create({...tradeRequest(),idempotencyKey:"valid"});await expect(s.transition(tradeTransition(appraisal.id,"accepted"))).rejects.toBeInstanceOf(HandoffTransitionError);});});
describe("DeliveryService",()=>{it("schedules idempotently and completes a contracted handoff",async()=>{const p=new Deliveries();const s=new DeliveryService(p,()=>new Date("2026-08-30T15:00:00.000Z"));const first=await s.schedule(deliveryRequest());const retry=await s.schedule(deliveryRequest());expect(retry.created).toBe(false);await s.transition(deliveryTransition(first.delivery.id,"ready"));const completed=await s.transition(deliveryTransition(first.delivery.id,"completed"));expect(completed.delivery).toMatchObject({status:"completed",completedAt:"2026-08-30T15:00:00.000Z"});});it("requires valid scheduling state and cancellation reason",async()=>{const p=new Deliveries();p.dealStatus="working";const s=new DeliveryService(p);await expect(s.schedule(deliveryRequest())).rejects.toBeInstanceOf(HandoffIntegrityError);p.dealStatus="contracted";const {delivery}=await s.schedule(deliveryRequest());await expect(s.transition(deliveryTransition(delivery.id,"cancelled"))).rejects.toBeInstanceOf(HandoffValidationError);});});
