import { generateEntityId } from "@/lib/core/identifiers";
import { assertAuthorized, type AuthorizationActor } from "@/lib/platform/auth";
import type { OrganizationScope, RequestContext } from "@/lib/platform/data";

export type DealDocumentStatus = "pending" | "generated" | "provided" | "complete" | "waived" | "unavailable";
export type DealDocumentSource = "internal-generated" | "uploaded" | "external-reference" | "canonical-quote";
export interface DealDocumentRequirement extends OrganizationScope { id:string;locationId:string;dealId:string;quoteId:string;quoteVersion:number;documentType:string;documentVersion:number;sourceType:DealDocumentSource;status:DealDocumentStatus;required:boolean;waiverAllowed:boolean;templateId?:string;templateVersion?:number;externalReference?:string;completedBy?:string;completedAt?:string;waivedBy?:string;waivedAt?:string;waiverReason?:string;createdAt:string;updatedAt:string; }
export interface DealDocumentEvent extends OrganizationScope { id:string;requirementId:string;fromStatus?:DealDocumentStatus;toStatus:DealDocumentStatus;reason?:string;occurredAt:string;idempotencyKey:string; }
export interface CreateDealDocumentRequest extends OrganizationScope { actor:AuthorizationActor;correlationId:string;idempotencyKey:string;dealId:string;documentType:string;sourceType:Exclude<DealDocumentSource,"canonical-quote">;required:boolean;waiverAllowed:boolean;templateId?:string;templateVersion?:number;externalReference?:string; }
export interface TransitionDealDocumentRequest extends OrganizationScope { actor:AuthorizationActor;correlationId:string;idempotencyKey:string;dealId:string;requirementId:string;toStatus:Exclude<DealDocumentStatus,"pending">;reason?:string; }
export interface DealDocumentSession { acquireLock(scope:OrganizationScope,key:string):Promise<void>;findByIdempotency(scope:OrganizationScope,key:string):Promise<DealDocumentRequirement|null>;getContractContext(scope:OrganizationScope,dealId:string):Promise<{locationId:string;quoteId:string;quoteVersion:number}|null>;nextVersion(scope:OrganizationScope,dealId:string,documentType:string):Promise<number>;create(context:RequestContext,item:DealDocumentRequirement,event:DealDocumentEvent):Promise<DealDocumentRequirement>;findTransition(scope:OrganizationScope,key:string):Promise<{requirement:DealDocumentRequirement;event:DealDocumentEvent}|null>;getForUpdate(scope:OrganizationScope,dealId:string,id:string):Promise<DealDocumentRequirement|null>;transition(context:RequestContext,item:DealDocumentRequirement,event:DealDocumentEvent):Promise<DealDocumentRequirement>; }
export interface DealDocumentProvider { transaction<Result>(operation:(session:DealDocumentSession)=>Promise<Result>):Promise<Result>;list(scope:OrganizationScope,dealId:string):Promise<readonly DealDocumentRequirement[]>; }
export class DealDocumentValidationError extends Error { constructor(readonly issues:readonly string[]){super("Document requirement data is invalid.");this.name="DealDocumentValidationError";} }
export class DealDocumentIntegrityError extends Error { constructor(message:string){super(message);this.name="DealDocumentIntegrityError";} }

export class DealDocumentService {
  constructor(private readonly provider:DealDocumentProvider,private readonly now:()=>Date=()=>new Date()){}
  async list(input:{actor:AuthorizationActor;organizationId:string;dealId:string}){assertAuthorized(input.actor,{capability:"document.read",organizationId:input.organizationId});const records=await this.provider.list(input,input.dealId);for(const record of records)assertAuthorized(input.actor,{capability:"document.read",organizationId:input.organizationId,locationId:record.locationId});return records;}
  async create(request:CreateDealDocumentRequest){const input=validateCreate(request);authorize(request.actor,request.organizationId,"document.manage");return this.provider.transaction(async session=>{await session.acquireLock(request,request.idempotencyKey);const existing=await session.findByIdempotency(request,request.idempotencyKey);if(existing){authorize(request.actor,request.organizationId,"document.manage",existing.locationId);return{requirement:existing,created:false};}const context=await session.getContractContext(request,request.dealId);if(!context)throw new DealDocumentIntegrityError("A contracted Deal bound to an accepted Quote is required.");authorize(request.actor,request.organizationId,"document.manage",context.locationId);const now=this.now().toISOString();const requirement:DealDocumentRequirement={id:generateEntityId("ddr"),organizationId:request.organizationId,locationId:context.locationId,dealId:request.dealId,quoteId:context.quoteId,quoteVersion:context.quoteVersion,documentType:input.documentType,documentVersion:await session.nextVersion(request,request.dealId,input.documentType),sourceType:request.sourceType,status:"pending",required:request.required,waiverAllowed:request.waiverAllowed,...(input.templateId?{templateId:input.templateId}:{}),...(input.templateVersion?{templateVersion:input.templateVersion}:{}),...(input.externalReference?{externalReference:input.externalReference}:{}),createdAt:now,updatedAt:now};const event=makeEvent(request,requirement.id,undefined,"pending",now);return{requirement:await session.create(ctx(request,context.locationId),requirement,event),created:true};});}
  async transition(request:TransitionDealDocumentRequest){validateTransition(request);const capability=request.toStatus==="waived"?"document.waive":"document.complete";authorize(request.actor,request.organizationId,capability);return this.provider.transaction(async session=>{await session.acquireLock(request,request.idempotencyKey);const existing=await session.findTransition(request,request.idempotencyKey);if(existing){if(existing.requirement.dealId!==request.dealId)throw new DealDocumentIntegrityError("The document requirement is unavailable.");authorize(request.actor,request.organizationId,capability,existing.requirement.locationId);return{...existing,transitioned:false};}const current=await session.getForUpdate(request,request.dealId,request.requirementId);if(!current)throw new DealDocumentIntegrityError("The document requirement is unavailable.");authorize(request.actor,request.organizationId,capability,current.locationId);if(current.sourceType==="canonical-quote")throw new DealDocumentIntegrityError("Canonical Quote evidence is immutable.");if(current.status==="complete"||current.status==="waived")throw new DealDocumentIntegrityError("The document requirement is already final.");const reason=request.reason?.trim();if(request.toStatus==="waived"&&(!current.waiverAllowed||!reason))throw new DealDocumentValidationError(["An explicit waiver policy and reason are required."]);if(request.toStatus==="complete"&&!['generated','provided'].includes(current.status))throw new DealDocumentIntegrityError("Only generated or provided document evidence can be completed.");const now=this.now().toISOString();const requirement:DealDocumentRequirement={...current,status:request.toStatus,updatedAt:now,...(request.toStatus==="complete"?{completedBy:request.actor.userId,completedAt:now}:{}),...(request.toStatus==="waived"&&reason?{waivedBy:request.actor.userId,waivedAt:now,waiverReason:reason}: {})};const event=makeEvent(request,current.id,current.status,request.toStatus,now);return{requirement:await session.transition(ctx(request,current.locationId),requirement,event),event,transitioned:true};});}
}

function validateCreate(r:CreateDealDocumentRequest){const issues:string[]=[];const documentType=r.documentType.trim().toLowerCase();if(!r.dealId.trim())issues.push("dealId is required.");if(!r.idempotencyKey.trim())issues.push("idempotencyKey is required.");if(!/^[a-z0-9][a-z0-9-]{1,63}$/.test(documentType))issues.push("documentType must be a stable kebab-case identifier.");const templateId=r.templateId?.trim();if((templateId&&!r.templateVersion)||(!templateId&&r.templateVersion))issues.push("templateId and templateVersion must be supplied together.");if(r.templateVersion!==undefined&&(!Number.isSafeInteger(r.templateVersion)||r.templateVersion<1))issues.push("templateVersion is invalid.");const externalReference=r.externalReference?.trim();if(r.sourceType==="external-reference"&&!externalReference)issues.push("externalReference is required for external evidence.");if(externalReference&&(/^[a-z]+:\/\//i.test(externalReference)||externalReference.length>500))issues.push("externalReference must be an opaque reference of 500 characters or fewer.");if(issues.length)throw new DealDocumentValidationError(issues);return{documentType,...(templateId?{templateId}:{}),...(r.templateVersion?{templateVersion:r.templateVersion}:{}),...(externalReference?{externalReference}: {})};}
function validateTransition(r:TransitionDealDocumentRequest){const issues:string[]=[];if(!r.dealId.trim())issues.push("dealId is required.");if(!r.requirementId.trim())issues.push("requirementId is required.");if(!r.idempotencyKey.trim())issues.push("idempotencyKey is required.");if(r.reason&&r.reason.trim().length>1000)issues.push("reason must not exceed 1000 characters.");if(issues.length)throw new DealDocumentValidationError(issues);}
function authorize(actor:AuthorizationActor,organizationId:string,capability:"document.manage"|"document.complete"|"document.waive",locationId?:string){assertAuthorized(actor,{capability:"document.read",organizationId,locationId});assertAuthorized(actor,{capability,organizationId,locationId});}
function ctx(r:{actor:AuthorizationActor;organizationId:string;correlationId:string},locationId:string):RequestContext{return{actorId:r.actor.userId,organizationId:r.organizationId,locationId,correlationId:r.correlationId};}
function makeEvent(r:{organizationId:string;idempotencyKey:string;reason?:string},requirementId:string,fromStatus:DealDocumentStatus|undefined,toStatus:DealDocumentStatus,occurredAt:string):DealDocumentEvent{return{id:generateEntityId("dde"),organizationId:r.organizationId,requirementId,...(fromStatus?{fromStatus}:{}),toStatus,...(r.reason?.trim()?{reason:r.reason.trim()}:{}),occurredAt,idempotencyKey:r.idempotencyKey};}
