import { describe, expect, it } from "vitest";
import type { AuthorizationActor } from "@/lib/platform/auth";
import type { RequestContext } from "@/lib/platform/data";
import { AuthorizationError } from "@/lib/platform/auth";
import { DealIntegrityError, DealService, DealTransitionError, DealValidationError,
  type CreateDealRequest, type DealProvider, type DealRecord, type DealSession, type DealStatusEvent, type TransitionDealRequest } from "./manage-deal";

class MemoryProvider implements DealProvider, DealSession {
  deals: DealRecord[] = []; events: DealStatusEvent[] = []; contextExists = true; completedDelivery = true; readyForDelivery = true;
  acceptedQuote: Awaited<ReturnType<DealSession["acceptedQuoteForContract"]>> = { quoteId: "quo_accepted", version: 3, purchaseType: "finance", totalCents: 4185000 };
  async transaction<Result>(operation: (session: DealSession) => Promise<Result>) { return operation(this); }
  async acquireIdempotencyLock() {}
  async findDealByIdempotency(scope: { organizationId: string }, key: string) { return this.deals.find((item) => item.organizationId === scope.organizationId && item.idempotencyKey === key) ?? null; }
  async creationContextExists() { return this.contextExists; }
  async createDeal(_context: RequestContext, deal: DealRecord, event: DealStatusEvent) { this.deals.push(deal); this.events.push(event); return deal; }
  async findTransitionByIdempotency(scope: { organizationId: string }, key: string) { const event = this.events.find((item) => item.organizationId === scope.organizationId && item.idempotencyKey === key); const deal = event ? this.deals.find((item) => item.id === event.dealId) : undefined; return event && deal ? { deal, event } : null; }
  async getDealForUpdate(scope: { organizationId: string }, id: string) { return this.deals.find((item) => item.organizationId === scope.organizationId && item.id === id) ?? null; }
  async deliveryCompleted() { return this.completedDelivery; }
  async acceptedQuoteForContract() { return this.acceptedQuote; }
  async deliveryReady() { return this.readyForDelivery; }
  async transitionDeal(_context: RequestContext, deal: DealRecord, event: DealStatusEvent) { const index = this.deals.findIndex((item) => item.id === deal.id); this.deals[index] = deal; this.events.push(event); return deal; }
}
const capabilities: AuthorizationActor["memberships"][number]["capabilities"] = ["deal.create", "deal.read", "deal.update", "deal.approve", "lead.read", "customer.read", "inventory.read"];
const actor = (grants = capabilities): AuthorizationActor => ({ userId: "usr_sales", memberships: [{ organizationId: "org_dealerflow", locationIds: ["loc_main"], capabilities: grants }] });
const createRequest = (overrides: Partial<CreateDealRequest> = {}): CreateDealRequest => ({ actor: actor(), organizationId: "org_dealerflow", locationId: "loc_main", correlationId: "req_deal", idempotencyKey: "deal:lead-1", customerId: "cus_jordan", leadId: "led_jordan", appointmentId: "apt_jordan", showroomVisitId: "vis_jordan", primaryVehicleId: "veh_crv", inventoryUnitId: "inv_crv", ownerUserId: "usr_sales", purchaseType: "finance", agreedPriceCents: 4200000, ...overrides });
const transitionRequest = (dealId: string, toStatus: TransitionDealRequest["toStatus"], overrides: Partial<TransitionDealRequest> = {}): TransitionDealRequest => ({ actor: actor(), organizationId: "org_dealerflow", locationId: "loc_main", correlationId: "req_status", idempotencyKey: `transition:${toStatus}`, dealId, toStatus, ...overrides });

describe("DealService", () => {
  it("creates one linked draft deal and immutable initial event for an idempotent request", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const first = await service.create(createRequest()); const second = await service.create(createRequest()); expect(first.created).toBe(true); expect(second.created).toBe(false); expect(first.deal).toMatchObject({ appointmentId: "apt_jordan", showroomVisitId: "vis_jordan", ownerUserId: "usr_sales" }); expect(first.deal.dealNumber).toMatch(/^DF-[A-Z0-9]{8}$/); expect(provider.deals).toHaveLength(1); expect(provider.events).toMatchObject([{ toStatus: "draft" }]); });
  it("rejects unavailable cross-record context", async () => { const provider = new MemoryProvider(); provider.contextExists = false; await expect(new DealService(provider).create(createRequest())).rejects.toBeInstanceOf(DealIntegrityError); });
  it("requires an appointment when a showroom visit is linked", async () => { await expect(new DealService(new MemoryProvider()).create(createRequest({ appointmentId: undefined }))).rejects.toBeInstanceOf(DealValidationError); });
  it("moves through the controlled approval and delivery lifecycle", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const { deal } = await service.create(createRequest()); await service.transition(transitionRequest(deal.id, "working")); await service.transition(transitionRequest(deal.id, "pending-approval")); await service.transition(transitionRequest(deal.id, "approved")); await service.transition(transitionRequest(deal.id, "contracted")); const result = await service.transition(transitionRequest(deal.id, "delivered")); expect(result.deal.status).toBe("delivered"); expect(provider.events.map((item) => item.toStatus)).toEqual(["draft", "working", "pending-approval", "approved", "contracted", "delivered"]); });
  it("requires approval capability and rejects terminal or skipped transitions", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const { deal } = await service.create(createRequest()); await expect(service.transition(transitionRequest(deal.id, "approved", { actor: actor(capabilities.filter((item) => item !== "deal.approve")) }))).rejects.toBeInstanceOf(AuthorizationError); await expect(service.transition(transitionRequest(deal.id, "delivered"))).rejects.toBeInstanceOf(DealTransitionError); });
  it("requires an audit reason for cancellation after work begins", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const { deal } = await service.create(createRequest()); await service.transition(transitionRequest(deal.id, "working")); await expect(service.transition(transitionRequest(deal.id, "cancelled"))).rejects.toBeInstanceOf(DealValidationError); const cancelled = await service.transition(transitionRequest(deal.id, "cancelled", { idempotencyKey: "cancel:reason", reason: "Customer postponed purchase." })); expect(cancelled.deal.status).toBe("cancelled"); });
  it("requires a completed physical handoff before delivery", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const { deal } = await service.create(createRequest()); await service.transition(transitionRequest(deal.id, "working")); await service.transition(transitionRequest(deal.id, "pending-approval")); await service.transition(transitionRequest(deal.id, "approved")); await service.transition(transitionRequest(deal.id, "contracted")); provider.completedDelivery = false; await expect(service.transition(transitionRequest(deal.id, "delivered"))).rejects.toBeInstanceOf(DealIntegrityError); });
  it("binds contracting to the exact accepted Quote version and canonical terms", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const { deal } = await service.create(createRequest()); await service.transition(transitionRequest(deal.id, "working")); await service.transition(transitionRequest(deal.id, "pending-approval")); await service.transition(transitionRequest(deal.id, "approved")); const result = await service.transition(transitionRequest(deal.id, "contracted")); expect(result.deal).toMatchObject({ acceptedQuoteId: "quo_accepted", acceptedQuoteVersion: 3, purchaseType: "finance", agreedPriceCents: 4185000 }); });
  it("refuses contracting without an accepted Quote", async () => { const provider = new MemoryProvider(); provider.acceptedQuote = null; const service = new DealService(provider); const { deal } = await service.create(createRequest()); await service.transition(transitionRequest(deal.id, "working")); await service.transition(transitionRequest(deal.id, "pending-approval")); await service.transition(transitionRequest(deal.id, "approved")); await expect(service.transition(transitionRequest(deal.id, "contracted"))).rejects.toBeInstanceOf(DealIntegrityError); });
  it("refuses sale completion while canonical delivery readiness is blocked", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const { deal } = await service.create(createRequest()); await service.transition(transitionRequest(deal.id, "working")); await service.transition(transitionRequest(deal.id, "pending-approval")); await service.transition(transitionRequest(deal.id, "approved")); await service.transition(transitionRequest(deal.id, "contracted")); provider.readyForDelivery = false; await expect(service.transition(transitionRequest(deal.id, "delivered"))).rejects.toBeInstanceOf(DealIntegrityError); });
  it("enforces the persisted deal location even when a transition omits location input", async () => { const provider = new MemoryProvider(); const service = new DealService(provider); const { deal } = await service.create(createRequest()); const restricted: AuthorizationActor = { userId: "usr_sales", memberships: [{ organizationId: "org_dealerflow", locationIds: ["loc_other"], capabilities }] }; await expect(service.transition(transitionRequest(deal.id, "working", { actor: restricted, locationId: undefined }))).rejects.toBeInstanceOf(AuthorizationError); });
});
