import { generateEntityId } from "@/lib/core/identifiers";
import { assertAuthorized, type AuthorizationActor } from "@/lib/platform/auth";
import type { OrganizationScope, RequestContext } from "@/lib/platform/data";
import type { DealStatus } from "./manage-deal";

export type TradeStatus = "draft" | "presented" | "accepted" | "rejected" | "expired" | "acquired";
export interface TradeAppraisal extends OrganizationScope { id: string; dealId: string; vehicleId: string; version: number; status: TradeStatus; allowanceCents: number; payoffCents: number; equityCents: number; odometerMiles?: number; conditionNotes?: string; lienholder?: string; expiresAt?: string; acquiredInventoryUnitId?: string; idempotencyKey: string; }
export interface TradeEvent extends OrganizationScope { id: string; appraisalId: string; fromStatus?: TradeStatus; toStatus: TradeStatus; reason?: string; occurredAt: string; idempotencyKey: string; }
export interface CreateTradeRequest extends OrganizationScope { actor: AuthorizationActor; correlationId: string; idempotencyKey: string; dealId: string; vehicleId: string; allowanceCents: number; payoffCents: number; odometerMiles?: number; conditionNotes?: string; lienholder?: string; expiresAt?: string; }
export interface TransitionTradeRequest extends OrganizationScope { actor: AuthorizationActor; correlationId: string; idempotencyKey: string; appraisalId: string; toStatus: Exclude<TradeStatus, "draft">; reason?: string; acquisition?: { stockNumber: string; listPriceCents?: number }; }
export interface TradeSession { acquireLock(scope: OrganizationScope, key: string): Promise<void>; findByIdempotency(scope: OrganizationScope, key: string): Promise<TradeAppraisal | null>; getContext(scope: OrganizationScope, dealId: string, vehicleId: string): Promise<{ dealStatus: DealStatus; locationId: string } | null>; nextVersion(scope: OrganizationScope, dealId: string, vehicleId: string): Promise<number>; create(context: RequestContext, item: TradeAppraisal, event: TradeEvent): Promise<TradeAppraisal>; findTransition(scope: OrganizationScope, key: string): Promise<{ appraisal: TradeAppraisal; event: TradeEvent } | null>; getForUpdate(scope: OrganizationScope, id: string): Promise<{ appraisal: TradeAppraisal; dealStatus: DealStatus; locationId: string } | null>; hasAccepted(scope: OrganizationScope, dealId: string, vehicleId: string, exceptId: string): Promise<boolean>; transition(context: RequestContext, item: TradeAppraisal, event: TradeEvent, acquisition?: { inventoryUnitId: string; stockNumber: string; listPriceCents?: number }): Promise<TradeAppraisal>; }
export interface TradeProvider { transaction<Result>(operation: (session: TradeSession) => Promise<Result>): Promise<Result>; }

export type DeliveryStatus = "scheduled" | "ready" | "completed" | "cancelled";
export interface DealDelivery extends OrganizationScope { id: string; dealId: string; status: DeliveryStatus; startsAt: string; endsAt: string; timezone: string; notes?: string; completedAt?: string; idempotencyKey: string; }
export interface DeliveryEvent extends OrganizationScope { id: string; deliveryId: string; fromStatus?: DeliveryStatus; toStatus: DeliveryStatus; reason?: string; occurredAt: string; idempotencyKey: string; }
export interface ScheduleDeliveryRequest extends OrganizationScope { actor: AuthorizationActor; correlationId: string; idempotencyKey: string; dealId: string; startsAt: string; endsAt: string; timezone: string; notes?: string; }
export interface TransitionDeliveryRequest extends OrganizationScope { actor: AuthorizationActor; correlationId: string; idempotencyKey: string; deliveryId: string; toStatus: Exclude<DeliveryStatus, "scheduled">; reason?: string; }
export interface DeliverySession { acquireLock(scope: OrganizationScope, key: string): Promise<void>; findByIdempotency(scope: OrganizationScope, key: string): Promise<DealDelivery | null>; getDealContext(scope: OrganizationScope, dealId: string): Promise<{ dealStatus: DealStatus; locationId: string } | null>; create(context: RequestContext, item: DealDelivery, event: DeliveryEvent): Promise<DealDelivery>; findTransition(scope: OrganizationScope, key: string): Promise<{ delivery: DealDelivery; event: DeliveryEvent } | null>; getForUpdate(scope: OrganizationScope, id: string): Promise<{ delivery: DealDelivery; dealStatus: DealStatus; locationId: string } | null>; transition(context: RequestContext, item: DealDelivery, event: DeliveryEvent): Promise<DealDelivery>; }
export interface DeliveryProvider { transaction<Result>(operation: (session: DeliverySession) => Promise<Result>): Promise<Result>; }
export class HandoffValidationError extends Error { constructor(readonly issues: readonly string[]) { super("Deal handoff data is invalid."); this.name = "HandoffValidationError"; } }
export class HandoffIntegrityError extends Error { constructor(message: string) { super(message); this.name = "HandoffIntegrityError"; } }
export class HandoffTransitionError extends Error { constructor(from: string, to: string) { super(`Record cannot transition from ${from} to ${to}.`); this.name = "HandoffTransitionError"; } }

export class TradeAppraisalService {
  constructor(private readonly provider: TradeProvider, private readonly now: () => Date = () => new Date()) {}
  async create(request: CreateTradeRequest): Promise<{ appraisal: TradeAppraisal; created: boolean }> { const input = validateTrade(request); authorize(request.actor, request.organizationId); return this.provider.transaction(async (session) => { await session.acquireLock(request, request.idempotencyKey); const existing = await session.findByIdempotency(request, request.idempotencyKey); if (existing) { authorize(request.actor, request.organizationId, existing.locationId); return { appraisal: existing, created: false }; } await session.acquireLock(request, `trade-version:${request.dealId}:${request.vehicleId}`); const resolved = await session.getContext(request, request.dealId, request.vehicleId); if (!resolved) throw new HandoffIntegrityError("The Deal and trade vehicle context is unavailable."); authorize(request.actor, request.organizationId, resolved.locationId); if (["contracted", "delivered", "cancelled"].includes(resolved.dealStatus)) throw new HandoffIntegrityError("This Deal no longer accepts trade appraisals."); if (input.expiresAt && new Date(input.expiresAt) <= this.now()) throw new HandoffValidationError(["expiresAt must be in the future."]); const id = generateEntityId("tap"); const appraisal: TradeAppraisal = { id, organizationId: request.organizationId, locationId: resolved.locationId, dealId: request.dealId, vehicleId: request.vehicleId, version: await session.nextVersion(request, request.dealId, request.vehicleId), status: "draft", allowanceCents: input.allowanceCents, payoffCents: input.payoffCents, equityCents: input.allowanceCents - input.payoffCents, ...(input.odometerMiles !== undefined ? { odometerMiles: input.odometerMiles } : {}), ...(input.conditionNotes ? { conditionNotes: input.conditionNotes } : {}), ...(input.lienholder ? { lienholder: input.lienholder } : {}), ...(input.expiresAt ? { expiresAt: input.expiresAt } : {}), idempotencyKey: request.idempotencyKey }; const event = tradeEvent(request, id, undefined, "draft", this.now()); return { appraisal: await session.create(ctx(request), appraisal, event), created: true }; }); }
  async transition(request: TransitionTradeRequest): Promise<{ appraisal: TradeAppraisal; event: TradeEvent; transitioned: boolean }> { validateTradeTransition(request); authorize(request.actor, request.organizationId); return this.provider.transaction(async (session) => { await session.acquireLock(request, request.idempotencyKey); const existing = await session.findTransition(request, request.idempotencyKey); if (existing) { authorize(request.actor, request.organizationId, existing.appraisal.locationId); return { ...existing, transitioned: false }; } const resolved = await session.getForUpdate(request, request.appraisalId); if (!resolved) throw new HandoffIntegrityError("The appraisal is unavailable."); authorize(request.actor, request.organizationId, resolved.locationId); await session.acquireLock(request, `trade-decision:${resolved.appraisal.dealId}:${resolved.appraisal.vehicleId}`); if (!tradeAllowed[resolved.appraisal.status].includes(request.toStatus)) throw new HandoffTransitionError(resolved.appraisal.status, request.toStatus); const now = this.now(); if (request.toStatus === "accepted" && resolved.appraisal.expiresAt && new Date(resolved.appraisal.expiresAt) <= now) throw new HandoffIntegrityError("An expired appraisal cannot be accepted."); if (request.toStatus === "accepted" && await session.hasAccepted(request, resolved.appraisal.dealId, resolved.appraisal.vehicleId, resolved.appraisal.id)) throw new HandoffIntegrityError("This trade already has an accepted appraisal."); if ((request.toStatus === "rejected" || request.toStatus === "expired") && !request.reason?.trim()) throw new HandoffValidationError(["reason is required for rejection or expiration."]); let acquisition: { inventoryUnitId: string; stockNumber: string; listPriceCents?: number } | undefined; if (request.toStatus === "acquired") { if (!["contracted", "delivered"].includes(resolved.dealStatus)) throw new HandoffIntegrityError("Trade acquisition requires a contracted Deal."); const stockNumber = request.acquisition?.stockNumber.trim(); if (!stockNumber) throw new HandoffValidationError(["acquisition.stockNumber is required."]); const price = request.acquisition?.listPriceCents; if (price !== undefined && (!Number.isSafeInteger(price) || price < 0)) throw new HandoffValidationError(["acquisition.listPriceCents is invalid."]); acquisition = { inventoryUnitId: generateEntityId("inv"), stockNumber, ...(price !== undefined ? { listPriceCents: price } : {}) }; } const appraisal = { ...resolved.appraisal, status: request.toStatus, ...(acquisition ? { acquiredInventoryUnitId: acquisition.inventoryUnitId } : {}) }; const event = tradeEvent(request, appraisal.id, resolved.appraisal.status, request.toStatus, now); return { appraisal: await session.transition(ctx(request), appraisal, event, acquisition), event, transitioned: true }; }); }
}

export class DeliveryService {
  constructor(private readonly provider: DeliveryProvider, private readonly now: () => Date = () => new Date()) {}
  async schedule(request: ScheduleDeliveryRequest): Promise<{ delivery: DealDelivery; created: boolean }> { const input = validateDelivery(request); authorize(request.actor, request.organizationId); return this.provider.transaction(async (session) => { await session.acquireLock(request, request.idempotencyKey); const existing = await session.findByIdempotency(request, request.idempotencyKey); if (existing) { authorize(request.actor, request.organizationId, existing.locationId); return { delivery: existing, created: false }; } const deal = await session.getDealContext(request, request.dealId); if (!deal) throw new HandoffIntegrityError("The Deal is unavailable."); authorize(request.actor, request.organizationId, deal.locationId); if (!["approved", "contracted"].includes(deal.dealStatus)) throw new HandoffIntegrityError("Delivery may be scheduled only for an approved or contracted Deal."); const id = generateEntityId("dlv"); const delivery: DealDelivery = { id, organizationId: request.organizationId, locationId: deal.locationId, dealId: request.dealId, status: "scheduled", startsAt: input.startsAt, endsAt: input.endsAt, timezone: input.timezone, ...(input.notes ? { notes: input.notes } : {}), idempotencyKey: request.idempotencyKey }; const event: DeliveryEvent = { id: generateEntityId("dse"), organizationId: request.organizationId, locationId: deal.locationId, deliveryId: id, toStatus: "scheduled", occurredAt: this.now().toISOString(), idempotencyKey: `create:${request.idempotencyKey}` }; return { delivery: await session.create(ctx(request), delivery, event), created: true }; }); }
  async transition(request: TransitionDeliveryRequest): Promise<{ delivery: DealDelivery; event: DeliveryEvent; transitioned: boolean }> { validateDeliveryTransition(request); authorize(request.actor, request.organizationId); return this.provider.transaction(async (session) => { await session.acquireLock(request, request.idempotencyKey); const existing = await session.findTransition(request, request.idempotencyKey); if (existing) { authorize(request.actor, request.organizationId, existing.delivery.locationId); return { ...existing, transitioned: false }; } const resolved = await session.getForUpdate(request, request.deliveryId); if (!resolved) throw new HandoffIntegrityError("The delivery is unavailable."); authorize(request.actor, request.organizationId, resolved.locationId); if (!deliveryAllowed[resolved.delivery.status].includes(request.toStatus)) throw new HandoffTransitionError(resolved.delivery.status, request.toStatus); if (request.toStatus === "completed" && resolved.dealStatus !== "contracted") throw new HandoffIntegrityError("Delivery completion requires a contracted Deal."); if (request.toStatus === "cancelled" && !request.reason?.trim()) throw new HandoffValidationError(["reason is required for cancellation."]); const now = this.now(); const delivery = { ...resolved.delivery, status: request.toStatus, ...(request.toStatus === "completed" ? { completedAt: now.toISOString() } : {}) }; const event: DeliveryEvent = { id: generateEntityId("dse"), organizationId: request.organizationId, locationId: resolved.locationId, deliveryId: delivery.id, fromStatus: resolved.delivery.status, toStatus: request.toStatus, ...(request.reason?.trim() ? { reason: request.reason.trim() } : {}), occurredAt: now.toISOString(), idempotencyKey: request.idempotencyKey }; return { delivery: await session.transition(ctx(request), delivery, event), event, transitioned: true }; }); }
}

const tradeAllowed: Record<TradeStatus, readonly TradeStatus[]> = { draft: ["presented", "expired"], presented: ["accepted", "rejected", "expired"], accepted: ["acquired"], rejected: [], expired: [], acquired: [] }; const deliveryAllowed: Record<DeliveryStatus, readonly DeliveryStatus[]> = { scheduled: ["ready", "cancelled"], ready: ["completed", "cancelled"], completed: [], cancelled: [] };
function validateTrade(r: CreateTradeRequest) { const issues: string[] = []; for (const [key, value] of [["dealId", r.dealId], ["vehicleId", r.vehicleId], ["idempotencyKey", r.idempotencyKey]] as const) if (!value.trim()) issues.push(`${key} is required.`); for (const [key, value] of [["allowanceCents", r.allowanceCents], ["payoffCents", r.payoffCents]] as const) if (!Number.isSafeInteger(value) || value < 0) issues.push(`${key} is invalid.`); if (r.odometerMiles !== undefined && (!Number.isSafeInteger(r.odometerMiles) || r.odometerMiles < 0)) issues.push("odometerMiles is invalid."); const conditionNotes = r.conditionNotes?.trim(); if (conditionNotes && conditionNotes.length > 2000) issues.push("conditionNotes is too long."); const expiresAt = r.expiresAt?.trim(); if (expiresAt && Number.isNaN(new Date(expiresAt).valueOf())) issues.push("expiresAt is invalid."); if (issues.length) throw new HandoffValidationError(issues); return { allowanceCents: r.allowanceCents, payoffCents: r.payoffCents, ...(r.odometerMiles !== undefined ? { odometerMiles: r.odometerMiles } : {}), ...(conditionNotes ? { conditionNotes } : {}), ...(r.lienholder?.trim() ? { lienholder: r.lienholder.trim() } : {}), ...(expiresAt ? { expiresAt: new Date(expiresAt).toISOString() } : {}) }; }
function validateTradeTransition(r: TransitionTradeRequest) { const issues: string[] = []; if (!r.appraisalId.trim()) issues.push("appraisalId is required."); if (!r.idempotencyKey.trim()) issues.push("idempotencyKey is required."); if (r.reason && r.reason.trim().length > 1000) issues.push("reason is too long."); if (issues.length) throw new HandoffValidationError(issues); }
function validateDelivery(r: ScheduleDeliveryRequest) { const issues: string[] = []; const starts = new Date(r.startsAt); const ends = new Date(r.endsAt); if (!r.dealId.trim()) issues.push("dealId is required."); if (!r.idempotencyKey.trim()) issues.push("idempotencyKey is required."); if (Number.isNaN(starts.valueOf()) || Number.isNaN(ends.valueOf()) || ends <= starts) issues.push("Delivery time range is invalid."); try { new Intl.DateTimeFormat("en-US", { timeZone: r.timezone }).format(starts); } catch { issues.push("timezone is invalid."); } const notes = r.notes?.trim(); if (notes && notes.length > 2000) issues.push("notes is too long."); if (issues.length) throw new HandoffValidationError(issues); return { startsAt: starts.toISOString(), endsAt: ends.toISOString(), timezone: r.timezone, ...(notes ? { notes } : {}) }; }
function validateDeliveryTransition(r: TransitionDeliveryRequest) { const issues: string[] = []; if (!r.deliveryId.trim()) issues.push("deliveryId is required."); if (!r.idempotencyKey.trim()) issues.push("idempotencyKey is required."); if (r.reason && r.reason.trim().length > 1000) issues.push("reason is too long."); if (issues.length) throw new HandoffValidationError(issues); }
function authorize(actor: AuthorizationActor, organizationId: string, locationId?: string) { for (const capability of ["deal.read", "deal.update", "inventory.read"] as const) assertAuthorized(actor, { capability, organizationId, locationId }); }
function tradeEvent(r: TransitionTradeRequest | CreateTradeRequest, appraisalId: string, fromStatus: TradeStatus | undefined, toStatus: TradeStatus, now: Date): TradeEvent { const reason = "reason" in r ? r.reason?.trim() : undefined; return { id: generateEntityId("tas"), organizationId: r.organizationId, ...(r.locationId ? { locationId: r.locationId } : {}), appraisalId, ...(fromStatus ? { fromStatus } : {}), toStatus, ...(reason ? { reason } : {}), occurredAt: now.toISOString(), idempotencyKey: "toStatus" in r ? r.idempotencyKey : `create:${r.idempotencyKey}` }; }
function ctx(r: { actor: AuthorizationActor; organizationId: string; correlationId: string; locationId?: string }): RequestContext { return { actorId: r.actor.userId, organizationId: r.organizationId, correlationId: r.correlationId, ...(r.locationId ? { locationId: r.locationId } : {}) }; }
