import { describe, expect, it } from "vitest";
import type { AuthorizationActor } from "@/lib/platform/auth";
import { AuthorizationError } from "@/lib/platform/auth";
import type { RequestContext } from "@/lib/platform/data";
import { QuoteIntegrityError, QuoteService, QuoteTransitionError, QuoteValidationError,
  type CreateQuoteRequest, type QuoteProvider, type QuoteRecord, type QuoteSession, type QuoteStatusEvent, type TransitionQuoteRequest } from "./manage-quote";

class MemoryProvider implements QuoteProvider, QuoteSession {
  quotes: QuoteRecord[] = []; events: QuoteStatusEvent[] = []; dealStatus = "working" as const; locationId = "loc_main";
  async transaction<Result>(operation: (session: QuoteSession) => Promise<Result>) { return operation(this); }
  async acquireLock() {}
  async findQuoteByIdempotency(scope: { organizationId: string }, key: string) { return this.quotes.find((item) => item.organizationId === scope.organizationId && item.idempotencyKey === key) ?? null; }
  async getDealContextForUpdate() { return { status: this.dealStatus, locationId: this.locationId }; }
  async nextVersion(_scope: { organizationId: string }, dealId: string) { return this.quotes.filter((item) => item.dealId === dealId).length + 1; }
  async createQuote(_context: RequestContext, quote: QuoteRecord, event: QuoteStatusEvent) { this.quotes.push(quote); this.events.push(event); return quote; }
  async findTransitionByIdempotency(scope: { organizationId: string }, key: string) { const event = this.events.find((item) => item.organizationId === scope.organizationId && item.idempotencyKey === key); const quote = event ? this.quotes.find((item) => item.id === event.quoteId) : undefined; return event && quote ? { quote, event } : null; }
  async getQuoteForUpdate(_scope: { organizationId: string }, quoteId: string) { const quote = this.quotes.find((item) => item.id === quoteId); return quote ? { quote, dealStatus: this.dealStatus, locationId: this.locationId } : null; }
  async hasAcceptedQuote(_scope: { organizationId: string }, dealId: string, exceptId: string) { return this.quotes.some((item) => item.dealId === dealId && item.id !== exceptId && item.status === "accepted"); }
  async transitionQuote(_context: RequestContext, quote: QuoteRecord, event: QuoteStatusEvent) { const index = this.quotes.findIndex((item) => item.id === quote.id); this.quotes[index] = quote; this.events.push(event); return quote; }
}
const capabilities: AuthorizationActor["memberships"][number]["capabilities"] = ["deal.read", "deal.update"];
const actor = (locationIds: readonly string[] | "all" = ["loc_main"]): AuthorizationActor => ({ userId: "usr_finance", memberships: [{ organizationId: "org_dealerflow", locationIds, capabilities }] });
const createRequest = (overrides: Partial<CreateQuoteRequest> = {}): CreateQuoteRequest => ({ actor: actor(), organizationId: "org_dealerflow", correlationId: "req_quote", idempotencyKey: "quote:deal-1:v1", dealId: "dea_12345678", purchaseType: "finance", expiresAt: "2026-09-01T12:00:00.000Z", lines: [{ category: "vehicle", description: "2026 Honda CR-V Hybrid Touring", unitAmountCents: 4200000 }, { category: "product", description: "Vehicle service contract", unitAmountCents: 250000 }, { category: "fee", description: "Documentation fee", unitAmountCents: 49900 }, { category: "tax", description: "Sales tax", unitAmountCents: 260000 }, { category: "discount", description: "Dealer discount", unitAmountCents: -100000 }], ...overrides });
const transitionRequest = (quoteId: string, status: TransitionQuoteRequest["toStatus"], overrides: Partial<TransitionQuoteRequest> = {}): TransitionQuoteRequest => ({ actor: actor(), organizationId: "org_dealerflow", correlationId: "req_quote_status", idempotencyKey: `quote:${status}`, quoteId, toStatus: status, ...overrides });

describe("QuoteService", () => {
  it("calculates an immutable quote version from typed line items", async () => { const provider = new MemoryProvider(); const service = new QuoteService(provider, () => new Date("2026-08-23T12:00:00.000Z")); const first = await service.create(createRequest()); const retry = await service.create(createRequest()); expect(first.created).toBe(true); expect(retry.created).toBe(false); expect(first.quote).toMatchObject({ version: 1, subtotalCents: 4450000, feeCents: 49900, taxCents: 260000, discountCents: -100000, totalCents: 4659900 }); expect(provider.quotes).toHaveLength(1); });
  it("allocates a new version without rewriting the first quote", async () => { const provider = new MemoryProvider(); const service = new QuoteService(provider, () => new Date("2026-08-23T12:00:00.000Z")); const first = await service.create(createRequest()); const second = await service.create(createRequest({ idempotencyKey: "quote:deal-1:v2", lines: [{ category: "vehicle", description: "CR-V", unitAmountCents: 4100000 }] })); expect(first.quote.version).toBe(1); expect(second.quote.version).toBe(2); expect(first.quote.totalCents).toBe(4659900); });
  it("requires exactly one vehicle line and safe signed arithmetic", async () => { const service = new QuoteService(new MemoryProvider()); await expect(service.create(createRequest({ lines: [{ category: "discount", description: "Wrong sign", unitAmountCents: 100 }] }))).rejects.toBeInstanceOf(QuoteValidationError); });
  it("presents and accepts a current quote through controlled transitions", async () => { const provider = new MemoryProvider(); const service = new QuoteService(provider, () => new Date("2026-08-23T12:00:00.000Z")); const { quote } = await service.create(createRequest()); await service.transition(transitionRequest(quote.id, "presented")); const result = await service.transition(transitionRequest(quote.id, "accepted")); expect(result.quote.status).toBe("accepted"); expect(result.quote.acceptedAt).toBe("2026-08-23T12:00:00.000Z"); });
  it("prevents skipped transitions and expired acceptance", async () => { const provider = new MemoryProvider(); const service = new QuoteService(provider, () => new Date("2026-08-25T12:00:00.000Z")); const { quote } = await service.create(createRequest({ expiresAt: "2026-08-26T12:00:00.000Z" })); await expect(service.transition(transitionRequest(quote.id, "accepted"))).rejects.toBeInstanceOf(QuoteTransitionError); await service.transition(transitionRequest(quote.id, "presented")); provider.quotes[0]!.expiresAt = "2026-08-24T12:00:00.000Z"; await expect(service.transition(transitionRequest(quote.id, "accepted"))).rejects.toBeInstanceOf(QuoteIntegrityError); });
  it("allows only one accepted version per deal", async () => { const provider = new MemoryProvider(); const service = new QuoteService(provider, () => new Date("2026-08-23T12:00:00.000Z")); const first = await service.create(createRequest()); const second = await service.create(createRequest({ idempotencyKey: "quote:v2" })); await service.transition(transitionRequest(first.quote.id, "presented", { idempotencyKey: "first:present" })); await service.transition(transitionRequest(first.quote.id, "accepted", { idempotencyKey: "first:accept" })); await service.transition(transitionRequest(second.quote.id, "presented", { idempotencyKey: "second:present" })); await expect(service.transition(transitionRequest(second.quote.id, "accepted", { idempotencyKey: "second:accept" }))).rejects.toBeInstanceOf(QuoteIntegrityError); });
  it("enforces the persisted deal location", async () => { const provider = new MemoryProvider(); const service = new QuoteService(provider, () => new Date("2026-08-23T12:00:00.000Z")); await expect(service.create(createRequest({ actor: actor(["loc_other"]) }))).rejects.toBeInstanceOf(AuthorizationError); });
});
