import { generateEntityId } from "@/lib/core/identifiers";
import { assertAuthorized, type AuthorizationActor } from "@/lib/platform/auth";
import { withTenantDatabaseContext, type DatabasePool } from "@/lib/server/database";
import { InventoryMediaStorageError, type InventoryImageContentType, R2InventoryMediaStorage } from "./r2-media-storage";

export class InventoryMediaValidationError extends Error { constructor(readonly issues:readonly string[]){super("Inventory media is invalid.");this.name="InventoryMediaValidationError";} }
export class InventoryMediaIntegrityError extends Error { constructor(message:string){super(message);this.name="InventoryMediaIntegrityError";} }
type UploadRow={id:string;organization_id:string;location_id:string;vehicle_id:string;inventory_unit_id:string;object_key:string;original_filename:string;content_type:InventoryImageContentType;expected_byte_size:number;alt_text:string;status:string;expires_at:Date;media_id:string|null};

export class InventoryMediaManager {
  constructor(private readonly pool:DatabasePool,private readonly storage:R2InventoryMediaStorage){}
  async initiate(input:{actor:AuthorizationActor;organizationId:string;inventoryUnitId:string;filename:string;contentType:string;byteSize:number;altText:string;idempotencyKey:string}){
    const values=validate(input);for(const capability of["inventory.read","inventory.update"]as const)assertAuthorized(input.actor,{capability,organizationId:input.organizationId});
    const upload=await withTenantDatabaseContext(this.pool,{userId:input.actor.userId,organizationId:input.organizationId},async(client)=>{
      await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`${input.organizationId}:${input.idempotencyKey}`]);
      const existing=await client.query("SELECT * FROM inventory_media_uploads WHERE organization_id=$1 AND idempotency_key=$2 LIMIT 1",[input.organizationId,input.idempotencyKey])as{rows:UploadRow[]};if(existing.rows[0])return existing.rows[0];
      const unit=await client.query("SELECT location_id,vehicle_id FROM inventory_units WHERE organization_id=$1 AND id=$2",[input.organizationId,input.inventoryUnitId])as{rows:Array<{location_id:string;vehicle_id:string}>};const context=unit.rows[0];if(!context)throw new InventoryMediaIntegrityError("The inventory unit is unavailable.");assertAuthorized(input.actor,{capability:"inventory.update",organizationId:input.organizationId,locationId:context.location_id});
      const id=generateEntityId("imu"),objectKey=`organizations/${input.organizationId}/inventory/${input.inventoryUnitId}/${id}.${extension(values.contentType)}`,expiresAt=new Date(Date.now()+5*60_000);
      const result=await client.query(`INSERT INTO inventory_media_uploads(id,organization_id,location_id,vehicle_id,inventory_unit_id,object_key,original_filename,content_type,expected_byte_size,alt_text,expires_at,idempotency_key,initiated_by)
        VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[id,input.organizationId,context.location_id,context.vehicle_id,input.inventoryUnitId,objectKey,values.filename,values.contentType,values.byteSize,values.altText,expiresAt,input.idempotencyKey,input.actor.userId])as{rows:UploadRow[]};return result.rows[0]!;
    });
    if(upload.status!=="pending"||upload.expires_at.getTime()<=Date.now())throw new InventoryMediaIntegrityError("The upload intent is no longer active.");
    const signed=await this.storage.createUploadUrl({objectKey:upload.object_key,contentType:upload.content_type,byteSize:upload.expected_byte_size});return{uploadId:upload.id,...signed};
  }
  async complete(input:{actor:AuthorizationActor;organizationId:string;inventoryUnitId:string;uploadId:string}){
    for(const capability of["inventory.read","inventory.update"]as const)assertAuthorized(input.actor,{capability,organizationId:input.organizationId});const upload=await this.readUpload(input);if(upload.media_id)return{mediaId:upload.media_id,created:false};if(upload.status!=="pending"||upload.expires_at.getTime()<=Date.now())throw new InventoryMediaIntegrityError("The upload intent is no longer active.");
    const verified=await this.storage.verify({objectKey:upload.object_key,contentType:upload.content_type,byteSize:upload.expected_byte_size});
    return withTenantDatabaseContext(this.pool,{userId:input.actor.userId,organizationId:input.organizationId},async(client)=>{const locked=await client.query("SELECT * FROM inventory_media_uploads WHERE organization_id=$1 AND id=$2 FOR UPDATE",[input.organizationId,input.uploadId])as{rows:UploadRow[]};const current=locked.rows[0];if(!current||current.inventory_unit_id!==input.inventoryUnitId)throw new InventoryMediaIntegrityError("The upload intent is unavailable.");if(current.media_id)return{mediaId:current.media_id,created:false};if(current.status!=="pending")throw new InventoryMediaIntegrityError("The upload intent is no longer active.");const mediaId=generateEntityId("ima");const order=await client.query("SELECT coalesce(max(sort_order),-1)+1 AS next_order FROM inventory_unit_media WHERE organization_id=$1 AND inventory_unit_id=$2 AND status='active'",[input.organizationId,input.inventoryUnitId])as{rows:Array<{next_order:number}>};const nextOrder=order.rows[0]?.next_order??0;await client.query(`INSERT INTO inventory_unit_media(id,organization_id,location_id,vehicle_id,inventory_unit_id,provider,provider_asset_id,delivery_url,content_type,byte_size,sha256,width,height,alt_text,sort_order,source_type,media_type,original_filename,is_primary,verified_at,verified_by)
      VALUES($1,$2,$3,$4,$5,'r2',$6,$7,$8,$9,$10,$11,$12,$13,$14,'actual','image',$15,$16,now(),$17)`,[mediaId,input.organizationId,current.location_id,current.vehicle_id,input.inventoryUnitId,current.object_key,this.storage.publicUrl(current.object_key),verified.contentType,verified.byteSize,verified.sha256,verified.width,verified.height,current.alt_text,nextOrder,current.original_filename,nextOrder===0,input.actor.userId]);await client.query("UPDATE inventory_media_uploads SET status='completed',completed_at=now(),media_id=$3,updated_at=now() WHERE organization_id=$1 AND id=$2",[input.organizationId,input.uploadId,mediaId]);await audit(client,input.actor.userId,input.organizationId,"inventory_media.verified",mediaId);return{mediaId,created:true};});
  }
  async remove(input:{actor:AuthorizationActor;organizationId:string;inventoryUnitId:string;mediaId:string;reason:string}){const reason=input.reason.trim();if(!reason||reason.length>500)throw new InventoryMediaValidationError(["reason must contain 1 to 500 characters."]);for(const capability of["inventory.read","inventory.update"]as const)assertAuthorized(input.actor,{capability,organizationId:input.organizationId});const objectKey=await withTenantDatabaseContext(this.pool,{userId:input.actor.userId,organizationId:input.organizationId},async(client)=>{const result=await client.query("SELECT location_id,provider_asset_id,status,is_primary FROM inventory_unit_media WHERE organization_id=$1 AND inventory_unit_id=$2 AND id=$3 FOR UPDATE",[input.organizationId,input.inventoryUnitId,input.mediaId])as{rows:Array<{location_id:string;provider_asset_id:string;status:string;is_primary:boolean}>};const media=result.rows[0];if(!media)throw new InventoryMediaIntegrityError("The inventory photo is unavailable.");assertAuthorized(input.actor,{capability:"inventory.update",organizationId:input.organizationId,locationId:media.location_id});if(media.status==="removed")return media.provider_asset_id;await client.query("UPDATE inventory_unit_media SET status='removed',is_primary=false,removed_at=now(),removed_by=$4,removal_reason=$5,updated_at=now() WHERE organization_id=$1 AND inventory_unit_id=$2 AND id=$3",[input.organizationId,input.inventoryUnitId,input.mediaId,input.actor.userId,reason]);if(media.is_primary)await client.query("UPDATE inventory_unit_media SET is_primary=true,updated_at=now() WHERE organization_id=$1 AND id=(SELECT id FROM inventory_unit_media WHERE organization_id=$1 AND inventory_unit_id=$2 AND status='active' ORDER BY sort_order,id LIMIT 1)",[input.organizationId,input.inventoryUnitId]);await audit(client,input.actor.userId,input.organizationId,"inventory_media.removed",input.mediaId);return media.provider_asset_id;});let storageRemoved=true;try{await this.storage.remove(objectKey);}catch{storageRemoved=false;}return{removed:true,storageRemoved};}
  async reorder(input:{actor:AuthorizationActor;organizationId:string;inventoryUnitId:string;mediaId:string;direction:"earlier"|"later"}){for(const capability of["inventory.read","inventory.update"]as const)assertAuthorized(input.actor,{capability,organizationId:input.organizationId});return withTenantDatabaseContext(this.pool,{userId:input.actor.userId,organizationId:input.organizationId},async(client)=>{const result=await client.query("SELECT id,location_id,sort_order FROM inventory_unit_media WHERE organization_id=$1 AND inventory_unit_id=$2 AND status='active' ORDER BY sort_order,id FOR UPDATE",[input.organizationId,input.inventoryUnitId])as{rows:Array<{id:string;location_id:string;sort_order:number}>};const index=result.rows.findIndex(item=>item.id===input.mediaId);if(index<0)throw new InventoryMediaIntegrityError("The inventory photo is unavailable.");assertAuthorized(input.actor,{capability:"inventory.update",organizationId:input.organizationId,locationId:result.rows[index]!.location_id});const otherIndex=input.direction==="earlier"?index-1:index+1;if(otherIndex<0||otherIndex>=result.rows.length)return{changed:false};const current=result.rows[index]!,other=result.rows[otherIndex]!;await client.query("UPDATE inventory_unit_media SET sort_order=CASE id WHEN $3 THEN $4 WHEN $5 THEN $6 END,updated_at=now() WHERE organization_id=$1 AND inventory_unit_id=$2 AND id IN($3,$5)",[input.organizationId,input.inventoryUnitId,current.id,other.sort_order,other.id,current.sort_order]);await audit(client,input.actor.userId,input.organizationId,"inventory_media.reordered",input.mediaId);return{changed:true};});}
  async setPrimary(input:{actor:AuthorizationActor;organizationId:string;inventoryUnitId:string;mediaId:string}){for(const capability of["inventory.read","inventory.update"]as const)assertAuthorized(input.actor,{capability,organizationId:input.organizationId});return withTenantDatabaseContext(this.pool,{userId:input.actor.userId,organizationId:input.organizationId},async(client)=>{const result=await client.query("SELECT id,location_id,is_primary FROM inventory_unit_media WHERE organization_id=$1 AND inventory_unit_id=$2 AND status='active' ORDER BY sort_order,id FOR UPDATE",[input.organizationId,input.inventoryUnitId])as{rows:Array<{id:string;location_id:string;is_primary:boolean}>};const media=result.rows.find(item=>item.id===input.mediaId);if(!media)throw new InventoryMediaIntegrityError("The inventory photo is unavailable.");assertAuthorized(input.actor,{capability:"inventory.update",organizationId:input.organizationId,locationId:media.location_id});if(media.is_primary)return{changed:false};await client.query("UPDATE inventory_unit_media SET is_primary=false,updated_at=now() WHERE organization_id=$1 AND inventory_unit_id=$2 AND status='active' AND is_primary=true",[input.organizationId,input.inventoryUnitId]);await client.query("UPDATE inventory_unit_media SET is_primary=true,updated_at=now() WHERE organization_id=$1 AND inventory_unit_id=$2 AND id=$3 AND status='active'",[input.organizationId,input.inventoryUnitId,input.mediaId]);await audit(client,input.actor.userId,input.organizationId,"inventory_media.primary_changed",input.mediaId);return{changed:true};});}
  private async readUpload(input:{actor:AuthorizationActor;organizationId:string;inventoryUnitId:string;uploadId:string}){return withTenantDatabaseContext(this.pool,{userId:input.actor.userId,organizationId:input.organizationId},async(client)=>{const result=await client.query("SELECT * FROM inventory_media_uploads WHERE organization_id=$1 AND id=$2 AND inventory_unit_id=$3",[input.organizationId,input.uploadId,input.inventoryUnitId])as{rows:UploadRow[]};const row=result.rows[0];if(!row)throw new InventoryMediaIntegrityError("The upload intent is unavailable.");assertAuthorized(input.actor,{capability:"inventory.update",organizationId:input.organizationId,locationId:row.location_id});return row;});}
}
function validate(input:{filename:string;contentType:string;byteSize:number;altText:string;idempotencyKey:string}){const issues:string[]=[];const filename=input.filename.trim(),altText=input.altText.trim();const allowed=["image/jpeg","image/png","image/webp"]as const;const contentType=allowed.find(value=>value===input.contentType);if(!filename||filename.length>255)issues.push("filename must contain 1 to 255 characters.");if(!contentType)issues.push("contentType must be image/jpeg, image/png, or image/webp.");if(!Number.isSafeInteger(input.byteSize)||input.byteSize<1||input.byteSize>20*1024*1024)issues.push("byteSize must be between 1 byte and 20 MB.");if(!altText||altText.length>300)issues.push("altText must contain 1 to 300 characters.");if(!input.idempotencyKey.trim())issues.push("idempotencyKey is required.");if(issues.length||!contentType)throw new InventoryMediaValidationError(issues);return{filename,altText,contentType,byteSize:input.byteSize};}
function extension(type:InventoryImageContentType){return type==="image/jpeg"?"jpg":type==="image/png"?"png":"webp";}
export{InventoryMediaStorageError};
async function audit(client:{query(query:string,values?:readonly unknown[]):Promise<unknown>},actorId:string,organizationId:string,action:string,entityId:string){await client.query("INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,source,correlation_id) VALUES($1,$2,$3,$4,'inventory_media',$5,'application',$6)",[generateEntityId("aud"),organizationId,actorId,action,entityId,`media:${generateEntityId("evt")}`]);}
