import { describe, expect, it, vi } from "vitest";
import type { DatabaseClient, DatabasePool } from "@/lib/server/database";
import { InventoryDirectoryError, InventoryDirectoryReader } from "./inventory-directory";

describe("InventoryDirectoryReader", () => {
  it("embeds allowed locations in the inventory query", async () => { const query = vi.fn<DatabaseClient["query"]>().mockResolvedValueOnce({}).mockResolvedValueOnce({}).mockResolvedValueOnce({ rows: [] }).mockResolvedValueOnce({}); const client: DatabaseClient = { query, release: vi.fn() }; const pool: DatabasePool = { connect: vi.fn().mockResolvedValue(client) }; const result = await new InventoryDirectoryReader(pool).list({ userId: "usr_salesperson", organizationId: "org_dealerflow", locationIds: ["loc_main"] }, { status: "available" }); expect(result.records).toEqual([]); expect(query.mock.calls[2]?.[0]).toContain("i.location_id = ANY($3::text[])"); expect(query.mock.calls[2]?.[1]).toEqual(["org_dealerflow", false, ["loc_main"], "", "available", 25]); });
  it("resolves the best explicitly labeled primary image for inventory cards",async()=>{const query=vi.fn<DatabaseClient["query"]>().mockResolvedValueOnce({}).mockResolvedValueOnce({}).mockResolvedValueOnce({rows:[{inventory_id:"inv_one",vehicle_id:"veh_one",location_id:"loc_main",stock_number:"N100",status:"available",list_price_cents:3895000,updated_at:new Date("2026-08-28T12:00:00Z"),vin:"1HGBH41JXMN109186",year:2027,make:"Honda",model:"CR-V",trim:"EX-L",exterior_color:"Black",media_url:"https://media.example.com/front.webp",media_alt_text:"Front view",media_source_type:"actual"}]}).mockResolvedValueOnce({});const client:DatabaseClient={query,release:vi.fn()};const pool:DatabasePool={connect:vi.fn().mockResolvedValue(client)};const result=await new InventoryDirectoryReader(pool).list({userId:"usr_inventory",organizationId:"org_dealerflow",locationIds:"all"},{});expect(result.records[0]?.primaryImage).toEqual({url:"https://media.example.com/front.webp",altText:"Front view",sourceType:"actual"});expect(query.mock.calls[2]?.[0]).toContain("is_primary DESC");expect(query.mock.calls[2]?.[0]).toContain("WHEN 'actual' THEN 0");});
  it("rejects unbounded requests and unknown statuses before database access", () => { const pool = { connect: vi.fn() } as unknown as DatabasePool; const reader = new InventoryDirectoryReader(pool); expect(() => reader.list({ userId: "usr_salesperson", organizationId: "org_dealerflow", locationIds: "all" }, { limit: 101 })).toThrow(InventoryDirectoryError); expect(() => reader.list({ userId: "usr_salesperson", organizationId: "org_dealerflow", locationIds: "all" }, { status: "mystery" })).toThrow(InventoryDirectoryError); expect(pool.connect).not.toHaveBeenCalled(); });
});
