import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { QuoteIntegrityError, QuoteService, QuoteValidationError, type QuoteLineCategory } from "@/lib/application/deals";
import { AuthorizationError } from "@/lib/platform/auth";
import { AuthenticationError, MembershipError, PostgresMembershipReader, authenticateOrganizationRequest } from "@/lib/server/auth";
import { getDatabasePool } from "@/lib/server/database";
import { PostgresQuoteProvider } from "@/lib/server/deals";
export const runtime = "nodejs"; export const dynamic = "force-dynamic"; interface Context { params: Promise<{ organizationId: string; dealId: string }> }
export async function POST(request: Request, context: Context) { try { const { organizationId, dealId } = await context.params; const body = objectValue(await request.json()); const idempotencyKey = request.headers.get("idempotency-key")?.trim(); if (!idempotencyKey) return problem(400, "invalid_request", "Idempotency-Key is required."); const purchaseType = enumValue(body.purchaseType, ["cash", "finance", "lease"] as const); if (!purchaseType) throw new QuoteValidationError(["purchaseType is invalid."]); const lines = arrayValue(body.lines).map((value, index) => { const line = objectValue(value); const category = enumValue(line.category, ["vehicle", "product", "accessory", "fee", "tax", "discount"] as const); if (!category) throw new QuoteValidationError([`lines[${index}].category is invalid.`]); return { category: category as QuoteLineCategory, description: stringValue(line.description), ...(numberValue(line.quantity) !== undefined ? { quantity: numberValue(line.quantity) } : {}), unitAmountCents: numberValue(line.unitAmountCents) ?? Number.NaN }; }); const pool = getDatabasePool(); const actor = await authenticateOrganizationRequest(request, organizationId, new PostgresMembershipReader(pool)); const result = await new QuoteService(new PostgresQuoteProvider(pool, { userId: actor.userId, organizationId })).create({ actor, organizationId, correlationId: request.headers.get("x-correlation-id")?.trim() || `req_${randomUUID()}`, idempotencyKey, dealId, purchaseType, ...(optionalString(body.currency) ? { currency: optionalString(body.currency) } : {}), ...(optionalString(body.expiresAt) ? { expiresAt: optionalString(body.expiresAt) } : {}), lines }); return NextResponse.json(result, { status: result.created ? 201 : 200, headers: { "cache-control": "no-store" } }); } catch (error) { return failure(error); } }
function objectValue(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new QuoteValidationError(["Request data must be an object."]); return value as Record<string, unknown>; } function arrayValue(value: unknown): unknown[] { if (!Array.isArray(value)) throw new QuoteValidationError(["lines must be an array."]); return value; } function stringValue(value: unknown) { return typeof value === "string" ? value : ""; } function optionalString(value: unknown) { return typeof value === "string" && value.trim() ? value : undefined; } function numberValue(value: unknown) { return typeof value === "number" ? value : undefined; } function enumValue<const V extends readonly string[]>(value: unknown, values: V): V[number] | undefined { return typeof value === "string" && values.includes(value) ? value as V[number] : undefined; }
function failure(error: unknown) { if (error instanceof SyntaxError) return problem(400, "invalid_json", "Request body must be valid JSON."); if (error instanceof AuthenticationError) return problem(401, "unauthorized", error.message); if (error instanceof MembershipError || error instanceof AuthorizationError) return problem(403, "forbidden", "Quote creation is not permitted."); if (error instanceof QuoteValidationError) return NextResponse.json({ error: "invalid_request", message: error.message, issues: error.issues }, { status: 400, headers: { "cache-control": "no-store" } }); if (error instanceof QuoteIntegrityError) return problem(409, "data_conflict", error.message); return problem(500, "internal_error", "The quote could not be created."); } function problem(status: number, error: string, message: string) { return NextResponse.json({ error, message }, { status, headers: { "cache-control": "no-store" } }); }
