"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { CarFront } from "lucide-react";

import { Button } from "@/components/ui/button";

interface InventoryRegistrationFormProps { organizationId: string; locations: readonly { id: string; name: string }[] }

export function InventoryRegistrationForm({ organizationId, locations }: InventoryRegistrationFormProps) {
  const router=useRouter();const[expanded,setExpanded]=useState(false);const[pending,setPending]=useState(false);const[message,setMessage]=useState<string>();
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const price=money(field(form,"listPrice"));if(price===undefined){setMessage("Enter a valid list price with no more than two decimal places.");return;}setPending(true);setMessage(undefined);try{const response=await fetch(`/api/organizations/${organizationId}/inventory`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":`inventory:${crypto.randomUUID()}`},body:JSON.stringify({locationId:field(form,"locationId"),stockNumber:field(form,"stockNumber"),...(price?{listPriceCents:price}:{}),vehicle:{vin:field(form,"vin"),year:Number(field(form,"year")),make:field(form,"make"),model:field(form,"model"),trim:field(form,"trim"),exteriorColor:field(form,"color")}})});if(!response.ok)throw new Error(await readProblem(response));setMessage("Inventory vehicle registered.");setExpanded(false);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Inventory could not be registered.");}finally{setPending(false);}}
  return <div className="mt-5"><Button disabled={!locations.length} onClick={()=>setExpanded((value)=>!value)} type="button" variant={expanded?"outline":"default"}><CarFront aria-hidden="true" className="size-4"/>{expanded?"Close":"Register inventory"}</Button><p aria-live="polite" className="mt-3 text-sm text-muted-foreground" role="status">{message}</p>{expanded?<section aria-labelledby="inventory-registration-heading" className="mt-3 rounded-xl border bg-card p-4 shadow-soft sm:p-5"><h2 id="inventory-registration-heading" className="font-semibold tracking-tight">Register inventory vehicle</h2><p className="mt-1 text-sm text-muted-foreground">DealerFlow reuses canonical VIN identity while creating a new dealership inventory cycle.</p><form className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3" onSubmit={submit}><label className="text-sm font-medium">Location<select className={inputClass} defaultValue={locations.length===1?locations[0]?.id:""} name="locationId" required><option value="">Select location</option>{locations.map((location)=><option key={location.id} value={location.id}>{location.name}</option>)}</select></label><Field label="Stock number" name="stockNumber" required/><Field label="VIN" maxLength={17} minLength={17} name="vin" required/><Field label="Year" max={2200} min={1886} name="year" required type="number"/><Field label="Make" name="make" required/><Field label="Model" name="model" required/><Field label="Trim" name="trim"/><Field label="Exterior color" name="color"/><Field inputMode="decimal" label="List price" name="listPrice" pattern="[0-9]+(\.[0-9]{1,2})?"/><div className="flex items-end"><Button disabled={pending} type="submit">{pending?"Registering…":"Register vehicle"}</Button></div></form></section>:null}</div>;
}
const inputClass="focus-ring mt-1 min-h-11 w-full rounded-lg border bg-background px-3 text-sm text-foreground";function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="text-sm font-medium">{label}<input className={inputClass}{...props}/></label>;}function field(form:FormData,name:string){const value=form.get(name);return typeof value==="string"?value.trim():"";}function money(value:string){if(!value)return 0;const match=/^(\d+)(?:\.(\d{1,2}))?$/.exec(value);if(!match)return undefined;const cents=Number(match[1])*100+Number((match[2]??"").padEnd(2,"0"));return Number.isSafeInteger(cents)?cents:undefined;}async function readProblem(response:Response){const payload=(await response.json().catch(()=>undefined))as{message?:unknown;issues?:unknown}|undefined;if(Array.isArray(payload?.issues)&&payload.issues.every((item)=>typeof item==="string"))return payload.issues.join(" ");return typeof payload?.message==="string"?payload.message:"The request could not be completed.";}
