"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Repeat2 } from "lucide-react";

import { Button } from "@/components/ui/button";

interface TradeWorkflowControlsProps {
  organizationId: string; customerId: string; locationId?: string; leadId?: string;
  deal?: { id: string; status: string }; tradeVehicle?: { id: string; label: string };
  appraisal?: { id: string; version: number; status: "draft" | "presented" | "accepted" | "rejected" | "expired" | "acquired"; allowanceCents: number; payoffCents: number; equityCents: number };
  canAddTrade: boolean; canAppraise: boolean;
}

export function TradeWorkflowControls({ organizationId, customerId, locationId, leadId, deal, tradeVehicle, appraisal, canAddTrade, canAppraise }: TradeWorkflowControlsProps) {
  const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState<string>();
  async function addTrade(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!locationId||!leadId)return;const f=new FormData(event.currentTarget);await send(`/api/organizations/${organizationId}/customers/${customerId}/trade-vehicle`,{locationId,leadId,vehicle:{vin:field(f,"vin"),year:Number(field(f,"year")),make:field(f,"make"),model:field(f,"model"),trim:field(f,"trim"),exteriorColor:field(f,"color")},notes:field(f,"notes")});}
  async function createAppraisal(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!deal||!tradeVehicle)return;const f=new FormData(event.currentTarget);const allowance=money(field(f,"allowance"));const payoff=money(field(f,"payoff"));if(allowance===undefined||payoff===undefined){setMessage("Enter valid allowance and payoff amounts.");return;}await send(`/api/organizations/${organizationId}/deals/${deal.id}/trade-appraisals`,{vehicleId:tradeVehicle.id,allowanceCents:allowance,payoffCents:payoff,...(field(f,"odometer")?{odometerMiles:Number(field(f,"odometer"))}:{}),conditionNotes:field(f,"conditionNotes"),lienholder:field(f,"lienholder")});}
  async function transition(toStatus:"presented"|"accepted"|"rejected"|"acquired",extra:Record<string,unknown>={}){if(!appraisal)return;await send(`/api/organizations/${organizationId}/trade-appraisals/${appraisal.id}/transitions`,{toStatus,...extra});}
  async function send(url:string,body:Record<string,unknown>){setPending(true);setMessage(undefined);try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json","idempotency-key":`trade:${crypto.randomUUID()}`},body:JSON.stringify(body)});if(!response.ok)throw new Error(await readProblem(response));setMessage("Trade workflow updated.");router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"The trade workflow could not be updated.");}finally{setPending(false);}}
  return <section aria-labelledby="trade-workflow-heading" className="rounded-xl border bg-card p-4 text-card-foreground shadow-soft sm:p-5"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-lg bg-muted"><Repeat2 aria-hidden="true" className="size-5 text-muted-foreground"/></span><div><h2 id="trade-workflow-heading" className="font-semibold tracking-tight">Trade appraisal</h2><p className="mt-1 text-sm text-muted-foreground">{appraisal?`Version ${appraisal.version} · ${appraisal.status} · ${formatMoney(appraisal.equityCents)} equity`:tradeVehicle?`${tradeVehicle.label} · Ready for appraisal`:"Capture a customer-owned vehicle before appraisal."}</p></div></div><p aria-live="polite" className="mt-3 text-sm text-muted-foreground" role="status">{message}</p>
    {!tradeVehicle&&canAddTrade&&leadId&&locationId?<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={addTrade}><Field label="VIN" maxLength={17} minLength={17} name="vin" required/><Field label="Year" min={1886} max={2200} name="year" required type="number"/><Field label="Make" name="make" required/><Field label="Model" name="model" required/><Field label="Trim" name="trim"/><Field label="Exterior color" name="color"/><Field label="Customer notes" maxLength={1000} name="notes"/><div className="flex items-end"><Button disabled={pending} type="submit">Add trade vehicle</Button></div></form>:null}
    {!tradeVehicle&&(!canAddTrade||!leadId||!locationId)?<p className="mt-3 rounded-lg border border-dashed bg-muted/30 p-3 text-sm text-muted-foreground">Trade intake requires an active Lead, dealership location, and vehicle-management permission.</p>:null}
    {tradeVehicle&&deal&&!appraisal&&canAppraise?<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={createAppraisal}><Money label="Allowance" name="allowance" required/><Money label="Payoff" name="payoff" required/><Field label="Odometer miles" min={0} name="odometer" type="number"/><Field label="Lienholder" name="lienholder"/><Field label="Condition notes" maxLength={2000} name="conditionNotes"/><div className="flex items-end"><Button disabled={pending} type="submit">Create appraisal</Button></div></form>:null}
    {tradeVehicle&&!deal?<p className="mt-3 rounded-lg border border-dashed bg-muted/30 p-3 text-sm text-muted-foreground">Create a Deal before appraising this trade.</p>:null}
    {appraisal&&canAppraise?<div className="mt-4 space-y-3">{appraisal.status==="draft"?<Button disabled={pending} onClick={()=>transition("presented")} type="button">Mark presented</Button>:null}{appraisal.status==="presented"?<><Button disabled={pending} onClick={()=>transition("accepted")} type="button">Accept appraisal</Button><form className="flex flex-col gap-3 border-t pt-3 sm:flex-row sm:items-end" onSubmit={(event)=>{event.preventDefault();const f=new FormData(event.currentTarget);void transition("rejected",{reason:field(f,"reason")});}}><Field label="Rejection reason" maxLength={1000} name="reason" required/><Button disabled={pending} type="submit" variant="outline">Reject</Button></form></>:null}{appraisal.status==="accepted"&&deal?.status==="contracted"?<form className="grid gap-3 sm:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const f=new FormData(event.currentTarget);const price=money(field(f,"listPrice"));void transition("acquired",{acquisition:{stockNumber:field(f,"stockNumber"),...(price?{listPriceCents:price}:{})}});}}><Field label="Acquired stock number" name="stockNumber" required/><Money label="Resale list price" name="listPrice"/><div className="sm:col-span-2"><Button disabled={pending} type="submit">Acquire into inventory</Button></div></form>:null}{appraisal.status==="accepted"&&deal?.status!=="contracted"?<p className="text-sm text-muted-foreground">The Deal must be contracted before acquiring this trade into inventory.</p>:null}</div>:null}
  </section>;
}
const inputClass="focus-ring mt-1 min-h-11 w-full rounded-lg border bg-background px-3 text-sm text-foreground";
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="min-w-0 text-sm font-medium">{label}<input className={inputClass}{...props}/></label>;}function Money({label,name,required}:{label:string;name:string;required?:boolean}){return <Field inputMode="decimal" label={label} name={name} pattern="[0-9]+(\.[0-9]{1,2})?" required={required}/>;}function field(form:FormData,name:string){const value=form.get(name);return typeof value==="string"?value.trim():"";}function money(value:string){if(!value)return 0;const match=/^(\d+)(?:\.(\d{1,2}))?$/.exec(value);if(!match)return undefined;const cents=Number(match[1])*100+Number((match[2]??"").padEnd(2,"0"));return Number.isSafeInteger(cents)?cents:undefined;}function formatMoney(cents:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);}async function readProblem(response:Response){const payload=(await response.json().catch(()=>undefined))as{message?:unknown;issues?:unknown}|undefined;if(Array.isArray(payload?.issues)&&payload.issues.every((item)=>typeof item==="string"))return payload.issues.join(" ");return typeof payload?.message==="string"?payload.message:"The request could not be completed.";}
