import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";

import { InventoryVehicleService, VehicleIntegrityError, VehicleValidationError } from "@/lib/application/vehicles";
import { AuthorizationError, assertAuthorized } from "@/lib/platform/auth";
import { AuthenticationError, MembershipError, PostgresMembershipReader, authenticateOrganizationRequest } from "@/lib/server/auth";
import { getDatabasePool } from "@/lib/server/database";
import { InventoryDirectoryError, InventoryDirectoryReader, PostgresVehicleProvider } from "@/lib/server/vehicles";

export const runtime = "nodejs"; export const dynamic = "force-dynamic";
interface Context { params: Promise<{ organizationId: string }> }

export async function GET(request: Request, context: Context) { try { const { organizationId } = await context.params; const pool = getDatabasePool(); const actor = await authenticateOrganizationRequest(request, organizationId, new PostgresMembershipReader(pool)); const membership = assertAuthorized(actor, { capability: "inventory.read", organizationId }); const url = new URL(request.url); const result = await new InventoryDirectoryReader(pool).list({ userId: actor.userId, organizationId, locationIds: membership.locationIds }, { ...(value(url, "q") ? { search: value(url, "q") } : {}), ...(value(url, "status") ? { status: value(url, "status") } : {}), ...(value(url, "limit") ? { limit: Number(value(url, "limit")) } : {}) }); return NextResponse.json(result, { headers: { "cache-control": "private, no-store" } }); } catch (error) { return failure(error); } }

export async function POST(request: Request, context: Context) { try { const { organizationId } = await context.params; const body = objectValue(await request.json()); const idempotencyKey = request.headers.get("idempotency-key")?.trim(); if (!idempotencyKey) return problem(400, "invalid_request", "Idempotency-Key is required."); const pool = getDatabasePool(); const actor = await authenticateOrganizationRequest(request, organizationId, new PostgresMembershipReader(pool)); const vehicle = objectValue(body.vehicle); const result = await new InventoryVehicleService(new PostgresVehicleProvider(pool, { userId: actor.userId, organizationId })).register({ actor, organizationId, locationId: stringValue(body.locationId), idempotencyKey, correlationId: request.headers.get("x-correlation-id")?.trim() || `req_${randomUUID()}`, stockNumber: stringValue(body.stockNumber), ...(numberValue(body.listPriceCents) !== undefined ? { listPriceCents: numberValue(body.listPriceCents) } : {}), vehicle: { vin: stringValue(vehicle.vin), year: numberValue(vehicle.year) ?? Number.NaN, make: stringValue(vehicle.make), model: stringValue(vehicle.model), ...(optionalString(vehicle.trim) ? { trim: optionalString(vehicle.trim) } : {}), ...(optionalString(vehicle.exteriorColor) ? { exteriorColor: optionalString(vehicle.exteriorColor) } : {}) } }); return NextResponse.json(result, { status: result.created ? 201 : 200, headers: { "cache-control": "no-store" } }); } catch (error) { return failure(error); } }

function value(url: URL, key: string) { return url.searchParams.get(key) ?? undefined; }
function objectValue(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new VehicleValidationError(["Request data must be an object."]); return value as Record<string, unknown>; }
function stringValue(value: unknown) { return typeof value === "string" ? value : ""; } function optionalString(value: unknown) { return typeof value === "string" && value.trim() ? value : undefined; } function numberValue(value: unknown) { return typeof value === "number" ? value : undefined; }
function failure(error: unknown) { if (error instanceof SyntaxError) return problem(400, "invalid_json", "Request body must be valid JSON."); if (error instanceof AuthenticationError) return problem(401, "unauthorized", error.message); if (error instanceof MembershipError || error instanceof AuthorizationError) return problem(403, "forbidden", "Inventory access is not permitted."); if (error instanceof VehicleValidationError) return NextResponse.json({ error: "invalid_request", message: error.message, issues: error.issues }, { status: 400, headers: { "cache-control": "no-store" } }); if (error instanceof InventoryDirectoryError) return problem(400, "invalid_request", error.message); if (error instanceof VehicleIntegrityError) return problem(409, "data_conflict", error.message); return problem(500, "internal_error", "Inventory could not be processed."); }
function problem(status: number, error: string, message: string) { return NextResponse.json({ error, message }, { status, headers: { "cache-control": "no-store" } }); }
