import { generateEntityId } from "@/lib/core/identifiers";
import { assertAuthorized, type AuthorizationActor } from "@/lib/platform/auth";
import type { OrganizationScope, RequestContext } from "@/lib/platform/data";

export type TaskStatus = "open" | "in-progress" | "completed" | "cancelled";
export type TaskPriority = "low" | "normal" | "high" | "urgent";
export interface TaskItem extends OrganizationScope { id:string;locationId:string;customerId:string;leadId?:string;assignedUserId?:string;title:string;status:TaskStatus;priority:TaskPriority;dueAt?:string;idempotencyKey:string }
export interface TaskStatusEvent extends OrganizationScope { id:string;taskId:string;fromStatus?:TaskStatus;toStatus:TaskStatus;reason?:string;occurredAt:string;idempotencyKey:string }
export interface TaskSession { lock(scope:OrganizationScope,key:string):Promise<void>;findByIdempotency(scope:OrganizationScope,key:string):Promise<TaskItem|null>;creationContextExists(scope:OrganizationScope,input:{customerId:string;leadId?:string;assignedUserId?:string}):Promise<boolean>;create(context:RequestContext,item:TaskItem,event:TaskStatusEvent):Promise<TaskItem>;findTransition(scope:OrganizationScope,key:string):Promise<{task:TaskItem;event:TaskStatusEvent}|null>;getForUpdate(scope:OrganizationScope,id:string):Promise<TaskItem|null>;transition(context:RequestContext,item:TaskItem,event:TaskStatusEvent):Promise<TaskItem> }
export interface TaskProvider { transaction<T>(operation:(session:TaskSession)=>Promise<T>):Promise<T> }
export class TaskValidationError extends Error { constructor(readonly issues:readonly string[]){super("Task data is invalid.");this.name="TaskValidationError";} }
export class TaskIntegrityError extends Error { constructor(message:string){super(message);this.name="TaskIntegrityError";} }
export class TaskTransitionError extends Error { constructor(from:TaskStatus,to:TaskStatus){super(`Task cannot transition from ${from} to ${to}.`);this.name="TaskTransitionError";} }

export class TaskService {
  constructor(private readonly provider:TaskProvider) {}
  async create(request:{actor:AuthorizationActor;organizationId:string;locationId:string;correlationId:string;idempotencyKey:string;customerId:string;leadId?:string;assignedUserId?:string;title:string;priority:TaskPriority;dueAt?:string}) {
    validateCreate(request); for(const capability of ["customer.read","task.read","task.create"] as const) assertAuthorized(request.actor,{capability,organizationId:request.organizationId,locationId:request.locationId});
    return this.provider.transaction(async(session)=>{await session.lock(request,request.idempotencyKey);const existing=await session.findByIdempotency(request,request.idempotencyKey);if(existing)return{task:existing,created:false};if(!await session.creationContextExists(request,{customerId:request.customerId,...(request.leadId?{leadId:request.leadId}:{}),...(request.assignedUserId?{assignedUserId:request.assignedUserId}:{})}))throw new TaskIntegrityError("Customer, Lead, assignee, or Location context is unavailable.");const occurredAt=new Date().toISOString();const task:TaskItem={id:generateEntityId("tsk"),organizationId:request.organizationId,locationId:request.locationId,customerId:request.customerId,...(request.leadId?{leadId:request.leadId}:{}),...(request.assignedUserId?{assignedUserId:request.assignedUserId}:{}),title:request.title.trim(),status:"open",priority:request.priority,...(request.dueAt?{dueAt:new Date(request.dueAt).toISOString()}:{}),idempotencyKey:request.idempotencyKey};return{task:await session.create(context(request),task,{id:generateEntityId("tse"),organizationId:request.organizationId,locationId:request.locationId,taskId:task.id,toStatus:"open",occurredAt,idempotencyKey:`create:${request.idempotencyKey}`}),created:true};});
  }
  async transition(request:{actor:AuthorizationActor;organizationId:string;correlationId:string;idempotencyKey:string;taskId:string;toStatus:"in-progress"|"completed"|"cancelled";reason?:string}) {
    validateTransition(request);assertAuthorized(request.actor,{capability:"task.read",organizationId:request.organizationId});assertAuthorized(request.actor,{capability:"task.update",organizationId:request.organizationId});return this.provider.transaction(async(session)=>{await session.lock(request,request.idempotencyKey);const existing=await session.findTransition(request,request.idempotencyKey);if(existing){authorizeLocation(request.actor,request.organizationId,existing.task.locationId);return{...existing,transitioned:false};}const current=await session.getForUpdate(request,request.taskId);if(!current)throw new TaskIntegrityError("Task is unavailable.");authorizeLocation(request.actor,request.organizationId,current.locationId);if(!allowed[current.status].includes(request.toStatus))throw new TaskTransitionError(current.status,request.toStatus);const occurredAt=new Date().toISOString();const event:TaskStatusEvent={id:generateEntityId("tse"),organizationId:request.organizationId,locationId:current.locationId,taskId:current.id,fromStatus:current.status,toStatus:request.toStatus,...(request.reason?.trim()?{reason:request.reason.trim()}:{}),occurredAt,idempotencyKey:request.idempotencyKey};return{task:await session.transition(context({...request,locationId:current.locationId}),{...current,status:request.toStatus},event),event,transitioned:true};});
  }
}
const allowed:Record<TaskStatus,readonly TaskStatus[]>={open:["in-progress","completed","cancelled"],"in-progress":["completed","cancelled"],completed:[],cancelled:[]};
function validateCreate(request:{locationId:string;customerId:string;idempotencyKey:string;title:string;priority:string;dueAt?:string}){const issues:string[]=[];for(const[field,value]of[["locationId",request.locationId],["customerId",request.customerId],["idempotencyKey",request.idempotencyKey],["title",request.title]]as const)if(!value.trim())issues.push(`${field} is required.`);if(request.title.trim().length>200)issues.push("title must not exceed 200 characters.");if(!["low","normal","high","urgent"].includes(request.priority))issues.push("priority is invalid.");if(request.dueAt&&Number.isNaN(Date.parse(request.dueAt)))issues.push("dueAt must be a valid ISO timestamp.");if(issues.length)throw new TaskValidationError(issues);}
function validateTransition(request:{taskId:string;idempotencyKey:string;toStatus:string;reason?:string}){const issues:string[]=[];if(!request.taskId.trim())issues.push("taskId is required.");if(!request.idempotencyKey.trim())issues.push("idempotencyKey is required.");if(request.toStatus==="cancelled"&&!request.reason?.trim())issues.push("reason is required to cancel a task.");if(request.reason&&request.reason.length>1000)issues.push("reason must not exceed 1000 characters.");if(issues.length)throw new TaskValidationError(issues);}
function authorizeLocation(actor:AuthorizationActor,organizationId:string,locationId:string){assertAuthorized(actor,{capability:"task.read",organizationId,locationId});assertAuthorized(actor,{capability:"task.update",organizationId,locationId});}
function context(request:{actor:AuthorizationActor;organizationId:string;correlationId:string;locationId?:string}):RequestContext{return{actorId:request.actor.userId,organizationId:request.organizationId,correlationId:request.correlationId,...(request.locationId?{locationId:request.locationId}:{})};}
