import type{Pool}from"pg";import type{ShowroomVisitEvent,ShowroomVisitProvider,ShowroomVisitRecord,ShowroomVisitSession}from"@/lib/application/visits";import{ShowroomVisitIntegrityError}from"@/lib/application/visits";import{generateEntityId}from"@/lib/core/identifiers";import type{OrganizationScope,RequestContext}from"@/lib/platform/data";import{withTenantDatabaseContext}from"@/lib/server/database";import type{SqlExecutor}from"@/lib/server/data";
export class PostgresShowroomVisitProvider implements ShowroomVisitProvider{constructor(private readonly pool:Pool,private readonly tenant:{userId:string;organizationId:string}){}transaction<T>(operation:(session:ShowroomVisitSession)=>Promise<T>){return withTenantDatabaseContext(this.pool,this.tenant,(client)=>operation(new Session(client as unknown as SqlExecutor)));}}
type Row={id:string;organization_id:string;location_id:string;customer_id:string;lead_id:string;appointment_id:string|null;assigned_user_id:string|null;status:ShowroomVisitRecord["status"];purpose:string;arrived_at:Date;started_at:Date|null;completed_at:Date|null;cancelled_at:Date|null;outcome:string|null;notes:string|null;idempotency_key:string};type EventRow={id:string;organization_id:string;visit_id:string;from_status:ShowroomVisitEvent["fromStatus"]|null;to_status:ShowroomVisitEvent["toStatus"];reason:string|null;occurred_at:Date;idempotency_key:string};
const columns="id,organization_id,location_id,customer_id,lead_id,appointment_id,assigned_user_id,status,purpose,arrived_at,started_at,completed_at,cancelled_at,outcome,notes,idempotency_key";
class Session implements ShowroomVisitSession{constructor(private readonly db:SqlExecutor){}
  async lock(scope:OrganizationScope,key:string){await this.db.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`${scope.organizationId}:${key}`]);}
  async findVisitByIdempotency(scope:OrganizationScope,key:string){const result=await this.db.query<Row>(`SELECT ${columns} FROM showroom_visits WHERE organization_id=$1 AND idempotency_key=$2 LIMIT 1`,[scope.organizationId,key]);return result.rows[0]?visit(result.rows[0]):null;}
  async creationContextExists(scope:OrganizationScope,input:{customerId:string;leadId:string;appointmentId?:string;assignedUserId?:string}){const result=await this.db.query<{exists:boolean}>(`SELECT EXISTS(SELECT 1 FROM leads l JOIN locations location ON location.organization_id=l.organization_id AND location.id=$4 AND location.active=true WHERE l.organization_id=$1 AND l.customer_id=$2 AND l.id=$3 AND l.status IN ('open','working','qualified') AND NOT EXISTS(SELECT 1 FROM showroom_visits visit WHERE visit.organization_id=l.organization_id AND visit.customer_id=l.customer_id AND visit.status IN ('checked-in','active')) AND ($5::text IS NULL OR EXISTS(SELECT 1 FROM appointments a WHERE a.organization_id=l.organization_id AND a.customer_id=l.customer_id AND a.id=$5 AND (a.location_id IS NULL OR a.location_id=$4) AND a.status IN ('scheduled','confirmed','arrived'))) AND ($6::text IS NULL OR EXISTS(SELECT 1 FROM organization_memberships m WHERE m.organization_id=l.organization_id AND m.user_id=$6 AND m.status='active'))) AS exists`,[scope.organizationId,input.customerId,input.leadId,scope.locationId??null,input.appointmentId??null,input.assignedUserId??null]);return result.rows[0]?.exists===true;}
  async create(context:RequestContext,item:ShowroomVisitRecord,statusEvent:ShowroomVisitEvent){try{await this.db.query(`INSERT INTO showroom_visits(id,organization_id,location_id,customer_id,lead_id,appointment_id,assigned_user_id,status,purpose,arrived_at,notes,idempotency_key,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13)`,[item.id,item.organizationId,item.locationId,item.customerId,item.leadId,item.appointmentId??null,item.assignedUserId??null,item.status,item.purpose,item.arrivedAt,item.notes??null,item.idempotencyKey,context.actorId]);}catch(error){if(isUniqueViolation(error))throw new ShowroomVisitIntegrityError("This customer already has an active showroom visit.");throw error;}if(item.appointmentId){const changed=await this.db.query<{from_status:"scheduled"|"confirmed"}>("WITH current AS (SELECT status FROM appointments WHERE organization_id=$1 AND id=$2 AND status IN ('scheduled','confirmed') FOR UPDATE), updated AS (UPDATE appointments appointment SET status='arrived',updated_by=$3,updated_at=now() FROM current WHERE appointment.organization_id=$1 AND appointment.id=$2 RETURNING current.status AS from_status) SELECT from_status FROM updated",[item.organizationId,item.appointmentId,context.actorId]);if(changed.rows[0])await insertAppointmentEvent(this.db,context,item.appointmentId,changed.rows[0].from_status,"arrived",`visit-arrival:${item.id}`);}await insertEvent(this.db,context,statusEvent);await audit(this.db,context,"showroom_visit.checked_in",item.id);return item;}
  async findTransition(scope:OrganizationScope,key:string){const result=await this.db.query<Row&{event_id:string;from_status:EventRow["from_status"];to_status:EventRow["to_status"];reason:string|null;occurred_at:Date;event_key:string}>(`SELECT v.*,e.id event_id,e.from_status,e.to_status,e.reason,e.occurred_at,e.idempotency_key event_key FROM showroom_visit_status_events e JOIN showroom_visits v ON v.organization_id=e.organization_id AND v.id=e.visit_id WHERE e.organization_id=$1 AND e.idempotency_key=$2 LIMIT 1`,[scope.organizationId,key]);const row=result.rows[0];return row?{visit:visit(row),event:event({id:row.event_id,organization_id:row.organization_id,visit_id:row.id,from_status:row.from_status,to_status:row.to_status,reason:row.reason,occurred_at:row.occurred_at,idempotency_key:row.event_key})}:null;}
  async getForUpdate(scope:OrganizationScope,id:string){const result=await this.db.query<Row>(`SELECT ${columns} FROM showroom_visits WHERE organization_id=$1 AND id=$2 FOR UPDATE`,[scope.organizationId,id]);return result.rows[0]?visit(result.rows[0]):null;}
  async transition(context:RequestContext,item:ShowroomVisitRecord,statusEvent:ShowroomVisitEvent){const result=await this.db.query<{id:string}>(`UPDATE showroom_visits SET status=$3,started_at=$4,completed_at=$5,cancelled_at=$6,outcome=$7,updated_by=$8,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status=$9 RETURNING id`,[item.organizationId,item.id,item.status,item.startedAt??null,item.completedAt??null,item.cancelledAt??null,item.outcome??null,context.actorId,statusEvent.fromStatus]);if(!result.rows[0])throw new ShowroomVisitIntegrityError("Concurrent showroom visit transition was rejected.");if(item.status==="completed"&&item.appointmentId){const changed=await this.db.query<{id:string}>("UPDATE appointments SET status='completed',updated_by=$3,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status='arrived' RETURNING id",[item.organizationId,item.appointmentId,context.actorId]);if(changed.rows[0])await insertAppointmentEvent(this.db,context,item.appointmentId,"arrived","completed",`visit-completed:${item.id}`);}await insertEvent(this.db,context,statusEvent);await audit(this.db,context,`showroom_visit.${item.status}`,item.id);return item;}
}
function visit(row:Row):ShowroomVisitRecord{return{id:row.id,organizationId:row.organization_id,locationId:row.location_id,customerId:row.customer_id,leadId:row.lead_id,...(row.appointment_id?{appointmentId:row.appointment_id}:{}),...(row.assigned_user_id?{assignedUserId:row.assigned_user_id}:{}),status:row.status,purpose:row.purpose,arrivedAt:row.arrived_at.toISOString(),...(row.started_at?{startedAt:row.started_at.toISOString()}:{}),...(row.completed_at?{completedAt:row.completed_at.toISOString()}:{}),...(row.cancelled_at?{cancelledAt:row.cancelled_at.toISOString()}:{}),...(row.outcome?{outcome:row.outcome}:{}),...(row.notes?{notes:row.notes}:{}),idempotencyKey:row.idempotency_key};}
function event(row:EventRow):ShowroomVisitEvent{return{id:row.id,organizationId:row.organization_id,visitId:row.visit_id,...(row.from_status?{fromStatus:row.from_status}:{}),toStatus:row.to_status,...(row.reason?{reason:row.reason}:{}),occurredAt:row.occurred_at.toISOString(),idempotencyKey:row.idempotency_key};}
async function insertEvent(db:SqlExecutor,context:RequestContext,item:ShowroomVisitEvent){await db.query("INSERT INTO showroom_visit_status_events(id,organization_id,visit_id,from_status,to_status,reason,occurred_at,idempotency_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[item.id,item.organizationId,item.visitId,item.fromStatus??null,item.toStatus,item.reason??null,item.occurredAt,item.idempotencyKey,context.actorId]);}
async function insertAppointmentEvent(db:SqlExecutor,context:RequestContext,appointmentId:string,fromStatus:string,toStatus:string,idempotencyKey:string){await db.query("INSERT INTO appointment_status_events(id,organization_id,appointment_id,from_status,to_status,idempotency_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)",[generateEntityId("ase"),context.organizationId,appointmentId,fromStatus,toStatus,idempotencyKey,context.actorId]);}
async function audit(db:SqlExecutor,context:RequestContext,action:string,id:string){await db.query("INSERT INTO audit_logs(id,organization_id,actor_id,action,entity_type,entity_id,source,correlation_id) VALUES($1,$2,$3,$4,'showroom_visit',$5,'application',$6)",[generateEntityId("aud"),context.organizationId,context.actorId,action,id,context.correlationId]);}
function isUniqueViolation(error:unknown):boolean{return typeof error==="object"&&error!==null&&"code" in error&&(error as{code?:unknown}).code==="23505";}
