import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { DealIntegrityError, DealService, DealValidationError } from "@/lib/application/deals";
import { AuthorizationError, assertAuthorized } from "@/lib/platform/auth";
import { AuthenticationError, MembershipError, PostgresMembershipReader, authenticateOrganizationRequest } from "@/lib/server/auth";
import { getDatabasePool } from "@/lib/server/database";
import { DealDirectoryError, DealDirectoryReader, PostgresDealProvider } from "@/lib/server/deals";

export const runtime = "nodejs"; export const dynamic = "force-dynamic"; interface Context { params: Promise<{ organizationId: string }> }
export async function GET(request: Request, context: Context) { try { const { organizationId } = await context.params; const pool = getDatabasePool(); const actor = await authenticateOrganizationRequest(request, organizationId, new PostgresMembershipReader(pool)); const membership = assertAuthorized(actor, { capability: "deal.read", organizationId }); const url = new URL(request.url); const result = await new DealDirectoryReader(pool).list({ userId: actor.userId, organizationId, locationIds: membership.locationIds }, { ...(url.searchParams.get("q") ? { search: url.searchParams.get("q")! } : {}), ...(url.searchParams.get("status") ? { status: url.searchParams.get("status")! } : {}), ...(url.searchParams.get("limit") ? { limit: Number(url.searchParams.get("limit")) } : {}) }); return NextResponse.json(result, { headers: { "cache-control": "private, no-store" } }); } catch (error) { return failure(error); } }
export async function POST(request: Request, context: Context) { try { const { organizationId } = await context.params; const body = objectValue(await request.json()); const idempotencyKey = request.headers.get("idempotency-key")?.trim(); if (!idempotencyKey) return problem(400, "invalid_request", "Idempotency-Key is required."); const pool = getDatabasePool(); const actor = await authenticateOrganizationRequest(request, organizationId, new PostgresMembershipReader(pool)); const purchaseType = optionalEnum(body.purchaseType, ["cash", "finance", "lease"] as const); const result = await new DealService(new PostgresDealProvider(pool, { userId: actor.userId, organizationId })).create({ actor, organizationId, locationId: stringValue(body.locationId), correlationId: request.headers.get("x-correlation-id")?.trim() || `req_${randomUUID()}`, idempotencyKey, customerId: stringValue(body.customerId), leadId: stringValue(body.leadId), primaryVehicleId: stringValue(body.primaryVehicleId), ...(optionalString(body.inventoryUnitId) ? { inventoryUnitId: optionalString(body.inventoryUnitId) } : {}), ...(optionalString(body.ownerUserId) ? { ownerUserId: optionalString(body.ownerUserId) } : {}), ...(purchaseType ? { purchaseType } : {}), ...(numberValue(body.agreedPriceCents) !== undefined ? { agreedPriceCents: numberValue(body.agreedPriceCents) } : {}) }); return NextResponse.json(result, { status: result.created ? 201 : 200, headers: { "cache-control": "no-store" } }); } catch (error) { return failure(error); } }
function objectValue(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new DealValidationError(["Request data must be an object."]); return value as Record<string, unknown>; } function stringValue(value: unknown) { return typeof value === "string" ? value : ""; } function optionalString(value: unknown) { return typeof value === "string" && value.trim() ? value : undefined; } function numberValue(value: unknown) { return typeof value === "number" ? value : undefined; } function optionalEnum<const V extends readonly string[]>(value: unknown, values: V): V[number] | undefined { if (value === undefined || value === null || value === "") return undefined; if (typeof value === "string" && values.includes(value)) return value as V[number]; throw new DealValidationError(["purchaseType is invalid."]); }
function failure(error: unknown) { if (error instanceof SyntaxError) return problem(400, "invalid_json", "Request body must be valid JSON."); if (error instanceof AuthenticationError) return problem(401, "unauthorized", error.message); if (error instanceof MembershipError || error instanceof AuthorizationError) return problem(403, "forbidden", "Deal access is not permitted."); if (error instanceof DealValidationError) return NextResponse.json({ error: "invalid_request", message: error.message, issues: error.issues }, { status: 400, headers: { "cache-control": "no-store" } }); if (error instanceof DealDirectoryError) return problem(400, "invalid_request", error.message); if (error instanceof DealIntegrityError) return problem(409, "data_conflict", error.message); return problem(500, "internal_error", "Deals could not be processed."); } function problem(status: number, error: string, message: string) { return NextResponse.json({ error, message }, { status, headers: { "cache-control": "no-store" } }); }
