import type { Pool } from "pg";
import { generateEntityId } from "@/lib/core/identifiers";
import { assertAuthorized, type AuthorizationActor } from "@/lib/platform/auth";
import { withTenantDatabaseContext } from "@/lib/server/database";

export type ConversationKind="direct"|"group"|"department"|"record";
export type ReferenceType="customer"|"lead"|"deal"|"quote"|"vehicle"|"inventory"|"appointment"|"document";
export interface TeamMember{id:string;name:string;email:string}
export interface ConversationSummary{id:string;kind:ConversationKind;name:string;locationId?:string;participants:readonly TeamMember[];lastMessage?:string;lastMessageAt?:string;unreadCount:number}
export interface TeamMessage{id:string;body:string;kind:"text"|"system"|"record";sender:TeamMember;createdAt:string;references:readonly {id:string;type:ReferenceType;entityId:string;label:string;href:string}[]}
export class TeamCommunicationError extends Error{constructor(message:string,readonly kind:"validation"|"conflict"|"not-found"="validation"){super(message);this.name="TeamCommunicationError";}}

export class TeamCommunicationService{
  constructor(private readonly pool:Pool){}
  async directory(actor:AuthorizationActor,organizationId:string){assertAuthorized(actor,{capability:"team_chat.read",organizationId});return withTenantDatabaseContext(this.pool,{userId:actor.userId,organizationId},async client=>{const result=await client.query(`SELECT DISTINCT u.id,u.display_name name,u.email FROM organization_memberships m JOIN users u ON u.id=m.user_id AND u.active=true WHERE m.organization_id=$1 AND m.status='active' ORDER BY u.display_name,u.id`,[organizationId])as{rows:Array<{id:string;name:string;email:string}>};return result.rows;});}
  async list(actor:AuthorizationActor,organizationId:string):Promise<readonly ConversationSummary[]>{assertAuthorized(actor,{capability:"team_chat.read",organizationId});return withTenantDatabaseContext(this.pool,{userId:actor.userId,organizationId},async client=>{const result=await client.query(`SELECT c.id,c.kind,c.name,c.location_id,COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id',u.id,'name',u.display_name,'email',u.email)) FILTER(WHERE u.id IS NOT NULL),'[]') participants,last.body last_message,last.created_at last_message_at,(SELECT count(*)::int FROM team_messages unread WHERE unread.organization_id=c.organization_id AND unread.conversation_id=c.id AND unread.sender_user_id<>$2 AND unread.created_at>COALESCE(me.last_read_at,'epoch')) unread_count FROM team_conversations c JOIN team_conversation_participants me ON me.organization_id=c.organization_id AND me.conversation_id=c.id AND me.user_id=$2 LEFT JOIN team_conversation_participants p ON p.organization_id=c.organization_id AND p.conversation_id=c.id LEFT JOIN users u ON u.id=p.user_id LEFT JOIN LATERAL(SELECT body,created_at FROM team_messages m WHERE m.organization_id=c.organization_id AND m.conversation_id=c.id ORDER BY created_at DESC,id DESC LIMIT 1) last ON true WHERE c.organization_id=$1 AND c.archived_at IS NULL GROUP BY c.id,me.last_read_at,last.body,last.created_at ORDER BY last.created_at DESC NULLS LAST,c.updated_at DESC`,[organizationId,actor.userId])as{rows:Array<{id:string;kind:ConversationKind;name:string|null;location_id:string|null;participants:TeamMember[];last_message:string|null;last_message_at:Date|null;unread_count:number}>};return result.rows.map(row=>({id:row.id,kind:row.kind,name:row.name??directName(row.participants,actor.userId),participants:row.participants,unreadCount:row.unread_count,...(row.location_id?{locationId:row.location_id}:{}),...(row.last_message?{lastMessage:row.last_message}:{}) ,...(row.last_message_at?{lastMessageAt:row.last_message_at.toISOString()}:{})}));});}
  async messages(actor:AuthorizationActor,organizationId:string,conversationId:string):Promise<readonly TeamMessage[]>{assertAuthorized(actor,{capability:"team_chat.read",organizationId});validId(conversationId,"cnv","conversation");return withTenantDatabaseContext(this.pool,{userId:actor.userId,organizationId},async client=>{const result=await client.query(`SELECT m.id,m.body,m.kind,m.created_at,u.id sender_id,u.display_name sender_name,u.email sender_email,COALESCE(jsonb_agg(jsonb_build_object('id',r.id,'type',r.entity_type,'entityId',r.entity_id,'label',r.label,'href',r.href)) FILTER(WHERE r.id IS NOT NULL),'[]') refs FROM team_messages m JOIN users u ON u.id=m.sender_user_id LEFT JOIN team_message_references r ON r.organization_id=m.organization_id AND r.message_id=m.id WHERE m.organization_id=$1 AND m.conversation_id=$2 GROUP BY m.id,u.id ORDER BY m.created_at,m.id LIMIT 200`,[organizationId,conversationId])as{rows:Array<{id:string;body:string;kind:TeamMessage["kind"];created_at:Date;sender_id:string;sender_name:string;sender_email:string;refs:TeamMessage["references"]}>};return result.rows.map(row=>({id:row.id,body:row.body,kind:row.kind,createdAt:row.created_at.toISOString(),sender:{id:row.sender_id,name:row.sender_name,email:row.sender_email},references:row.refs}));});}
  async markRead(actor:AuthorizationActor,organizationId:string,conversationId:string){assertAuthorized(actor,{capability:"team_chat.read",organizationId});validId(conversationId,"cnv","conversation");return withTenantDatabaseContext(this.pool,{userId:actor.userId,organizationId},async client=>{const result=await client.query("UPDATE team_conversation_participants SET last_read_at=now() WHERE organization_id=$1 AND conversation_id=$2 AND user_id=$3 RETURNING conversation_id",[organizationId,conversationId,actor.userId])as{rows:Array<{conversation_id:string}>};if(!result.rows[0])throw new TeamCommunicationError("Conversation was not found.","not-found");return{updated:true};});}
  async create(actor:AuthorizationActor,input:{organizationId:string;kind:ConversationKind;name?:string;locationId?:string;participantUserIds:readonly string[];idempotencyKey:string}){const membership=assertAuthorized(actor,{capability:"team_chat.write",organizationId:input.organizationId,...(input.locationId?{locationId:input.locationId}:{})});const participants=[...new Set([actor.userId,...input.participantUserIds])];if(!input.idempotencyKey.trim()||input.idempotencyKey.length>200)throw new TeamCommunicationError("A valid idempotency key is required.");if(!["direct","group","department","record"].includes(input.kind))throw new TeamCommunicationError("Conversation type is invalid.");if(input.kind==="direct"&&participants.length!==2)throw new TeamCommunicationError("A direct conversation requires exactly two participants.");if(input.kind!=="direct"&&(!input.name?.trim()||input.name.trim().length>120))throw new TeamCommunicationError("A group conversation name is required.");if(participants.length<2||participants.length>100)throw new TeamCommunicationError("Choose between 2 and 100 participants.");return withTenantDatabaseContext(this.pool,{userId:actor.userId,organizationId:input.organizationId},async client=>{const existing=await client.query("SELECT id FROM team_conversations WHERE organization_id=$1 AND idempotency_key=$2",[input.organizationId,input.idempotencyKey])as{rows:Array<{id:string}>};if(existing.rows[0])return{id:existing.rows[0].id,created:false};const all=membership.locationIds==="all";const eligible=await client.query(`SELECT u.id FROM organization_memberships m JOIN users u ON u.id=m.user_id AND u.active=true WHERE m.organization_id=$1 AND m.status='active' AND u.id=ANY($2::text[]) AND ($3::text IS NULL OR m.all_locations OR EXISTS(SELECT 1 FROM membership_locations ml WHERE ml.organization_id=m.organization_id AND ml.membership_id=m.id AND ml.location_id=$3))`,[input.organizationId,participants,input.locationId??null])as{rows:Array<{id:string}>};if(eligible.rows.length!==participants.length)throw new TeamCommunicationError("One or more participants are unavailable in this organization or Location.","conflict");if(input.locationId&&!all&&!membership.locationIds.includes(input.locationId))throw new TeamCommunicationError("Location access is required.","not-found");const id=generateEntityId("cnv");await client.query("INSERT INTO team_conversations(id,organization_id,location_id,kind,name,created_by,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7)",[id,input.organizationId,input.locationId??null,input.kind,input.kind==="direct"?null:input.name!.trim(),actor.userId,input.idempotencyKey]);for(const userId of participants)await client.query("INSERT INTO team_conversation_participants(organization_id,conversation_id,user_id,role) VALUES($1,$2,$3,$4)",[input.organizationId,id,userId,userId===actor.userId?"owner":"member"]);return{id,created:true};});}
  async send(actor:AuthorizationActor,input:{organizationId:string;conversationId:string;body:string;idempotencyKey:string;reference?:{type:ReferenceType;entityId:string;label:string;href:string}}){assertAuthorized(actor,{capability:"team_chat.write",organizationId:input.organizationId});validId(input.conversationId,"cnv","conversation");const body=input.body.trim();if(!body||body.length>4000)throw new TeamCommunicationError("Messages must contain 1 to 4,000 characters.");if(!input.idempotencyKey.trim()||input.idempotencyKey.length>200)throw new TeamCommunicationError("A valid idempotency key is required.");if(input.reference&&!validReference(input.reference,input.organizationId))throw new TeamCommunicationError("The shared DealerFlow record is invalid.");if(input.reference)assertAuthorized(actor,{capability:referenceCapability[input.reference.type],organizationId:input.organizationId});return withTenantDatabaseContext(this.pool,{userId:actor.userId,organizationId:input.organizationId},async client=>{const prior=await client.query("SELECT id FROM team_messages WHERE organization_id=$1 AND conversation_id=$2 AND idempotency_key=$3",[input.organizationId,input.conversationId,input.idempotencyKey])as{rows:Array<{id:string}>};if(prior.rows[0])return{id:prior.rows[0].id,created:false};if(input.reference){const target=await client.query(referenceSql[input.reference.type],[input.organizationId,input.reference.entityId])as{rows:Array<{location_id:string|null}>};if(!target.rows[0])throw new TeamCommunicationError("The shared record is unavailable.","not-found");if(target.rows[0].location_id)assertAuthorized(actor,{capability:referenceCapability[input.reference.type],organizationId:input.organizationId,locationId:target.rows[0].location_id});}const id=generateEntityId("msg");await client.query("INSERT INTO team_messages(id,organization_id,conversation_id,sender_user_id,body,kind,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7)",[id,input.organizationId,input.conversationId,actor.userId,body,input.reference?"record":"text",input.idempotencyKey]);if(input.reference)await client.query("INSERT INTO team_message_references(id,organization_id,message_id,entity_type,entity_id,label,href) VALUES($1,$2,$3,$4,$5,$6,$7)",[generateEntityId("mrf"),input.organizationId,id,input.reference.type,input.reference.entityId,input.reference.label.trim(),input.reference.href]);await client.query("UPDATE team_conversations SET updated_at=now() WHERE organization_id=$1 AND id=$2",[input.organizationId,input.conversationId]);return{id,created:true};});}
}
function directName(participants:readonly TeamMember[],current:string){return participants.find(item=>item.id!==current)?.name??"Direct conversation";}
function validId(value:string,prefix:string,label:string){if(!new RegExp(`^${prefix}_[a-z0-9_-]{6,64}$`).test(value))throw new TeamCommunicationError(`A valid ${label} is required.`);}
function validReference(value:{type:ReferenceType;entityId:string;label:string;href:string},organizationId:string){return ["customer","lead","deal","quote","vehicle","inventory","appointment","document"].includes(value.type)&&/^[a-z]{3}_[a-z0-9_-]{6,64}$/.test(value.entityId)&&value.label.trim().length>0&&value.label.trim().length<=200&&value.href.startsWith(`/organizations/${organizationId}/`);}
const referenceCapability={customer:"customer.read",lead:"lead.read",deal:"deal.read",quote:"quote.read",vehicle:"inventory.read",inventory:"inventory.read",appointment:"appointment.read",document:"document.read"}as const;
const referenceSql:Record<ReferenceType,string>={customer:"SELECT location_id FROM customers WHERE organization_id=$1 AND id=$2",lead:"SELECT location_id FROM leads WHERE organization_id=$1 AND id=$2",deal:"SELECT location_id FROM deals WHERE organization_id=$1 AND id=$2",quote:"SELECT d.location_id FROM deal_quotes q JOIN deals d ON d.organization_id=q.organization_id AND d.id=q.deal_id WHERE q.organization_id=$1 AND q.id=$2",vehicle:"SELECT location_id FROM vehicles WHERE organization_id=$1 AND id=$2",inventory:"SELECT location_id FROM inventory_units WHERE organization_id=$1 AND id=$2",appointment:"SELECT location_id FROM appointments WHERE organization_id=$1 AND id=$2",document:"SELECT d.location_id FROM deal_document_requirements r JOIN deals d ON d.organization_id=r.organization_id AND d.id=r.deal_id WHERE r.organization_id=$1 AND r.id=$2"};
