import { AppShell } from "@/components/app-shell";
import { TeamCommunicationsWorkspace } from "@/components/team-communications/TeamCommunicationsWorkspace";
import { TeamCommunicationService } from "@/lib/server/team-communications";
import { loadDirectoryContext } from "../_lib/load-directory-context";

export const dynamic="force-dynamic";
export default async function CommunicationsPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{conversation?:string;new?:string}>}){
  const{organizationId}=await params;const query=await searchParams;const context=await loadDirectoryContext(organizationId,"team_chat.read");const service=new TeamCommunicationService(context.pool);const conversations=await service.list(context.actor,organizationId);const selectedId=query.new==="1"?undefined:conversations.some(item=>item.id===query.conversation)?query.conversation:conversations[0]?.id;const messages=selectedId?await service.messages(context.actor,organizationId,selectedId):[];const members=await service.directory(context.actor,organizationId);const required=["appointment.create","appointment.read","customer.read","lead.read","task.read","task.create"]as const;const appointmentContexts=required.every(capability=>context.membership.capabilities.includes(capability))?await service.appointmentContexts(context.actor,organizationId):[];const shareableRecords=await service.shareableCommercialRecords(context.actor,organizationId,{quotes:context.membership.capabilities.includes("quote.read"),documents:context.membership.capabilities.includes("document.read")});
  return <AppShell organizationId={organizationId} navigationCapabilities={context.membership.capabilities} activeHref={`/organizations/${organizationId}/communications`} breadcrumbs={[{label:context.organization.name},{label:"Communications"}]} user={{name:context.session.user.name,email:context.session.user.email,...(context.session.user.image?{image:context.session.user.image}:{})}}><section className="mx-auto max-w-7xl" aria-labelledby="communications-heading"><div className="mb-5"><p className="text-sm font-semibold text-primary">DealerFlow Communications</p><h1 className="mt-1 text-2xl font-semibold tracking-tight" id="communications-heading">Your dealership, connected</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Direct, team, and department conversations stay connected to authorized DealerFlow work.</p></div><TeamCommunicationsWorkspace organizationId={organizationId} currentUserId={context.actor.userId} conversations={conversations} members={members} selectedId={selectedId} messages={messages} canWrite={context.membership.capabilities.includes("team_chat.write")} appointmentContexts={appointmentContexts} shareableRecords={shareableRecords}/></section></AppShell>;
}
