import { headers } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { RoleWorkspace } from "@/components/workspaces/RoleWorkspace";
import { getAuth, PostgresMembershipReader, resolveAuthorizationActor } from "@/lib/server/auth";
import { getDatabasePool } from "@/lib/server/database";
import { OrganizationDirectory, resolveWorkspaceProfiles, RoleWorkspaceReader } from "@/lib/server/organizations";

export const dynamic="force-dynamic";
interface Props{params:Promise<{organizationId:string}>;searchParams:Promise<{view?:string}>}
export default async function OrganizationWorkspacePage({params,searchParams}:Props){const{organizationId}=await params,{view}=await searchParams;const session=await getAuth().api.getSession({headers:await headers()});if(!session)redirect("/login");const pool=getDatabasePool(),reader=new PostgresMembershipReader(pool);const actor=await resolveAuthorizationActor(session.user.id,organizationId,reader);const membership=actor.memberships[0];if(!membership)notFound();const organization=(await new OrganizationDirectory(pool).listForUser(session.user.id)).find(item=>item.id===organizationId);if(!organization)notFound();const resolved=resolveWorkspaceProfiles(membership,view);const profile=resolved.active;const model=profile?.moduleAvailable?await new RoleWorkspaceReader(pool).read({userId:session.user.id,organizationId,membership,profile}):undefined;const activeHref=`/organizations/${organizationId}/workspace`;return <AppShell organizationId={organizationId} navigationCapabilities={membership.capabilities} activeHref={activeHref} breadcrumbs={[{label:organization.name},{label:profile?.label??"Workspace"}]} user={{name:session.user.name,email:session.user.email,...(session.user.image?{image:session.user.image}:{})}}>{profile?<RoleWorkspace capabilities={membership.capabilities} model={model} organizationId={organizationId} organizationName={organization.name} profile={profile} profiles={resolved.available}/>:<section aria-labelledby="workspace-heading" className="mx-auto max-w-4xl rounded-xl border border-dashed bg-muted/20 p-8 text-center"><h1 className="font-semibold" id="workspace-heading">No operational workspace assigned</h1><p className="mt-2 text-sm text-muted-foreground">Your active membership has no enabled workspace capability. Contact a tenant administrator.</p></section>}</AppShell>}
