import { ArrowRight, BrainCircuit, Gauge, MessagesSquare, Smartphone, Users } from "lucide-react";
import { MarketingShell, CtaLink, FeatureCard, PageHero, SectionHeading } from "@/components/marketing/MarketingShell";

export const metadata = { title: "DealerFlow | Intelligent dealership operations", description: "DealerFlow connects customer workflow, inventory, communications, management visibility, and explainable AI in one dealership operating platform.", alternates: { canonical: "/" } };

const story = ["A lead arrives", "The right salesperson acts", "The customer timeline stays current", "The vehicle and deal stay connected", "Managers see exceptions", "DealerFlow AI explains the next best action"];

export default function HomePage() {
  return <MarketingShell><PageHero eyebrow="DealerFlow operating system" title="Run the dealership from one intelligent workspace." description="Connect customer workflow, inventory, communications, deal progress, and management visibility—without burying your team in CRM clutter." primary={{href:"/book-demo",label:"Book a demo"}} secondary={{href:"/product",label:"See how it works"}}><div className="grid gap-3 rounded-2xl border bg-card p-4 shadow-soft sm:grid-cols-2"><Metric label="Today’s focus" value="12 priority actions"/><Metric label="Customer momentum" value="7 moving forward"/><Metric label="Inventory exceptions" value="3 need attention"/><Metric label="Manager visibility" value="Live and explainable"/></div></PageHero><section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:py-24"><SectionHeading eyebrow="One connected story" title="From first signal to lasting relationship" description="DealerFlow keeps context connected as work moves across roles, devices, and departments."/><ol className="mt-10 grid gap-3 md:grid-cols-3" aria-label="DealerFlow workflow">{story.map((item,index)=><li className="rounded-xl border bg-card p-5 shadow-soft" key={item}><span className="text-xs font-semibold text-primary">0{index+1}</span><p className="mt-3 font-medium">{item}</p></li>)}</ol></section><section className="border-y bg-muted/40"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:py-24"><SectionHeading eyebrow="Built for the operating day" title="Clarity for every dealership role"/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><FeatureCard icon={Users} title="Role-specific workspaces">Sales, BDC, managers, and inventory teams see the work relevant to them.</FeatureCard><FeatureCard icon={BrainCircuit} title="Explainable AI">Recommendations include confidence and supporting evidence—not hidden reasoning.</FeatureCard><FeatureCard icon={MessagesSquare} title="Connected communication">Customer context remains attached to the relationship and authorized team.</FeatureCard><FeatureCard icon={Gauge} title="Management visibility">Surface exceptions and next actions without turning every screen into a dashboard.</FeatureCard><FeatureCard icon={Smartphone} title="Phone-first execution">Responsive workflows support the showroom, lot, desk, and road.</FeatureCard><FeatureCard icon={ArrowRight} title="One operating flow">Customer, vehicle, deal, and follow-up context move together.</FeatureCard></div></div></section><FinalCta/></MarketingShell>;
}

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-muted p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>}
function FinalCta(){return <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:py-24"><div className="rounded-2xl bg-foreground px-6 py-10 text-background sm:px-10"><p className="text-sm font-semibold text-primary">See DealerFlow in context</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight">A focused operating system for the way dealerships actually work.</h2><div className="mt-7"><CtaLink href="/book-demo">Book a demo <ArrowRight className="size-4" aria-hidden="true"/></CtaLink></div></div></section>}
