import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { Brand } from "@/components/app-shell/brand";
import { PrintQuoteButton } from "@/components/customer/PrintQuoteButton";
import { QuoteDocumentReader } from "@/lib/server/deals";
import { loadDirectoryContext } from "../../../_lib/load-directory-context";

export const metadata: Metadata = { title: "Purchase proposal", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

export default async function PrintableQuotePage({ params }: { params: Promise<{ organizationId: string; quoteId: string }> }) {
  const { organizationId, quoteId } = await params;
  const context = await loadDirectoryContext(organizationId, "deal.read");
  const document = await new QuoteDocumentReader(context.pool).read({ userId: context.session.user.id, organizationId, locationIds: context.membership.locationIds }, quoteId);
  if (!document) notFound();
  const money = (value: number) => formatMoney(value, document.quote.currency);

  return <main className="min-h-dvh bg-muted/30 p-4 print:bg-white print:p-0 sm:p-8">
    <div className="mx-auto mb-4 flex max-w-4xl items-center justify-between gap-3 print:hidden">
      <Link className="focus-ring rounded-lg px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground" href={`/organizations/${organizationId}/customers/${document.customer.id}`}>← Back to Customer</Link>
      <PrintQuoteButton />
    </div>
    <article aria-labelledby="proposal-heading" className="mx-auto max-w-4xl rounded-xl border bg-card p-5 text-card-foreground shadow-soft print:max-w-none print:rounded-none print:border-0 print:bg-white print:p-0 print:text-black print:shadow-none sm:p-8 lg:p-10">
      <header className="flex flex-col gap-6 border-b pb-6 sm:flex-row sm:items-start sm:justify-between">
        <div><Brand name={context.configuration.brand.productName} /><p className="mt-3 text-sm font-medium">{context.configuration.brand.organizationName}</p><p className="text-sm text-muted-foreground">{document.location.name}</p></div>
        <div className="sm:text-right"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary print:text-black">Purchase proposal</p><h1 className="mt-1 text-2xl font-semibold" id="proposal-heading">Quote #{document.deal.dealNumber}</h1><p className="mt-1 text-sm text-muted-foreground">Version {document.quote.version} · <span className="capitalize">{document.quote.status}</span></p><p className="text-sm text-muted-foreground">Created {date(document.quote.createdAt)}</p></div>
      </header>
      <section aria-labelledby="proposal-for" className="grid gap-5 border-b py-6 sm:grid-cols-2"><div><h2 className="text-xs font-semibold uppercase text-muted-foreground" id="proposal-for">Prepared for</h2><p className="mt-2 font-medium">{document.customer.displayName}</p></div><div><h2 className="text-xs font-semibold uppercase text-muted-foreground">Vehicle</h2><p className="mt-2 font-medium">{document.vehicle.label}</p><p className="text-sm text-muted-foreground">VIN {document.vehicle.vin}{document.vehicle.stockNumber ? ` · Stock ${document.vehicle.stockNumber}` : ""}</p></div></section>
      <section aria-labelledby="proposal-details" className="py-6"><div className="flex items-end justify-between"><h2 className="font-semibold" id="proposal-details">Proposal details</h2><p className="text-sm capitalize text-muted-foreground">{document.quote.purchaseType} purchase</p></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[34rem] text-left text-sm"><thead className="border-y bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-3 py-2" scope="col">Description</th><th className="px-3 py-2 text-right" scope="col">Quantity</th><th className="px-3 py-2 text-right" scope="col">Unit amount</th><th className="px-3 py-2 text-right" scope="col">Total</th></tr></thead><tbody className="divide-y">{document.lines.map((line) => <tr key={line.id}><th className="px-3 py-3 font-medium" scope="row">{line.description}<span className="block text-xs font-normal capitalize text-muted-foreground">{line.category}</span></th><td className="px-3 py-3 text-right">{line.quantity}</td><td className="px-3 py-3 text-right">{money(line.unitAmountCents)}</td><td className="px-3 py-3 text-right font-medium">{money(line.totalCents)}</td></tr>)}</tbody></table></div><dl className="ml-auto mt-5 max-w-sm space-y-2 text-sm"><Total label="Subtotal" value={money(document.quote.subtotalCents)} /><Total label="Fees" value={money(document.quote.feeCents)} /><Total label="Estimated taxes" value={money(document.quote.taxCents)} /><Total label="Discounts" value={money(document.quote.discountCents)} /><Total label="Proposal total" value={money(document.quote.totalCents)} /></dl></section>
      {document.commercialTerms ? <section aria-labelledby="proposal-terms" className="border-t py-6"><h2 className="font-semibold" id="proposal-terms">Purchase terms</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Term label="Trade allowance" value={money(document.commercialTerms.tradeAllowanceCents)} /><Term label="Trade payoff" value={money(document.commercialTerms.tradePayoffCents)} /><Term label="Trade equity" value={money(document.commercialTerms.tradeEquityCents)} /><Term label="Cash down" value={money(document.commercialTerms.cashDownCents)} />{document.commercialTerms.amountFinancedCents !== undefined ? <Term label="Amount financed" value={money(document.commercialTerms.amountFinancedCents)} /> : null}{document.financeTerms ? <><Term label="APR" value={`${(document.financeTerms.aprBasisPoints / 100).toFixed(2)}%`} /><Term label="Term" value={`${document.financeTerms.termMonths} months`} /><Term label="Estimated payment" value={`${money(document.financeTerms.estimatedPaymentCents)}/month`} /></> : null}</dl></section> : null}
      {document.leaseTerms ? <section aria-labelledby="proposal-lease-terms" className="border-t py-6"><h2 className="font-semibold" id="proposal-lease-terms">Lease terms</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Term label="Adjusted cap cost" value={money(document.leaseTerms.adjustedCapCostCents)} /><Term label="Residual value" value={money(document.leaseTerms.residualValueCents)} /><Term label="Term" value={`${document.leaseTerms.termMonths} months`} />{document.leaseTerms.annualMileage ? <Term label="Annual mileage" value={`${document.leaseTerms.annualMileage.toLocaleString("en-US")} miles`} /> : null}<Term label="Acquisition fee" value={money(document.leaseTerms.acquisitionFeeCents)} /><Term label="Cap cost reduction" value={money(document.leaseTerms.capCostReductionCents)} /><Term label="Rebate" value={money(document.leaseTerms.rebateCents)} /><Term label="Estimated base payment" value={`${money(document.leaseTerms.basePaymentCents)}/month`} /></dl><p className="mt-4 text-xs text-muted-foreground">Taxes and jurisdiction-specific lease charges are not inferred. This is not a lender approval or final lease agreement.</p></section> : null}
      {document.verifiedIncentives.length ? <section aria-labelledby="verified-incentives" className="border-t py-6"><h2 className="font-semibold" id="verified-incentives">Verified incentives</h2><ul className="mt-3 space-y-2">{document.verifiedIncentives.map((item) => <li className="flex justify-between gap-4 text-sm" key={item.code}><span>{item.name}</span><span>{money(item.amountCents)}</span></li>)}</ul></section> : null}
      <footer className="border-t pt-5 text-xs leading-5 text-muted-foreground"><p>This proposal reflects the saved DealerFlow Quote version shown above. Taxes and fees are estimates unless otherwise identified, and this document is not a financing approval or final retail installment contract.</p>{document.quote.status === "draft" ? <p className="mt-2 font-medium text-foreground">Draft — this proposal has not been marked as presented.</p> : null}</footer>
    </article>
  </main>;
}

function Total({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-6"><dt className="text-muted-foreground">{label}</dt><dd className="tabular-nums">{value}</dd></div>; }
function Term({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border p-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium tabular-nums">{value}</dd></div>; }
function date(value: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(value)); }
function formatMoney(cents: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(cents / 100); }
