import type { LucideIcon } from "lucide-react";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const links=[{href:"/product",label:"Product"},{href:"/ai-product",label:"AI"},{href:"/integrations",label:"Integrations"},{href:"/security",label:"Security"},{href:"/pricing",label:"Pricing"}];

export function MarketingShell({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-background"><a className="focus-ring sr-only z-50 rounded bg-background p-3 focus:not-sr-only focus:fixed focus:left-3 focus:top-3" href="#main">Skip to content</a><header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-6xl flex-wrap items-center gap-x-5 gap-y-2 px-4 py-3 sm:px-6"><Link className="focus-ring mr-auto rounded-md text-base font-semibold tracking-tight" href="/">DealerFlow</Link><nav aria-label="Primary" className="order-3 flex w-full gap-1 overflow-x-auto sm:order-none sm:w-auto">{links.map(link=><Link className="focus-ring whitespace-nowrap rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground" href={link.href} key={link.href}>{link.label}</Link>)}</nav><Link className="focus-ring rounded-md px-3 py-2 text-sm font-medium" href="/login">Login</Link><Link className={cn(buttonVariants({size:"sm"}),"hidden sm:inline-flex")} href="/book-demo">Book a demo</Link></div></header><main id="main">{children}</main><footer className="border-t"><div className="mx-auto grid max-w-6xl gap-8 px-4 py-10 text-sm sm:grid-cols-2 sm:px-6"><div><p className="font-semibold">DealerFlow</p><p className="mt-2 max-w-md text-muted-foreground">Modern automotive retail operations with focused workflows and explainable intelligence.</p></div><nav aria-label="Footer" className="flex flex-wrap content-start gap-x-5 gap-y-3 sm:justify-end"><Link href="/security">Security</Link><Link href="/contact">Contact</Link><span className="text-muted-foreground">Privacy and terms pending approved legal content.</span></nav></div></footer></div>}

export function PageHero({eyebrow,title,description,primary,secondary,children}:{eyebrow:string;title:string;description:string;primary?:{href:string;label:string};secondary?:{href:string;label:string};children?:React.ReactNode}){return <section className="mx-auto grid max-w-6xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-24"><div><p className="text-sm font-semibold text-primary">{eyebrow}</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{description}</p>{primary?<div className="mt-8 flex flex-wrap gap-3"><CtaLink href={primary.href}>{primary.label}<ArrowRight className="size-4" aria-hidden="true"/></CtaLink>{secondary?<CtaLink href={secondary.href} variant="outline">{secondary.label}</CtaLink>:null}</div>:null}</div>{children?<div>{children}</div>:null}</section>}
export function CtaLink({href,variant="default",children}:{href:string;variant?:"default"|"outline";children:React.ReactNode}){return <Link className={buttonVariants({variant})} href={href}>{children}</Link>}
export function SectionHeading({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}){return <div className="max-w-2xl">{eyebrow?<p className="text-sm font-semibold text-primary">{eyebrow}</p>:null}<h2 className="mt-3 text-3xl font-semibold tracking-tight">{title}</h2>{description?<p className="mt-4 leading-7 text-muted-foreground">{description}</p>:null}</div>}
export function FeatureCard({icon:Icon,title,children}:{icon:LucideIcon;title:string;children:React.ReactNode}){return <article className="rounded-xl border bg-card p-5 shadow-soft"><Icon className="size-5 text-primary" aria-hidden="true"/><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{children}</p></article>}
