import Link from "next/link";
import { AlertCircle, ArrowRight, CheckCircle2, Lightbulb, Sparkles } from "lucide-react";
import type { OperatingBrief as OperatingBriefModel } from "@/lib/application/ai";

export function OperatingBrief({brief,compact=false}:{brief:OperatingBriefModel;compact?:boolean}) {
  return <section aria-labelledby="operating-brief-heading" className="overflow-hidden rounded-xl border bg-card shadow-soft">
    <header className="border-b p-4 sm:p-5"><div className="flex items-center gap-2"><Sparkles aria-hidden="true" className="size-5 text-primary"/><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">DealerFlow intelligence</p></div><h2 className="mt-2 text-lg font-semibold" id="operating-brief-heading">{brief.title}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{brief.summary}</p></header>
    {brief.primaryRecommendation?<div className="border-b bg-muted/20 p-4 sm:p-5"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground"><Lightbulb aria-hidden="true" className="size-4"/></span><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Recommendation</p><p className="mt-1 font-medium">{brief.primaryRecommendation.title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{brief.primaryRecommendation.detail}</p>{brief.primaryRecommendation.href?<Link className="focus-ring mt-3 inline-flex min-h-11 items-center gap-2 rounded-lg border bg-background px-3 text-sm font-medium hover:bg-muted" href={brief.primaryRecommendation.href}>Open supporting record<ArrowRight aria-hidden="true" className="size-4"/></Link>:null}</div></div></div>:null}
    <div className={compact?"p-4 sm:p-5":"grid gap-0 lg:grid-cols-2"}><section aria-labelledby="brief-facts" className={compact?"":"p-4 sm:p-5"}><h3 className="flex items-center gap-2 text-sm font-semibold" id="brief-facts"><CheckCircle2 aria-hidden="true" className="size-4 text-muted-foreground"/>Verified facts</h3>{brief.facts.length?<ul className="mt-3 space-y-2" role="list">{brief.facts.map(item=><li key={item.id}>{item.href?<Link className="focus-ring flex min-h-11 items-center justify-between gap-3 rounded-lg border p-3 hover:bg-muted/30" href={item.href}><span><span className="block text-sm font-medium">{item.title}</span><span className="mt-1 block text-xs text-muted-foreground">{item.detail}</span></span><ArrowRight aria-hidden="true" className="size-4 shrink-0 text-muted-foreground"/></Link>:<span className="block rounded-lg border p-3 text-sm">{item.title}</span>}</li>)}</ul>:<p className="mt-3 text-sm text-muted-foreground">No authorized operating metrics are available.</p>}</section>{!compact&&brief.unknowns.length?<section aria-labelledby="brief-unknowns" className="border-t p-4 lg:border-l lg:border-t-0 sm:p-5"><h3 className="flex items-center gap-2 text-sm font-semibold" id="brief-unknowns"><AlertCircle aria-hidden="true" className="size-4 text-muted-foreground"/>Unknown or unavailable</h3><ul className="mt-3 space-y-3" role="list">{brief.unknowns.map(item=><li className="rounded-lg border border-dashed p-3" key={item.id}><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.detail}</p></li>)}</ul></section>:null}</div>
    <footer className="border-t px-4 py-3 text-xs text-muted-foreground sm:px-5">Facts come from authorized DealerFlow records. Recommendations are guidance, not automatic actions. Generated {new Date(brief.generatedAt).toLocaleString("en-US")}.</footer>
  </section>;
}
