import { AppShell } from "@/components/app-shell";
import { VehicleCatalogReadinessReader } from "@/lib/server/vehicles";
import { loadDirectoryContext } from "../../_lib/load-directory-context";

export const dynamic="force-dynamic";
export default async function CatalogHealthPage({params}:{params:Promise<{organizationId:string}>}) {
  const {organizationId}=await params; const context=await loadDirectoryContext(organizationId,"inventory.read"); const snapshot=await new VehicleCatalogReadinessReader(context.pool).read();
  return <AppShell organizationId={organizationId} navigationCapabilities={context.membership.capabilities} activeHref={`/organizations/${organizationId}/inventory`} breadcrumbs={[{label:context.organization.name},{label:"Inventory"},{label:"Catalog health"}]} user={{name:context.session.user.name,email:context.session.user.email,...(context.session.user.image?{image:context.session.user.image}:{})}}><main className="mx-auto max-w-7xl space-y-8"><header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Vehicle Intelligence</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Catalog readiness</h1><p className="mt-1 text-sm text-muted-foreground">Read-only operational health for the latest accepted governed release.</p></header><section aria-labelledby="counts-heading"><h2 id="counts-heading" className="text-lg font-semibold">Projected records</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(snapshot.counts).map(([label,value])=><Metric key={label} label={label} value={value}/>)}</dl></section><section aria-labelledby="readiness-heading"><h2 id="readiness-heading" className="text-lg font-semibold">Readiness distribution</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(snapshot.readiness).map(([label,value])=><Metric key={label} label={label} value={value}/>)}</dl></section><p className="text-xs text-muted-foreground">Release {snapshot.releaseId??"Unavailable"} · source revision {snapshot.sourceRevision??"Unavailable"}</p></main></AppShell>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-card p-4 shadow-soft"><dt className="text-sm capitalize text-muted-foreground">{label.replaceAll("-"," ")}</dt><dd className="mt-2 text-2xl font-semibold tabular-nums">{value.toLocaleString()}</dd></div>;}
