import { describe,expect,it,vi } from "vitest";
import { AIProviderError,OpenAIRecommendationGateway } from "./openai-recommendation-gateway";
const evidence=[{id:"appointment:apt_123",category:"appointment" as const,observation:"Appointment confirmed.",observedAt:"2026-08-25T12:00:00Z"}];
const output={primaryAction:"Confirm appointment",rationale:"Appointment is confirmed.",evidenceIds:["appointment:apt_123"],confidence:90,urgency:"high",timeHorizon:"Today",risks:[],opportunities:[],supportingActions:[]};
describe("OpenAIRecommendationGateway",()=>{
  it("uses Responses structured output without provider storage",async()=>{const request=vi.fn<typeof fetch>().mockResolvedValue(Response.json({id:"resp_123",model:"gpt-5.6",status:"completed",output:[{type:"message",content:[{type:"output_text",text:JSON.stringify(output)}]}],usage:{input_tokens:50,output_tokens:25}}));const now=vi.fn().mockReturnValueOnce(1000).mockReturnValueOnce(1120);const result=await new OpenAIRecommendationGateway({apiKey:"secret",model:"gpt-5.6",fetch:request,now}).generate({evidence,idempotencyKey:"air_run123",promptVersion:"customer-next-action-v1"});expect(result.recommendation?.evidenceIds).toEqual(["appointment:apt_123"]);const body=JSON.parse(String(request.mock.calls[0]?.[1]?.body));expect(body.store).toBe(false);expect(body.text.format).toMatchObject({type:"json_schema",strict:true});expect(body.input[0].content).toContain("Do not reveal chain-of-thought");});
  it("returns explicit refusals without manufacturing a recommendation",async()=>{const request=vi.fn<typeof fetch>().mockResolvedValue(Response.json({id:"resp_refusal",model:"gpt-5.6",status:"completed",output:[{type:"message",content:[{type:"refusal",refusal:"Unable to assist."}]}]}));const result=await new OpenAIRecommendationGateway({apiKey:"secret",model:"gpt-5.6",fetch:request}).generate({evidence,idempotencyKey:"air_run123",promptVersion:"customer-next-action-v1"});expect(result.refusal).toBe("Unable to assist.");expect(result.recommendation).toBeUndefined();});
  it("sanitizes provider HTTP failures",async()=>{const request=vi.fn<typeof fetch>().mockResolvedValue(new Response("sensitive provider detail",{status:429}));await expect(new OpenAIRecommendationGateway({apiKey:"secret",model:"gpt-5.6",fetch:request}).generate({evidence,idempotencyKey:"air_run123",promptVersion:"customer-next-action-v1"})).rejects.toEqual(new AIProviderError("provider-http-429"));});
});
