import type { Metadata } from "next";
import { headers } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { TenantRuntimeProvider } from "@/components/app-shell/tenant-runtime";
import { getAuth, PostgresMembershipReader, resolveAuthorizationActor } from "@/lib/server/auth";
import { getDatabasePool } from "@/lib/server/database";
import { PostgresTenantConfigurationProvider } from "@/lib/server/organizations";
import { createTenantBrandTokens } from "@/lib/platform/tenant";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{organizationId:string}>}):Promise<Metadata>{const{organizationId}=await params;const session=await getAuth().api.getSession({headers:await headers()});if(!session)return{};try{const pool=getDatabasePool();const actor=await resolveAuthorizationActor(session.user.id,organizationId,new PostgresMembershipReader(pool));if(!actor.memberships.length)return{};const configuration=(await new PostgresTenantConfigurationProvider(pool).read({actorId:session.user.id,organizationId})).configuration;return{title:{default:configuration.brand.productName,template:`%s · ${configuration.brand.productName}`},...(configuration.brand.faviconUrl?{icons:{icon:configuration.brand.faviconUrl}}:{})};}catch{return{};}}
export default async function OrganizationLayout({children,params}:{children:React.ReactNode;params:Promise<{organizationId:string}>}){const{organizationId}=await params;const session=await getAuth().api.getSession({headers:await headers()});if(!session)redirect("/login");const pool=getDatabasePool();const actor=await resolveAuthorizationActor(session.user.id,organizationId,new PostgresMembershipReader(pool));if(!actor.memberships.length)notFound();const configuration=(await new PostgresTenantConfigurationProvider(pool).read({actorId:session.user.id,organizationId})).configuration;return <TenantRuntimeProvider value={{productName:configuration.brand.productName,...(configuration.brand.logoUrl?{logoUrl:configuration.brand.logoUrl}:{}),...(configuration.brand.logoDarkUrl?{logoDarkUrl:configuration.brand.logoDarkUrl}:{}),features:configuration.features,brandTokens:createTenantBrandTokens(configuration.brand.colors)}}>{children}</TenantRuntimeProvider>}
