import Link from "next/link";
import { AlertTriangle, ArrowRight, Bot, CalendarDays, CheckCircle2, Gauge, Sparkles } from "lucide-react";
import type { Capability } from "@/lib/platform/auth";
import type { RoleWorkspaceModel, WorkspaceProfile } from "@/lib/server/organizations";

interface Props { organizationId:string; organizationName:string; profile:WorkspaceProfile; profiles:readonly WorkspaceProfile[]; model?:RoleWorkspaceModel; capabilities:readonly Capability[] }

export function RoleWorkspace({organizationId,organizationName,profile,profiles,model,capabilities}:Props){const base=`/organizations/${organizationId}`;return <section aria-labelledby="workspace-heading" className="mx-auto max-w-7xl">
  <header className="flex flex-col gap-4 border-b pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{profile.eyebrow}</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl" id="workspace-heading">{profile.label}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground"><span className="font-medium text-foreground">{organizationName}:</span> {profile.question}</p></div>{profiles.length>1?<form className="w-full sm:w-auto"><label className="text-xs font-medium text-muted-foreground">Workspace view<select className="focus-ring mt-1 block h-11 w-full rounded-lg border bg-background px-3 text-sm text-foreground sm:min-w-56" defaultValue={profile.key} name="view">{profiles.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label><button className="focus-ring mt-2 h-10 w-full rounded-lg border bg-background px-4 text-sm font-medium hover:bg-muted">Switch view</button></form>:null}</header>
  {!profile.moduleAvailable?<ModuleUnavailable profile={profile}/>:model?<div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><div className="space-y-6"><Queue icon={AlertTriangle} title="Priorities" description="Work requiring attention now." items={model.priorities} empty={emptyPriority(profile)}/><Queue icon={CalendarDays} title="Today" description="Appointments and commitments due today." items={model.today} empty="No scheduled work requires attention today."/><Queue icon={CheckCircle2} title="Exceptions" description="Items outside the normal workflow." items={model.exceptions} empty="No role-specific exceptions are currently in scope."/></div><aside aria-label="Workspace context" className="space-y-6"><Metrics model={model}/><AiContext profile={profile}/><QuickActions base={base} capabilities={capabilities}/></aside></div>:null}
</section>}

function Queue({icon:Icon,title,description,items,empty}:{icon:typeof AlertTriangle;title:string;description:string;items:RoleWorkspaceModel["priorities"];empty:string}){return <section aria-labelledby={`queue-${title.toLowerCase()}`} className="overflow-hidden rounded-xl border bg-card shadow-soft"><div className="flex items-start gap-3 border-b p-4 sm:p-5"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-muted"><Icon aria-hidden="true" className="size-5 text-muted-foreground"/></span><div><h2 className="font-semibold" id={`queue-${title.toLowerCase()}`}>{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div>{items.length?<ul className="divide-y" role="list">{items.map(item=><li key={item.id}><Link className="focus-ring flex min-h-16 items-center justify-between gap-3 p-4 hover:bg-muted/30 sm:px-5" href={item.href}><span className="min-w-0"><span className="block truncate text-sm font-medium">{item.label}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{item.detail}</span></span><ArrowRight aria-hidden="true" className="size-4 shrink-0 text-muted-foreground"/></Link></li>)}</ul>:<p className="p-6 text-sm text-muted-foreground">{empty}</p>}</section>}
function Metrics({model}:{model:RoleWorkspaceModel}){return <section aria-labelledby="role-kpis" className="rounded-xl border bg-card p-4 shadow-soft sm:p-5"><div className="flex items-center gap-2"><Gauge aria-hidden="true" className="size-5 text-muted-foreground"/><h2 className="font-semibold" id="role-kpis">Role KPIs</h2></div><ul className="mt-4 space-y-4" role="list">{model.metrics.map(metric=><li key={metric.label}><Link className="focus-ring block rounded-lg border p-3 hover:bg-muted/30" href={metric.href}><span className="text-xs font-medium text-muted-foreground">{metric.label}</span><strong className="mt-1 block text-2xl">{metric.value}</strong><span className="mt-1 block text-xs text-muted-foreground">{metric.definition}</span></Link></li>)}</ul><p className="mt-3 text-[11px] text-muted-foreground">Verified from authorized operational records.</p></section>}
function AiContext({profile}:{profile:WorkspaceProfile}){return <section aria-labelledby="role-ai" className="rounded-xl border bg-card p-4 shadow-soft sm:p-5"><div className="flex items-center gap-2"><Sparkles aria-hidden="true" className="size-5 text-primary"/><h2 className="font-semibold" id="role-ai">DealerFlow AI</h2></div><p className="mt-3 text-sm text-muted-foreground">AI context is prepared for the {profile.label} view and remains limited to authorized records. Role-aware recommendations arrive in Batch 5.</p><div className="mt-3 flex items-center gap-2 rounded-lg border border-dashed bg-muted/20 p-3 text-xs text-muted-foreground"><Bot aria-hidden="true" className="size-4"/>No autonomous actions are enabled.</div></section>}
function QuickActions({base,capabilities}:{base:string;capabilities:readonly Capability[]}){const allowed=(capability:Capability)=>capabilities.includes(capability);const actions=[...(allowed("lead.create")?[{label:"Create Lead",href:`${base}/leads`}]:[]),...(allowed("customer.read")?[{label:"Find Customer",href:`${base}/customers`}]:[]),...(allowed("deal.read")?[{label:"Review Deals",href:`${base}/deals`}]:[]),...(allowed("inventory.read")?[{label:"Open Inventory",href:`${base}/inventory`}]:[]),...(allowed("reports.view")?[{label:"View Reports",href:`${base}/reports`}]:[])];return <section aria-labelledby="quick-actions" className="rounded-xl border bg-card p-4 shadow-soft sm:p-5"><h2 className="font-semibold" id="quick-actions">Quick Actions</h2><div className="mt-3 grid gap-2">{actions.slice(0,4).map(action=><Link className="focus-ring flex min-h-11 items-center justify-between rounded-lg border px-3 text-sm font-medium hover:bg-muted" href={action.href} key={action.label}>{action.label}<ArrowRight aria-hidden="true" className="size-4"/></Link>)}</div></section>}
function ModuleUnavailable({profile}:{profile:WorkspaceProfile}){return <section aria-labelledby="module-unavailable" className="mt-6 rounded-xl border border-dashed bg-muted/20 p-8 text-center"><h2 className="font-semibold" id="module-unavailable">Service module not yet enabled</h2><p className="mx-auto mt-2 max-w-xl text-sm text-muted-foreground">{profile.label} is recognized, but DealerFlow will not fabricate service queues before authoritative service workflows are implemented.</p></section>}
function emptyPriority(profile:WorkspaceProfile){if(profile.audience==="individual")return"You’re caught up. No follow-ups are overdue.";if(profile.audience==="inventory")return"All available vehicles have actual inventory photos.";if(profile.audience==="finance")return"No Deals currently require finance review.";if(profile.audience==="team")return"No Leads or follow-ups currently require team intervention.";return"No urgent work is currently in scope."}
