import type { DatabasePool } from "@/lib/server/database";
import { withTenantDatabaseContext } from "@/lib/server/database";

export type ReportWindowDays=7|30|90;
export interface ManagementReport{windowDays:ReportWindowDays;generatedAt:string;metrics:{newLeads:number;deliveredDeals:number;deliveredRevenueCents:number;appointmentsCompleted:number;appointmentsNoShow:number;overdueTasks:number};leadFunnel:readonly{status:string;count:number}[];leadSources:readonly{source:string;count:number;deliveredDeals:number}[]}
export class ManagementReportQueryError extends Error{}
export class ManagementReportReader{
  constructor(private readonly pool:DatabasePool){}
  async read(scope:{userId:string;organizationId:string;locationIds:readonly string[]|"all"},windowDays:ReportWindowDays):Promise<ManagementReport>{if(![7,30,90].includes(windowDays))throw new ManagementReportQueryError("Reporting window must be 7, 30, or 90 days.");return withTenantDatabaseContext(this.pool,{userId:scope.userId,organizationId:scope.organizationId},async(client)=>{const all=scope.locationIds==="all";const locations=all?[]:scope.locationIds;const values=[scope.organizationId,all,locations,windowDays];const metrics=await client.query(`SELECT
        (SELECT count(*) FROM leads WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND created_at>=now()-make_interval(days=>$4))::int new_leads,
        (SELECT count(*) FROM deals d JOIN deal_status_events event ON event.organization_id=d.organization_id AND event.deal_id=d.id AND event.to_status='delivered' WHERE d.organization_id=$1 AND ($2 OR d.location_id=ANY($3::text[])) AND event.occurred_at>=now()-make_interval(days=>$4))::int delivered_deals,
        (SELECT COALESCE(sum(d.agreed_price_cents),0) FROM deals d JOIN deal_status_events event ON event.organization_id=d.organization_id AND event.deal_id=d.id AND event.to_status='delivered' WHERE d.organization_id=$1 AND ($2 OR d.location_id=ANY($3::text[])) AND event.occurred_at>=now()-make_interval(days=>$4))::bigint delivered_revenue_cents,
        (SELECT count(*) FROM appointments WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status='completed' AND updated_at>=now()-make_interval(days=>$4))::int appointments_completed,
        (SELECT count(*) FROM appointments WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status='no-show' AND updated_at>=now()-make_interval(days=>$4))::int appointments_no_show,
        (SELECT count(*) FROM tasks WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status IN ('open','in-progress') AND due_at<now())::int overdue_tasks`,values) as {rows:Array<{new_leads:number;delivered_deals:number;delivered_revenue_cents:string;appointments_completed:number;appointments_no_show:number;overdue_tasks:number}>};
      const funnel=await client.query("SELECT status::text,count(*)::int count FROM leads WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND created_at>=now()-make_interval(days=>$4) GROUP BY status ORDER BY count(*) DESC,status",values) as {rows:Array<{status:string;count:number}>};
      const sources=await client.query(`SELECT l.source,count(DISTINCT l.id)::int count,count(DISTINCT d.id) FILTER(WHERE event.id IS NOT NULL)::int delivered_deals FROM leads l LEFT JOIN deals d ON d.organization_id=l.organization_id AND d.lead_id=l.id LEFT JOIN deal_status_events event ON event.organization_id=d.organization_id AND event.deal_id=d.id AND event.to_status='delivered' AND event.occurred_at>=now()-make_interval(days=>$4) WHERE l.organization_id=$1 AND ($2 OR l.location_id=ANY($3::text[])) AND l.created_at>=now()-make_interval(days=>$4) GROUP BY l.source ORDER BY count(DISTINCT l.id) DESC,l.source LIMIT 10`,values) as {rows:Array<{source:string;count:number;delivered_deals:number}>};const row=metrics.rows[0]!;const revenue=Number(row.delivered_revenue_cents);if(!Number.isSafeInteger(revenue))throw new ManagementReportQueryError("Reported revenue exceeds the supported range.");return{windowDays,generatedAt:new Date().toISOString(),metrics:{newLeads:row.new_leads,deliveredDeals:row.delivered_deals,deliveredRevenueCents:revenue,appointmentsCompleted:row.appointments_completed,appointmentsNoShow:row.appointments_no_show,overdueTasks:row.overdue_tasks},leadFunnel:funnel.rows,leadSources:sources.rows.map(item=>({source:item.source,count:item.count,deliveredDeals:item.delivered_deals}))};});}
}
