import { describe, expect, it, vi } from "vitest";
import { ImportBatchService, ImportBatchValidationError, type ImportBatch, type ImportBatchProvider } from "./import-batch";

const actor = { userId: "usr_admin001", memberships: [{ organizationId: "org_dealer001", locationIds: "all" as const, capabilities: ["organization.configure" as const] }] };
function provider(existing: ImportBatch | null = null) { return { findByIdempotencyKey: vi.fn().mockResolvedValue(existing), create: vi.fn(async (batch: ImportBatch) => batch), commit: vi.fn().mockResolvedValue({batchId:"imb_batch001",status:"completed",appliedRows:1,entityCounts:{customer:1,lead:1},completedAt:"2026-09-01T12:00:00.000Z"}), reverse: vi.fn().mockResolvedValue({batchId:"imb_batch001",status:"reversed",appliedRows:1,entityCounts:{customer:1,lead:1},completedAt:"2026-09-01T13:00:00.000Z"}) } satisfies ImportBatchProvider; }
const valid = { actor, organizationId: "org_dealer001", domain: "customer-lead" as const, sourceName: "pilot-customers.csv", sourceChecksum: "a".repeat(64), mapping: { Name: "displayName", Email: "email", Location: "locationId" }, rows: [{ Name: "Jordan Lee", Email: "jordan@example.com", Location: "loc_main001" }], idempotencyKey: "pilot-import-1" };

describe("ImportBatchService", () => {
  it("persists a clean preview as ready", async () => { const target = provider(); const result = await new ImportBatchService(target, () => new Date("2026-08-31T12:00:00Z")).stage(valid); expect(result).toMatchObject({ status: "ready", createdBy: actor.userId, preview: { validRows: 1 } }); expect(target.create).toHaveBeenCalledOnce(); });
  it("quarantines duplicate and unresolved rows for review", async () => { const target = provider(); const result = await new ImportBatchService(target).stage({ ...valid, existingIdentityKeys: new Set(["customer:email:jordan@example.com"]) }); expect(result.status).toBe("review-required"); expect(result.preview.duplicateRows).toBe(1); });
  it("returns the prior batch for the same tenant idempotency key", async () => { const prior = { id: "imb_existing1", organizationId: valid.organizationId } as ImportBatch; const target = provider(prior); expect(await new ImportBatchService(target).stage(valid)).toBe(prior); expect(target.create).not.toHaveBeenCalled(); });
  it("rejects unbounded or unverifiable sources before persistence", async () => { await expect(new ImportBatchService(provider()).stage({ ...valid, sourceChecksum: "unknown", rows: [] })).rejects.toBeInstanceOf(ImportBatchValidationError); });
  it("requires exact commit confirmation and delegates a tenant-scoped idempotent commit",async()=>{const target=provider();const service=new ImportBatchService(target);await expect(service.commit({actor,organizationId:valid.organizationId,batchId:"imb_batch001",idempotencyKey:"commit-1",confirmation:"yes"})).rejects.toBeInstanceOf(ImportBatchValidationError);await service.commit({actor,organizationId:valid.organizationId,batchId:"imb_batch001",idempotencyKey:"commit-1",confirmation:"COMMIT imb_batch001"});expect(target.commit).toHaveBeenCalledWith({organizationId:valid.organizationId,batchId:"imb_batch001",actorId:actor.userId,idempotencyKey:"commit-1"});});
  it("requires exact reversal confirmation and a bounded reason",async()=>{const target=provider();const service=new ImportBatchService(target);await expect(service.reverse({actor,organizationId:valid.organizationId,batchId:"imb_batch001",idempotencyKey:"reverse-1",confirmation:"REVERSE imb_batch001",reason:"short"})).rejects.toBeInstanceOf(ImportBatchValidationError);await service.reverse({actor,organizationId:valid.organizationId,batchId:"imb_batch001",idempotencyKey:"reverse-1",confirmation:"REVERSE imb_batch001",reason:"Pilot dry-run reversal"});expect(target.reverse).toHaveBeenCalledWith(expect.objectContaining({batchId:"imb_batch001",reason:"Pilot dry-run reversal"}));});
});
