export const importDomains=["customer-lead","inventory","user"]as const;export type ImportDomain=typeof importDomains[number];
export type ImportValue=string|number|boolean|null|undefined;export type ImportSourceRow=Readonly<Record<string,ImportValue>>;
export interface ImportPreviewIssue{code:"missing"|"invalid"|"unknown-field"|"duplicate"|"needs-review";field?:string;message:string}
export interface ImportPreviewRow{rowNumber:number;status:"valid"|"rejected"|"duplicate"|"needs-review";canonical:Readonly<Record<string,string|number|boolean>>;issues:readonly ImportPreviewIssue[]}
export interface ImportPreview{domain:ImportDomain;totalRows:number;validRows:number;rejectedRows:number;duplicateRows:number;unresolvedRows:number;rows:readonly ImportPreviewRow[]}
const fields:Record<ImportDomain,readonly string[]>={"customer-lead":["sourceId","displayName","email","phone","leadSource","assignedEmployeeId","vehicleInterest","status","createdAt"],inventory:["sourceId","vin","stockNumber","year","make","model","trim","priceCents","mileage","status","locationId","mediaUrl","mediaSourceType"],user:["sourceId","name","email","employeeId","locationId","department","roleKey","active"]};
export function previewImport(input:{domain:ImportDomain;rows:readonly ImportSourceRow[];mapping:Readonly<Record<string,string>>;existingIdentityKeys?:ReadonlySet<string>;approvedRoleKeys?:ReadonlySet<string>}):ImportPreview{
  const allowed=new Set(fields[input.domain]),seen=new Set<string>(),unknown=Object.entries(input.mapping).filter(([,target])=>!allowed.has(target));
  const rows=input.rows.map((source,index)=>{const canonical:Record<string,string|number|boolean>={};const issues:ImportPreviewIssue[]=unknown.map(([field])=>({code:"unknown-field",field,message:`${field} maps to an unsupported canonical field.`}));for(const[sourceField,target]of Object.entries(input.mapping)){const value=source[sourceField];if(allowed.has(target)&&value!==null&&value!==undefined&&String(value).trim()!=="")canonical[target]=typeof value==="string"?value.trim():value;}
    normalize(canonical);validate(input.domain,canonical,issues,input.approvedRoleKeys);const keys=identities(input.domain,canonical);if(keys.some(key=>seen.has(key)||input.existingIdentityKeys?.has(key)))issues.push({code:"duplicate",message:"The row matches an existing or earlier identity and requires duplicate review."});keys.forEach(key=>seen.add(key));const status=issues.some(issue=>issue.code==="duplicate")?"duplicate":issues.some(issue=>issue.code==="missing"||issue.code==="invalid"||issue.code==="unknown-field")?"rejected":issues.length?"needs-review":"valid";return{rowNumber:index+1,status,canonical,issues}as const;});
  return{domain:input.domain,totalRows:rows.length,validRows:rows.filter(row=>row.status==="valid").length,rejectedRows:rows.filter(row=>row.status==="rejected").length,duplicateRows:rows.filter(row=>row.status==="duplicate").length,unresolvedRows:rows.filter(row=>row.status==="needs-review").length,rows};
}
function normalize(row:Record<string,string|number|boolean>){if(typeof row.email==="string")row.email=row.email.toLowerCase();if(typeof row.phone==="string")row.phone=row.phone.replace(/[\s().-]/g,"");if(typeof row.vin==="string")row.vin=row.vin.toUpperCase();}
function validate(domain:ImportDomain,row:Readonly<Record<string,string|number|boolean>>,issues:ImportPreviewIssue[],roles?:ReadonlySet<string>){const required=domain==="customer-lead"?["displayName"]:domain==="inventory"?["stockNumber","year","make","model","locationId"]:["name","email","locationId","roleKey"];for(const field of required)if(!row[field])issues.push({code:"missing",field,message:`${field} is required.`});if(row.email&&!(typeof row.email==="string"&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(row.email)))issues.push({code:"invalid",field:"email",message:"email is invalid."});if(row.phone&&!(typeof row.phone==="string"&&/^\+[1-9]\d{7,14}$/.test(row.phone)))issues.push({code:"invalid",field:"phone",message:"phone must use E.164 format."});if(row.vin&&!(typeof row.vin==="string"&&/^[A-HJ-NPR-Z0-9]{17}$/.test(row.vin)))issues.push({code:"invalid",field:"vin",message:"vin must be a valid 17-character VIN."});if(domain==="inventory"&&!row.vin)issues.push({code:"needs-review",field:"vin",message:"VIN was not supplied; the physical unit requires review and VIN must not be fabricated."});if(domain==="user"&&typeof row.roleKey==="string"&&!roles?.has(row.roleKey))issues.push({code:"needs-review",field:"roleKey",message:"Role mapping requires explicit approval."});}
function identities(domain:ImportDomain,row:Readonly<Record<string,string|number|boolean>>){const values:string[]=[];if(row.sourceId)values.push(`${domain}:source:${row.sourceId}`);if(domain==="customer-lead"){if(row.email)values.push(`customer:email:${row.email}`);if(row.phone)values.push(`customer:phone:${row.phone}`)}if(domain==="inventory"){if(row.vin)values.push(`inventory:vin:${row.vin}`);if(row.stockNumber&&row.locationId)values.push(`inventory:stock:${row.locationId}:${row.stockNumber}`)}if(domain==="user"&&row.email)values.push(`user:email:${row.email}`);return values;}

