import{describe,expect,it,vi}from"vitest";import type{AuthorizationActor}from"@/lib/platform/auth";import{ShowroomVisitService,ShowroomVisitTransitionError,ShowroomVisitValidationError,type ShowroomVisitEvent,type ShowroomVisitProvider,type ShowroomVisitRecord,type ShowroomVisitSession}from"./manage-showroom-visit";
const actor:AuthorizationActor={userId:"usr_sales01",memberships:[{organizationId:"org_dealerflow",locationIds:["loc_main01"],capabilities:["customer.read","lead.read","appointment.read","appointment.create","appointment.update"]}]};
class MemorySession implements ShowroomVisitSession{visit?:ShowroomVisitRecord;events:ShowroomVisitEvent[]=[];lock=vi.fn(async()=>{});creationContextExists=vi.fn(async()=>true);async findVisitByIdempotency(_scope:unknown,key:string){return this.visit?.idempotencyKey===key?this.visit:null;}async create(_context:unknown,visit:ShowroomVisitRecord,event:ShowroomVisitEvent){this.visit=visit;this.events.push(event);return visit;}async findTransition(_scope:unknown,key:string){const event=this.events.find((item)=>item.idempotencyKey===key);return event&&this.visit?{visit:this.visit,event}:null;}async getForUpdate(){return this.visit??null;}async transition(_context:unknown,visit:ShowroomVisitRecord,event:ShowroomVisitEvent){this.visit=visit;this.events.push(event);return visit;}}
function service(session:MemorySession){const provider:ShowroomVisitProvider={transaction:async(operation)=>operation(session)};return new ShowroomVisitService(provider);}
const checkIn={actor,organizationId:"org_dealerflow",locationId:"loc_main01",correlationId:"req_visit01",idempotencyKey:"visit:checkin-01",customerId:"cus_customer01",leadId:"led_buycycle01",appointmentId:"apt_testdrive01",purpose:"Scheduled test drive"};
describe("ShowroomVisitService",()=>{
  it("checks in once and preserves idempotency",async()=>{const session=new MemorySession();const first=await service(session).checkIn(checkIn);const second=await service(session).checkIn(checkIn);expect(first.created).toBe(true);expect(second.created).toBe(false);expect(session.events).toHaveLength(1);expect(session.visit?.status).toBe("checked-in");});
  it("moves through active to completed with a required outcome",async()=>{const session=new MemorySession();await service(session).checkIn(checkIn);const started=await service(session).transition({actor,organizationId:"org_dealerflow",correlationId:"req_start01",idempotencyKey:"visit:start-01",visitId:session.visit!.id,toStatus:"active"});expect(started.visit.startedAt).toBeTruthy();const completed=await service(session).transition({actor,organizationId:"org_dealerflow",correlationId:"req_complete01",idempotencyKey:"visit:complete-01",visitId:session.visit!.id,toStatus:"completed",outcome:"Test drive completed; quote requested."});expect(completed.visit.status).toBe("completed");expect(completed.visit.outcome).toContain("quote");});
  it("rejects skipped transitions and missing cancellation evidence",async()=>{const session=new MemorySession();await service(session).checkIn(checkIn);await expect(service(session).transition({actor,organizationId:"org_dealerflow",correlationId:"req_bad01",idempotencyKey:"visit:bad-01",visitId:session.visit!.id,toStatus:"completed",outcome:"Done"})).rejects.toBeInstanceOf(ShowroomVisitTransitionError);await expect(service(session).transition({actor,organizationId:"org_dealerflow",correlationId:"req_cancel01",idempotencyKey:"visit:cancel-01",visitId:session.visit!.id,toStatus:"cancelled"})).rejects.toBeInstanceOf(ShowroomVisitValidationError);});
  it("denies cross-location check-in",async()=>{const session=new MemorySession();await expect(service(session).checkIn({...checkIn,locationId:"loc_other01"})).rejects.toThrow("permission");expect(session.creationContextExists).not.toHaveBeenCalled();});
});
