import { generateEntityId } from "@/lib/core/identifiers";
import { assertAuthorized,type AuthorizationActor } from "@/lib/platform/auth";
import type { OrganizationScope,RequestContext } from "@/lib/platform/data";

export type ShowroomVisitStatus="checked-in"|"active"|"completed"|"cancelled";
export interface ShowroomVisitRecord extends OrganizationScope{id:string;locationId:string;customerId:string;leadId:string;appointmentId?:string;assignedUserId?:string;status:ShowroomVisitStatus;purpose:string;arrivedAt:string;startedAt?:string;completedAt?:string;cancelledAt?:string;outcome?:string;notes?:string;idempotencyKey:string}
export interface ShowroomVisitEvent extends OrganizationScope{id:string;visitId:string;fromStatus?:ShowroomVisitStatus;toStatus:ShowroomVisitStatus;reason?:string;occurredAt:string;idempotencyKey:string}
export interface ShowroomVisitSession{lock(scope:OrganizationScope,key:string):Promise<void>;findVisitByIdempotency(scope:OrganizationScope,key:string):Promise<ShowroomVisitRecord|null>;creationContextExists(scope:OrganizationScope,input:{customerId:string;leadId:string;appointmentId?:string;assignedUserId?:string}):Promise<boolean>;create(context:RequestContext,visit:ShowroomVisitRecord,event:ShowroomVisitEvent):Promise<ShowroomVisitRecord>;findTransition(scope:OrganizationScope,key:string):Promise<{visit:ShowroomVisitRecord;event:ShowroomVisitEvent}|null>;getForUpdate(scope:OrganizationScope,id:string):Promise<ShowroomVisitRecord|null>;transition(context:RequestContext,visit:ShowroomVisitRecord,event:ShowroomVisitEvent):Promise<ShowroomVisitRecord>}
export interface ShowroomVisitProvider{transaction<T>(operation:(session:ShowroomVisitSession)=>Promise<T>):Promise<T>}
export class ShowroomVisitValidationError extends Error{constructor(readonly issues:readonly string[]){super("Showroom visit data is invalid.");this.name="ShowroomVisitValidationError";}}
export class ShowroomVisitIntegrityError extends Error{constructor(message:string){super(message);this.name="ShowroomVisitIntegrityError";}}
export class ShowroomVisitTransitionError extends Error{constructor(readonly from:ShowroomVisitStatus,readonly to:ShowroomVisitStatus){super(`Showroom visit cannot transition from ${from} to ${to}.`);this.name="ShowroomVisitTransitionError";}}

export class ShowroomVisitService{
  constructor(private readonly provider:ShowroomVisitProvider){}
  async checkIn(request:{actor:AuthorizationActor;organizationId:string;locationId:string;correlationId:string;idempotencyKey:string;customerId:string;leadId:string;appointmentId?:string;assignedUserId?:string;purpose:string;arrivedAt?:string;notes?:string}){validateCheckIn(request);for(const capability of["customer.read","lead.read","appointment.read","appointment.create"]as const)assertAuthorized(request.actor,{capability,organizationId:request.organizationId,locationId:request.locationId});if(request.appointmentId)assertAuthorized(request.actor,{capability:"appointment.update",organizationId:request.organizationId,locationId:request.locationId});return this.provider.transaction(async(session)=>{await session.lock(request,request.idempotencyKey);const existing=await session.findVisitByIdempotency(request,request.idempotencyKey);if(existing)return{visit:existing,created:false};if(!await session.creationContextExists(request,{customerId:request.customerId,leadId:request.leadId,...(request.appointmentId?{appointmentId:request.appointmentId}:{}),...(request.assignedUserId?{assignedUserId:request.assignedUserId}:{})}))throw new ShowroomVisitIntegrityError("Customer, Lead, Appointment, assignee, or Location context is unavailable.");const now=request.arrivedAt??new Date().toISOString();const visit:ShowroomVisitRecord={id:generateEntityId("vis"),organizationId:request.organizationId,locationId:request.locationId,customerId:request.customerId,leadId:request.leadId,...(request.appointmentId?{appointmentId:request.appointmentId}:{}),...(request.assignedUserId?{assignedUserId:request.assignedUserId}:{}),status:"checked-in",purpose:request.purpose.trim(),arrivedAt:now,...(request.notes?.trim()?{notes:request.notes.trim()}:{}),idempotencyKey:request.idempotencyKey};return{visit:await session.create(context(request),visit,{id:generateEntityId("vse"),organizationId:request.organizationId,locationId:request.locationId,visitId:visit.id,toStatus:"checked-in",occurredAt:now,idempotencyKey:`create:${request.idempotencyKey}`}),created:true};});}
  async transition(request:{actor:AuthorizationActor;organizationId:string;correlationId:string;idempotencyKey:string;visitId:string;toStatus:"active"|"completed"|"cancelled";outcome?:string;reason?:string}){validateTransition(request);assertAuthorized(request.actor,{capability:"appointment.read",organizationId:request.organizationId});assertAuthorized(request.actor,{capability:"appointment.update",organizationId:request.organizationId});return this.provider.transaction(async(session)=>{await session.lock(request,request.idempotencyKey);const existing=await session.findTransition(request,request.idempotencyKey);if(existing){authorizeLocation(request.actor,request.organizationId,existing.visit.locationId);return{...existing,transitioned:false};}const current=await session.getForUpdate(request,request.visitId);if(!current)throw new ShowroomVisitIntegrityError("Showroom visit is unavailable.");authorizeLocation(request.actor,request.organizationId,current.locationId);if(!allowed[current.status].includes(request.toStatus))throw new ShowroomVisitTransitionError(current.status,request.toStatus);const occurredAt=new Date().toISOString();const visit:ShowroomVisitRecord={...current,status:request.toStatus,...(request.toStatus==="active"?{startedAt:occurredAt}:{}),...(request.toStatus==="completed"?{completedAt:occurredAt,outcome:request.outcome!.trim()}:{}),...(request.toStatus==="cancelled"?{cancelledAt:occurredAt}:{})};const event:ShowroomVisitEvent={id:generateEntityId("vse"),organizationId:request.organizationId,locationId:current.locationId,visitId:current.id,fromStatus:current.status,toStatus:request.toStatus,...(request.reason?.trim()?{reason:request.reason.trim()}:{}),occurredAt,idempotencyKey:request.idempotencyKey};return{visit:await session.transition(context({...request,locationId:current.locationId}),visit,event),event,transitioned:true};});}
}
const allowed:Record<ShowroomVisitStatus,readonly ShowroomVisitStatus[]>={"checked-in":["active","cancelled"],active:["completed","cancelled"],completed:[],cancelled:[]};
function validateCheckIn(request:{locationId:string;customerId:string;leadId:string;idempotencyKey:string;purpose:string;arrivedAt?:string;notes?:string}){const issues:string[]=[];for(const[field,value]of[["locationId",request.locationId],["customerId",request.customerId],["leadId",request.leadId],["idempotencyKey",request.idempotencyKey],["purpose",request.purpose]]as const)if(!value.trim())issues.push(`${field} is required.`);if(request.purpose.length>200)issues.push("purpose must not exceed 200 characters.");if(request.notes&&request.notes.length>2000)issues.push("notes must not exceed 2000 characters.");if(request.arrivedAt&&Number.isNaN(Date.parse(request.arrivedAt)))issues.push("arrivedAt must be a valid ISO timestamp.");if(issues.length)throw new ShowroomVisitValidationError(issues);}
function validateTransition(request:{visitId:string;idempotencyKey:string;toStatus:string;outcome?:string;reason?:string}){const issues:string[]=[];if(!request.visitId.trim())issues.push("visitId is required.");if(!request.idempotencyKey.trim())issues.push("idempotencyKey is required.");if(request.toStatus==="completed"&&!request.outcome?.trim())issues.push("outcome is required to complete a visit.");if(request.outcome&&request.outcome.length>500)issues.push("outcome must not exceed 500 characters.");if(request.toStatus==="cancelled"&&!request.reason?.trim())issues.push("reason is required to cancel a visit.");if(request.reason&&request.reason.length>1000)issues.push("reason must not exceed 1000 characters.");if(issues.length)throw new ShowroomVisitValidationError(issues);}
function authorizeLocation(actor:AuthorizationActor,organizationId:string,locationId:string){assertAuthorized(actor,{capability:"appointment.read",organizationId,locationId});assertAuthorized(actor,{capability:"appointment.update",organizationId,locationId});}
function context(request:{actor:AuthorizationActor;organizationId:string;correlationId:string;locationId?:string}):RequestContext{return{actorId:request.actor.userId,organizationId:request.organizationId,correlationId:request.correlationId,...(request.locationId?{locationId:request.locationId}:{})};}
