import { describe,expect,it } from "vitest";
import { assertSyntheticEnvironment, assertSyntheticReset, resolveSyntheticDatabaseUrl, syntheticSeedOptions } from "./seed-synthetic-pilot.mjs";

describe("synthetic pilot seed guard",()=>{
  it("requires non-production and explicit seed confirmation",()=>{expect(()=>assertSyntheticEnvironment("production","SYNTHETIC-DEMO")).toThrow("disabled in production");expect(()=>assertSyntheticEnvironment("staging","wrong")).toThrow("--confirm");expect(()=>assertSyntheticEnvironment("staging","SYNTHETIC-DEMO")).not.toThrow();});
  it("requires non-production, reset confirmation, and the exact fixture version",()=>{expect(()=>assertSyntheticReset("production","RESET-SYNTHETIC-DEMO","pilot-demo-v1")).toThrow("disabled in production");expect(()=>assertSyntheticReset("staging","wrong","pilot-demo-v1")).toThrow("--confirm");expect(()=>assertSyntheticReset("staging","RESET-SYNTHETIC-DEMO","wrong")).toThrow("--fixture-version");expect(()=>assertSyntheticReset("staging","RESET-SYNTHETIC-DEMO","pilot-demo-v1")).not.toThrow();});
  it("requires a separate database identity for reset execution",()=>{expect(resolveSyntheticDatabaseUrl("seed",{DATABASE_URL:"postgres://runtime"})).toBe("postgres://runtime");expect(resolveSyntheticDatabaseUrl("reset",{DATABASE_URL:"postgres://runtime",SYNTHETIC_RESET_DATABASE_URL:"postgres://maintenance"})).toBe("postgres://maintenance");expect(()=>resolveSyntheticDatabaseUrl("reset",{DATABASE_URL:"postgres://runtime"})).toThrow("dedicated reset identity");});
  it("propagates the canonical governed version without substituting the template version",()=>{expect(syntheticSeedOptions("reset")).toEqual({reset:true,governedFixtureVersion:"pilot-demo-v1"});expect(syntheticSeedOptions("reset").governedFixtureVersion).not.toBe("v1");expect(syntheticSeedOptions("seed")).toEqual({reset:false});});
});
