import { describe,expect,it,vi } from "vitest";
import type { AuthorizationActor } from "@/lib/platform/auth";
import { resolveTenantConfiguration } from "@/lib/platform/tenant";
import { ManageTenantConfigurationService,TenantConfigurationConflictError,type TenantConfigurationProvider } from "./manage-tenant-configuration";
const configuration=resolveTenantConfiguration({id:"org_dealerflow",slug:"dealerflow",vertical:"automotive",brand:{organizationName:"DealerFlow Motors",productName:"DealerFlow"}});
const actor:AuthorizationActor={userId:"usr_admin01",memberships:[{organizationId:"org_dealerflow",locationIds:"all",capabilities:["organization.configure"]}]};
function provider(saved=true):TenantConfigurationProvider{return{read:vi.fn(),save:vi.fn().mockResolvedValue(saved),history:vi.fn().mockResolvedValue([]),restore:vi.fn().mockResolvedValue(saved)};}
describe("ManageTenantConfigurationService",()=>{
  it("validates and saves configuration behind organization.configure",async()=>{const target=provider();await new ManageTenantConfigurationService(target).update({actor,organizationId:"org_dealerflow",expectedVersion:"v1",configuration:{id:configuration.id,slug:configuration.slug,vertical:configuration.vertical,brand:configuration.brand,features:{service:true}}});expect(target.save).toHaveBeenCalledWith(expect.objectContaining({actorId:"usr_admin01",organizationId:"org_dealerflow",expectedVersion:"v1",configuration:expect.objectContaining({features:expect.objectContaining({service:true})})}));});
  it("rejects cross-tenant administration",async()=>{const target=provider();await expect(new ManageTenantConfigurationService(target).update({actor,organizationId:"org_other01",expectedVersion:"v1",configuration:{id:"org_other01",slug:"other",vertical:"automotive",brand:{organizationName:"Other",productName:"Other"}}})).rejects.toThrow("permission");expect(target.save).not.toHaveBeenCalled();});
  it("surfaces optimistic concurrency conflicts",async()=>{await expect(new ManageTenantConfigurationService(provider(false)).update({actor,organizationId:"org_dealerflow",expectedVersion:"old",configuration:{id:configuration.id,slug:configuration.slug,vertical:configuration.vertical,brand:configuration.brand}})).rejects.toBeInstanceOf(TenantConfigurationConflictError);});
  it("restores only valid tenant version identifiers",async()=>{const target=provider();await new ManageTenantConfigurationService(target).restore({actor,organizationId:"org_dealerflow",expectedVersion:"current",versionId:"ocv_snapshot01"});expect(target.restore).toHaveBeenCalledWith(expect.objectContaining({versionId:"ocv_snapshot01"}));await expect(new ManageTenantConfigurationService(target).restore({actor,organizationId:"org_dealerflow",expectedVersion:"current",versionId:"other"})).rejects.toThrow("invalid");});
});
