import { NextResponse } from "next/server";
import { DealIntegrityError, DealService, DealTransitionError, DealValidationError } from "@/lib/application/deals";
import { AuthorizationError } from "@/lib/platform/auth";
import { AuthenticationError, MembershipError, PostgresMembershipReader, authenticateOrganizationRequest } from "@/lib/server/auth";
import { getDatabasePool } from "@/lib/server/database";
import { PostgresDealProvider } from "@/lib/server/deals";
import { resolveCorrelationId, StructuredTelemetry } from "@/lib/server/observability";

export const runtime = "nodejs"; export const dynamic = "force-dynamic"; interface Context { params: Promise<{ organizationId: string; dealId: string }> }
export async function POST(request: Request, context: Context) { const correlationId = resolveCorrelationId(request); let organizationId: string | undefined; try { const params = await context.params; organizationId = params.organizationId; const { dealId } = params; const body = objectValue(await request.json()); const idempotencyKey = request.headers.get("idempotency-key")?.trim(); if (!idempotencyKey) return problem(400, "invalid_request", "Idempotency-Key is required.", correlationId); const status = enumValue(body.toStatus, ["draft", "working", "pending-approval", "approved", "contracted", "delivered", "cancelled"] as const); if (!status || status === "draft") throw new DealValidationError(["toStatus is invalid."]); const pool = getDatabasePool(); const actor = await authenticateOrganizationRequest(request, organizationId, new PostgresMembershipReader(pool)); const result = await new DealService(new PostgresDealProvider(pool, { userId: actor.userId, organizationId })).transition({ actor, organizationId, ...(optionalString(body.locationId) ? { locationId: optionalString(body.locationId) } : {}), correlationId, idempotencyKey, dealId, toStatus: status, ...(optionalString(body.reason) ? { reason: optionalString(body.reason) } : {}) }); return NextResponse.json(result, { status: 200, headers: { "cache-control": "no-store", "x-correlation-id": correlationId } }); } catch (error) { return failure(error, correlationId, organizationId); } }
function objectValue(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new DealValidationError(["Request data must be an object."]); return value as Record<string, unknown>; } function optionalString(value: unknown) { return typeof value === "string" && value.trim() ? value : undefined; } function enumValue<const V extends readonly string[]>(value: unknown, values: V): V[number] | undefined { return typeof value === "string" && values.includes(value) ? value as V[number] : undefined; }
function failure(error: unknown, correlationId: string, organizationId?: string) { if (error instanceof SyntaxError) return problem(400, "invalid_json", "Request body must be valid JSON.", correlationId); if (error instanceof AuthenticationError) return problem(401, "unauthorized", error.message, correlationId); if (error instanceof MembershipError || error instanceof AuthorizationError) return problem(403, "forbidden", "Deal transition is not permitted.", correlationId); if (error instanceof DealValidationError) return NextResponse.json({ error: "invalid_request", message: error.message, issues: error.issues, correlationId }, { status: 400, headers: { "cache-control": "no-store", "x-correlation-id": correlationId } }); if (error instanceof DealIntegrityError) return problem(409, "data_conflict", error.message, correlationId); if (error instanceof DealTransitionError) return problem(409, "invalid_transition", error.message, correlationId); new StructuredTelemetry().emit({ code: "deal.transition.failed", severity: "error", correlationId, ...(organizationId ? { organizationId } : {}), attributes: { errorName: error instanceof Error ? error.name : "UnknownError", databaseCode: databaseErrorCode(error) } }); return problem(500, "internal_error", "The deal could not be updated.", correlationId); }
function databaseErrorCode(error: unknown): string | null { return typeof error === "object" && error !== null && "code" in error && typeof error.code === "string" ? error.code : null; }
function problem(status: number, error: string, message: string, correlationId: string) { return NextResponse.json({ error, message, correlationId }, { status, headers: { "cache-control": "no-store", "x-correlation-id": correlationId } }); }
