import type{Capability,OrganizationMembership}from"@/lib/platform/auth";import{withTenantDatabaseContext,type DatabasePool}from"@/lib/server/database";
export interface CommandCenterException{id:string;label:string;count:number;detail:string;href:string;priority:"normal"|"important"|"urgent"}
export interface CommandCenterModel{exceptions:readonly CommandCenterException[];evidence:{smsConfigured:boolean;smsAccepted:number;smsFailures:number;emailSent:number;emailFailures:number};generatedAt:string}
interface Row{unworked_leads:string;overdue_tasks:string;appointments_at_risk:string;pending_deals:string;inventory_missing_photos:string;sms_configured:boolean;sms_accepted:string;sms_failures:string;email_sent:string;email_failures:string}
export class CommandCenterReader{constructor(private readonly pool:DatabasePool){}read(input:{userId:string;organizationId:string;membership:OrganizationMembership}):Promise<CommandCenterModel>{return withTenantDatabaseContext(this.pool,{userId:input.userId,organizationId:input.organizationId},async client=>{const all=input.membership.locationIds==="all",locations=all?[]:input.membership.locationIds,caps=new Set<Capability>(input.membership.capabilities);const result=await client.query(`SELECT
CASE WHEN $4 THEN (SELECT count(*) FROM leads WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status IN ('open','working','qualified') AND assigned_user_id IS NULL) ELSE 0 END::text unworked_leads,
CASE WHEN $5 THEN (SELECT count(*) FROM tasks WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status IN ('open','in-progress') AND due_at<now()) ELSE 0 END::text overdue_tasks,
CASE WHEN $6 THEN (SELECT count(*) FROM appointments WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status='scheduled' AND starts_at>=now() AND starts_at<now()+interval '2 days') ELSE 0 END::text appointments_at_risk,
CASE WHEN $7 THEN (SELECT count(*) FROM deals WHERE organization_id=$1 AND ($2 OR location_id=ANY($3::text[])) AND status='pending-approval') ELSE 0 END::text pending_deals,
CASE WHEN $8 THEN (SELECT count(*) FROM inventory_units unit WHERE unit.organization_id=$1 AND ($2 OR unit.location_id=ANY($3::text[])) AND unit.status='available' AND NOT EXISTS(SELECT 1 FROM inventory_unit_media media WHERE media.organization_id=unit.organization_id AND media.inventory_unit_id=unit.id AND media.status='active' AND media.source_type='actual')) ELSE 0 END::text inventory_missing_photos,
CASE WHEN $9 THEN EXISTS(SELECT 1 FROM integration_accounts WHERE organization_id=$1 AND active=true AND provider='twilio' AND ($2 OR location_id IS NULL OR location_id=ANY($3::text[]))) ELSE false END sms_configured,
CASE WHEN $9 THEN (SELECT count(*) FROM communication_send_attempts WHERE organization_id=$1 AND created_at>now()-interval '7 days' AND status='accepted' AND ($2 OR location_id IS NULL OR location_id=ANY($3::text[]))) ELSE 0 END::text sms_accepted,
CASE WHEN $9 THEN (SELECT count(*) FROM communication_send_attempts WHERE organization_id=$1 AND created_at>now()-interval '7 days' AND status IN ('delivery-unknown','rejected') AND ($2 OR location_id IS NULL OR location_id=ANY($3::text[]))) ELSE 0 END::text sms_failures,
CASE WHEN $10 THEN (SELECT count(*) FROM transactional_email_messages WHERE organization_id=$1 AND created_at>now()-interval '7 days' AND status='sent') ELSE 0 END::text email_sent,
CASE WHEN $10 THEN (SELECT count(*) FROM transactional_email_messages WHERE organization_id=$1 AND created_at>now()-interval '7 days' AND status='failed') ELSE 0 END::text email_failures`,[input.organizationId,all,locations,caps.has("lead.read"),caps.has("task.read"),caps.has("appointment.read"),caps.has("deal.read"),caps.has("inventory.read"),caps.has("communication.read"),caps.has("organization.configure")])as{rows:Row[]};return model(result.rows[0]!,input.organizationId,caps);});}}
function model(row:Row,organizationId:string,caps:Set<Capability>):CommandCenterModel{const base=`/organizations/${organizationId}`,items:CommandCenterException[]=[];const add=(capability:Capability,item:CommandCenterException)=>{if(caps.has(capability)&&item.count>0)items.push(item);};add("lead.read",{id:"unworked-leads",label:"Unworked Leads",count:Number(row.unworked_leads),detail:"Active Leads without an assigned employee.",href:`${base}/leads`,priority:"urgent"});add("task.read",{id:"overdue-tasks",label:"Overdue Follow-Up",count:Number(row.overdue_tasks),detail:"Open or in-progress tasks past due.",href:`${base}/workspace`,priority:"important"});add("appointment.read",{id:"appointments-at-risk",label:"Appointments at Risk",count:Number(row.appointments_at_risk),detail:"Scheduled, not confirmed, and starting within 48 hours.",href:`${base}/workspace`,priority:"important"});add("deal.read",{id:"pending-deals",label:"Deals Needing Attention",count:Number(row.pending_deals),detail:"Deals currently pending manager approval.",href:`${base}/desking`,priority:"urgent"});add("inventory.read",{id:"inventory-media",label:"Inventory Missing Photos",count:Number(row.inventory_missing_photos),detail:"Available units without verified actual media.",href:`${base}/inventory`,priority:"normal"});if(caps.has("organization.configure"))add("communication.read",{id:"message-failures",label:"SMS Delivery Exceptions",count:Number(row.sms_failures),detail:"Rejected or delivery-unknown attempts in the last seven days.",href:`${base}/operations/messages`,priority:"urgent"});const sms=caps.has("communication.read"),email=caps.has("organization.configure");return{exceptions:items,evidence:{smsConfigured:sms&&row.sms_configured,smsAccepted:sms?Number(row.sms_accepted):0,smsFailures:sms?Number(row.sms_failures):0,emailSent:email?Number(row.email_sent):0,emailFailures:email?Number(row.email_failures):0},generatedAt:new Date().toISOString()};}
