import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import Link from "next/link";

import { AppShell } from "@/components/app-shell";
import { ManageTenantConfigurationService } from "@/lib/application/organizations";
import { tenantFeatureKeys, type TenantFeatureKey } from "@/lib/platform/tenant";
import { PostgresTenantConfigurationProvider } from "@/lib/server/organizations";
import { loadDirectoryContext } from "../../_lib/load-directory-context";

export const dynamic = "force-dynamic";
interface Props { params: Promise<{organizationId:string}>; searchParams:Promise<{notice?:string;error?:string}> }

export default async function ConfigurationPage({params,searchParams}:Props){
  const {organizationId}=await params;const context=await loadDirectoryContext(organizationId,"organization.configure");
  const service=new ManageTenantConfigurationService(new PostgresTenantConfigurationProvider(context.pool));const[current,history]=await Promise.all([service.read(context.actor,organizationId),service.history(context.actor,organizationId)]);const feedback=await searchParams;const base=`/organizations/${organizationId}/settings/configuration`;
  return <AppShell organizationId={organizationId} navigationCapabilities={context.membership.capabilities} activeHref={base} breadcrumbs={[{label:context.organization.name},{label:"Configuration"}]} user={{name:context.session.user.name,email:context.session.user.email,...(context.session.user.image?{image:context.session.user.image}:{})}}>
    <section aria-labelledby="configuration-heading" className="mx-auto max-w-5xl"><h1 className="text-2xl font-semibold tracking-tight" id="configuration-heading">Workspace configuration</h1><p className="mt-1 text-sm text-muted-foreground">Control tenant-owned product identity, terminology, and available modules.</p>
      {feedback.notice?<p className="mt-4 rounded-lg border bg-muted p-3 text-sm" role="status">{feedback.notice}</p>:null}{feedback.error?<p className="mt-4 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive" role="alert">{feedback.error}</p>:null}
      {context.membership.capabilities.includes("quote.configure_thresholds")?<section className="mt-6 rounded-xl border bg-card p-4 shadow-soft sm:flex sm:items-center sm:justify-between sm:gap-4 sm:p-5"><div><h2 className="font-semibold">Quote approval rules</h2><p className="mt-1 text-sm text-muted-foreground">Control whether manager approval is required before a Quote can be presented.</p></div><Link className="focus-ring mt-3 inline-flex min-h-10 items-center justify-center rounded-lg border px-3 text-sm font-medium hover:bg-muted sm:mt-0" href={`/organizations/${organizationId}/settings/configuration/quote-approvals`}>Manage rules</Link></section>:null}
      {context.membership.capabilities.includes("inventory.cost.read")&&context.membership.capabilities.includes("quote.pack.read")?<section className="mt-4 rounded-xl border bg-card p-4 shadow-soft sm:flex sm:items-center sm:justify-between sm:gap-4 sm:p-5"><div><h2 className="font-semibold">Inventory cost &amp; pack</h2><p className="mt-1 text-sm text-muted-foreground">Manage authoritative cost, pack resolution, and profitability readiness.</p></div><Link className="focus-ring mt-3 inline-flex min-h-10 items-center justify-center rounded-lg border px-3 text-sm font-medium hover:bg-muted sm:mt-0" href={`/organizations/${organizationId}/settings/configuration/profitability`}>Manage inputs</Link></section>:null}
      <form action={saveConfiguration.bind(null,organizationId)} className="mt-6 space-y-6"><input name="version" type="hidden" value={current.version}/>
        <fieldset className="grid gap-4 rounded-xl border bg-card p-4 shadow-soft sm:grid-cols-2 sm:p-5"><legend className="px-1 text-base font-semibold">Identity and support</legend><Field defaultValue={current.configuration.brand.productName} label="Product name" name="productName" required/><Field defaultValue={current.configuration.brand.supportEmail} label="Support email" name="supportEmail" type="email"/><Field defaultValue={current.configuration.brand.supportPhone} label="Support phone" name="supportPhone"/><div className="rounded-lg border bg-muted/30 p-3 text-sm text-muted-foreground"><p className="font-medium text-foreground">Custom domain</p><p className="mt-1">Deferred until DNS ownership and host verification are implemented.</p></div><Field defaultValue={current.configuration.brand.logoUrl} label="Logo URL" name="logoUrl" placeholder="https://assets.example.com/logo.png" type="url"/><Field defaultValue={current.configuration.brand.logoDarkUrl} label="Dark-theme logo URL" name="logoDarkUrl" placeholder="https://assets.example.com/logo-dark.png" type="url"/><Field defaultValue={current.configuration.brand.faviconUrl} label="Favicon URL" name="faviconUrl" placeholder="https://assets.example.com/favicon.png" type="url"/><p className="self-end rounded-lg border bg-muted/30 p-3 text-xs text-muted-foreground">Brand assets must use credential-free HTTPS URLs. Use square artwork for the shell logo and favicon.</p><Field defaultValue={current.configuration.brand.colors.primary} label="Primary color" name="color.primary" required type="color"/><Field defaultValue={current.configuration.brand.colors.secondary} label="Secondary color" name="color.secondary" required type="color"/><Field defaultValue={current.configuration.brand.colors.accent} label="Accent color" name="color.accent" required type="color"/></fieldset>
        <fieldset className="rounded-xl border bg-card p-4 shadow-soft sm:p-5"><legend className="px-1 text-base font-semibold">Modules</legend><div className="mt-2 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{tenantFeatureKeys.map((feature)=><label className="flex min-h-11 items-center gap-3 rounded-lg border p-3 text-sm" key={feature}><input defaultChecked={current.configuration.features[feature]} name="features" type="checkbox" value={feature}/><span className="capitalize">{feature.replace(/([A-Z])/g," $1")}</span></label>)}</div><p className="mt-3 text-xs text-muted-foreground">Feature flags control availability but never replace server-side capability checks.</p></fieldset>
        <fieldset className="grid gap-4 rounded-xl border bg-card p-4 shadow-soft sm:grid-cols-2 sm:p-5"><legend className="px-1 text-base font-semibold">Terminology</legend>{Object.entries(current.configuration.terminology).map(([name,value])=><Field defaultValue={value} key={name} label={name.replace(/([A-Z])/g," $1")} name={`term.${name}`} required/>)}</fieldset>
        <button className="focus-ring min-h-11 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground hover:bg-primary/90">Save configuration</button>
      </form>
      <section aria-labelledby="configuration-history" className="mt-8 overflow-hidden rounded-xl border bg-card shadow-soft"><div className="border-b p-4 sm:p-5"><h2 className="font-semibold" id="configuration-history">Configuration history</h2><p className="mt-1 text-sm text-muted-foreground">Restore one of the latest 20 immutable snapshots.</p></div>{history.length?<ul className="divide-y" role="list">{history.map((item,index)=><li className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5" key={item.id}><div><p className="text-sm font-medium">{item.productName}</p><p className="mt-1 text-xs text-muted-foreground">{item.changeKind} · {new Date(item.createdAt).toLocaleString("en-US")}</p></div><form action={restoreConfiguration.bind(null,organizationId)}><input name="version" type="hidden" value={current.version}/><input name="versionId" type="hidden" value={item.id}/><button className="focus-ring h-9 rounded-lg border bg-background px-3 text-sm font-medium hover:bg-muted" disabled={index===0}>{index===0?"Current":"Restore"}</button></form></li>)}</ul>:<p className="p-6 text-sm text-muted-foreground">The first saved change will create a recoverable snapshot.</p>}</section>
    </section>
  </AppShell>;
}

async function restoreConfiguration(organizationId:string,formData:FormData){"use server";const base=`/organizations/${organizationId}/settings/configuration`;try{const context=await loadDirectoryContext(organizationId,"organization.configure");await new ManageTenantConfigurationService(new PostgresTenantConfigurationProvider(context.pool)).restore({actor:context.actor,organizationId,expectedVersion:String(formData.get("version")??""),versionId:String(formData.get("versionId")??"")});revalidatePath(base);}catch{redirect(`${base}?error=${encodeURIComponent("Configuration was not restored. Reload and try again.")}`)}redirect(`${base}?notice=${encodeURIComponent("Configuration restored from history.")}`)}

function Field({defaultValue,label,name,placeholder,required=false,type="text"}:{defaultValue?:string;label:string;name:string;placeholder?:string;required?:boolean;type?:string}){return <div className="space-y-1"><label className="text-sm font-medium capitalize" htmlFor={name}>{label}</label><input className="focus-ring h-10 w-full rounded-lg border bg-background px-3 text-sm" defaultValue={defaultValue} id={name} name={name} placeholder={placeholder} required={required} type={type}/></div>}

async function saveConfiguration(organizationId:string,formData:FormData){"use server";const base=`/organizations/${organizationId}/settings/configuration`;try{const context=await loadDirectoryContext(organizationId,"organization.configure");const service=new ManageTenantConfigurationService(new PostgresTenantConfigurationProvider(context.pool));const current=await service.read(context.actor,organizationId);const selected=new Set(formData.getAll("features").map(String));const features=Object.fromEntries(tenantFeatureKeys.map((key)=>[key,selected.has(key)])) as Record<TenantFeatureKey,boolean>;const read=(name:string)=>String(formData.get(name)??"").trim();await service.update({actor:context.actor,organizationId,expectedVersion:read("version"),configuration:{id:current.configuration.id,slug:current.configuration.slug,vertical:current.configuration.vertical,brand:{...current.configuration.brand,productName:read("productName"),colors:{primary:read("color.primary"),secondary:read("color.secondary"),accent:read("color.accent")},...(read("logoUrl")?{logoUrl:read("logoUrl")}:{logoUrl:undefined}),...(read("logoDarkUrl")?{logoDarkUrl:read("logoDarkUrl")}:{logoDarkUrl:undefined}),...(read("faviconUrl")?{faviconUrl:read("faviconUrl")}:{faviconUrl:undefined}),...(read("supportEmail")?{supportEmail:read("supportEmail")}:{supportEmail:undefined}),...(read("supportPhone")?{supportPhone:read("supportPhone")}:{supportPhone:undefined})},features,terminology:{item:read("term.item"),itemPlural:read("term.itemPlural"),itemIdentifier:read("term.itemIdentifier"),location:read("term.location"),locationPlural:read("term.locationPlural"),inventoryUnit:read("term.inventoryUnit")}}});revalidatePath(base);}catch{redirect(`${base}?error=${encodeURIComponent("Configuration was not saved. Reload the page and verify every value.")}`)}redirect(`${base}?notice=${encodeURIComponent("Workspace configuration saved.")}`)}
