import type { Pool } from "pg";
import type { RecommendationRunProvider } from "@/lib/application/ai";
import { generateEntityId } from "@/lib/core/identifiers";
import { withTenantDatabaseContext } from "@/lib/server/database";

export class PostgresRecommendationRunProvider implements RecommendationRunProvider{
  constructor(private readonly pool:Pool){}
  async begin(input:Parameters<RecommendationRunProvider["begin"]>[0]){return withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async(client)=>{const id=generateEntityId("air");const result=await client.query(`INSERT INTO ai_recommendation_runs(id,organization_id,customer_id,lead_id,prompt_version,evidence,idempotency_key,initiated_by) SELECT $1,$2,$3,$4,$5,$6::jsonb,$7,$8 WHERE EXISTS(SELECT 1 FROM customers WHERE organization_id=$2 AND id=$3) AND ($4::text IS NULL OR EXISTS(SELECT 1 FROM leads WHERE organization_id=$2 AND customer_id=$3 AND id=$4)) AND (SELECT count(*) FROM ai_recommendation_runs WHERE organization_id=$2 AND initiated_by=$8 AND created_at>now()-interval '1 hour')<30 ON CONFLICT(organization_id,idempotency_key) DO UPDATE SET updated_at=ai_recommendation_runs.updated_at RETURNING id,(xmax=0) created,status::text,model,output,refusal,provider_response_id,input_tokens,output_tokens,latency_ms`,[id,input.organizationId,input.customerId,input.leadId??null,input.promptVersion,JSON.stringify(input.evidence),input.idempotencyKey,input.actorId]) as{rows:Array<{id:string;created:boolean;status:string;model:string|null;output:unknown;refusal:string|null;provider_response_id:string|null;input_tokens:number|null;output_tokens:number|null;latency_ms:number|null}>};const row=result.rows[0];if(!row)throw new Error("Customer or Lead evidence scope is invalid or the AI request limit was reached.");const generation=!row.created&&(row.status==="completed"||row.status==="refused")&&row.model&&row.provider_response_id&&row.latency_ms!==null?{providerResponseId:row.provider_response_id,model:row.model,...(row.status==="completed"&&isStoredRecommendation(row.output)?{recommendation:row.output}:{}),...(row.refusal?{refusal:row.refusal}:{}),...(row.input_tokens!==null?{inputTokens:row.input_tokens}:{}),...(row.output_tokens!==null?{outputTokens:row.output_tokens}:{}),latencyMs:row.latency_ms}:undefined;return{runId:row.id,created:row.created,...(generation?{generation}:{})};});}
  async complete(input:Parameters<RecommendationRunProvider["complete"]>[0]){await withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async(client)=>{const generation=input.generation;const status=generation.refusal?"refused":"completed";const result=await client.query(`UPDATE ai_recommendation_runs SET status=$3,model=$4,output=$5::jsonb,refusal=$6,provider_response_id=$7,input_tokens=$8,output_tokens=$9,latency_ms=$10,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status='pending' RETURNING id`,[input.organizationId,input.runId,status,generation.model,generation.recommendation?JSON.stringify(generation.recommendation):null,generation.refusal??null,generation.providerResponseId,generation.inputTokens??null,generation.outputTokens??null,generation.latencyMs]) as{rows:Array<{id:string}>};if(!result.rows[0])throw new Error("Recommendation run is no longer pending.");});}
  async fail(input:Parameters<RecommendationRunProvider["fail"]>[0]){await withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async(client)=>{await client.query("UPDATE ai_recommendation_runs SET status='failed',failure_code=$3,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status='pending'",[input.organizationId,input.runId,input.code]);});}
  async review(input:Parameters<RecommendationRunProvider["review"]>[0]){return withTenantDatabaseContext(this.pool,{userId:input.actorId,organizationId:input.organizationId},async(client)=>{const result=await client.query(`UPDATE ai_recommendation_runs SET review_decision=$3,review_note=$4,reviewed_by=$5,reviewed_at=now(),updated_at=now() WHERE organization_id=$1 AND id=$2 AND status='completed' AND review_decision IS NULL RETURNING id`,[input.organizationId,input.runId,input.decision,input.note??null,input.actorId]) as{rows:Array<{id:string}>};return result.rows.length===1;});}
}
function isStoredRecommendation(value:unknown):value is NonNullable<import("@/lib/application/ai").RecommendationGeneration["recommendation"]>{return typeof value==="object"&&value!==null&&"primaryAction" in value&&typeof value.primaryAction==="string";}
